#!/bin/sh
set -e
. "$__distro_path_lib"
__mode="${1:-}"

list_are="1. Youtube
2. Anime
3. Moive/TV-Show
4. IP-TV"

FZF_DEFAULT_OPTS=""
FZF_CTRL_R_OPTS=""

__mode="$(printf "%s" "$list_are" | fzf --info=hidden --layout=reverse --height=100% --exact --cycle --ansi)"

case "${__mode}" in
	yt|1*)  name="youtube-cli" ;;
	ani|2*) name="anime-cli" ;;
	mov|3*) name="movie" ;;
	tv|4*)  name="iptv" ;;
    *)	    name="youtube-cli" ;;
esac

"${__distro_path_root}/bin_extra/X11/TV"/${name} $@
