#!/bin/sh
#called by : my-installer
app_name="discord"
if [ -f "${__distro_path_system_ready}/Distrobox_ready" ];then
	Distrobox_package_installer_ ${app_name} || continue
else
	pacstall -I discord
fi
