#!/bin/sh

app_name="heroic"

if [ -f '/usr/share/my_stuff/system_files/Distrobox_ready' ];then
	Distrobox_Package_update_
	clear
	say 'Installing package...' 1
	Distrobox_package_installer_ ${app_name} || continue
else
	Package_update_
	clear
	say 'Installing package...' 1
	my-superuser flatpak install flathub com.discordapp.Discord
fi
