#!/bin/sh
. "${my_stuff_display_manager_lib_path}"

printf '\n\n  1. Install Lazyvim? \n  2. Install kickstart?\n  3. Install ThePrimeagen config?\n  4. Install kickstart (ChrisTitusTech)?\n\nInsert appropriate number: '
stty -icanon -echo time 0 min 1
__choice="$(head -c1)"
stty icanon echo

Title="Neovim"
app_name="nvim"
extra_apps_="cmake ripgrep fd-find python3-venv luarocks golang-go shellcheck $clip_manager_package_name"

say "Installing ${Title} updater and installer..." 1
repobin --root install neovim/neovim || failed_to_run "failed to run ${app_name} ."

say 'Installing extra packages...' 1
Package_installer_ "${extra_apps_}" || continue

. "${_APPS_LIBDIR}/IDE/Neovim_Extra/post_install.sh"
