#!/bin/sh
app_name="code"

say "Configuring repositories..."
download_key "gpg" "https://packages.microsoft.com/keys/microsoft.asc" "/usr/share/keyrings/vscode-keyring.gpg"
add_repo "vscode" "deb [arch=amd64 signed-by=/usr/share/keyrings/vscode-keyring.gpg] http://packages.microsoft.com/repos/vscode stable main"

Package_update_

clear

say "Installing ${app_name} ..." 1

Package_installer_ "${app_name}" || continue
copy_from_extra_skel ".config/Code" || continue

