#!/bin/sh
# need superuser : called by my-installer
"${__distro_path_root}"/bin/not_add_2_path/my-installer --install-needed "GPU" || continue
app_name="Gaming Essential"
. "${__distro_path_root}/os-release"
distro_name_and_ver_3=$(printf "%s" "$distro_name_and_ver_2" | cut -c1 | tr '[:lower:]' '[:upper:]')$(printf "%s" "$distro_name_and_ver_2" | cut -c2-)

SHELL_EXT="$(which gnome-shell >/dev/null 2>&1 && echo gnome-shell-extension-gamemode)"

say 'add new repo ...' 1
[ ! -d "/etc/apt/keyrings" ] && my-superuser mkdir -pm755 /etc/apt/keyrings
if ! dpkg -q lutris 2>/dev/null;then
	download_key "gpg" "https://download.opensuse.org/repositories/home:/strycore/$distro_name_and_ver_3/Release.key" "/usr/share/keyrings/lutris.gpg"
	add_repo "lutris" "deb [signed-by=/usr/share/keyrings/lutris.gpg] https://download.opensuse.org/repositories/home:/strycore/$distro_name_and_ver_3/ ./"
fi

if ! dpkg -q winehq-staging 2>/dev/null;then
	download_key "download" "https://dl.winehq.org/wine-builds/winehq.key" "/etc/apt/keyrings/winehq-archive.key"
	download_key "download" "https://dl.winehq.org/wine-builds/debian/dists/${version_codename}/winehq-${version_codename}.sources" "/etc/apt/sources.list.d/winehq-${version_codename}.sources"
fi

my-superuser dpkg --add-architecture i386

clear
Package_update_

Package_installer_ libcec6 xboxdrv || continue     
Package_installer_ "mangohud goverlay gamemode $SHELL_EXT lutris" || continue                
Package_installer_ --install-recommends winehq-staging || continue     
Package_installer_ wine wine64 wine-binfmt || continue     

Package_installer_ steam || continue

install_as_dependency pacstall || continue
pacstall_install protonplus || continue
pacstall_install bottles || continue

flatpak_install "pupgui2" "net.davidotek.pupgui2" "nonflathub" || continue        
flatpak_install "Flatseal" "com.github.tchx84.Flatseal" || continue     

remove_system_ready_file GPU_Drivers_ready
generate_system_ready_file Gaming_ready
update_pipemenu preferences.sh || failed_to_run "failed to run generate_pipemenu/preferences.sh"
