#!/bin/sh
if grep -qE " backports" /etc/apt/sources.list;then # enabled
	return 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	return 1
fi

Package_installer_ software-properties-common
enable_repo backports
	
Package_update_
