#!/bin/sh
if [ "$Distro_installer_mode" = false ];then
	_SUPERUSER="my-superuser"
	[ "$(id -u)" -eq 0 ] && _SUPERUSER=""
fi

if grep -qE " backports" /etc/apt/sources.list;then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	say "Adding backports repo"
	Package_installer_ software-properties-common
	enable_repo backports
		
	Package_update_
	${_SUPERUSER} ln -s ${__distro_path_root}/Distro_Specific/tweeks_center/Extra/backports_install ${__distro_path_root}/system_files/bin
	command -v bash >/dev/null 2>&1 && ${_SUPERUSER} ln -s "${__distro_path_disabled_completion}"/bash/backports_install_auto_completion "${__distro_path_enabled_completion}"/bash
	command -v zsh >/dev/null 2>&1 && ${_SUPERUSER} ln -s "${__distro_path_disabled_completion}"/zsh/backports_install_auto_completion "${__distro_path_enabled_completion}"/zsh
fi
