#!/bin/sh
_SUPERUSER="my-superuser"
[ "$(id -u)" -eq 0 ] && _SUPERUSER=""

if grep -qE " universe| multiverse" /etc/apt/sources.list;then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	Package_installer_ software-properties-common
	enable_repo universe
	enable_repo multiverse
			
	Package_update_
fi
