#!/bin/sh
if [ "$Distro_installer_mode" = false ];then
	_SUPERUSER="my-superuser"
	[ "$(id -u)" -eq 0 ] && _SUPERUSER=""
fi

if grep -qE " universe| multiverse" /etc/apt/sources.list;then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	say "enable_universe_multiverse_repo"
	Package_installer_ software-properties-common
	enable_repo universe
	enable_repo multiverse
			
	Package_update_
fi
