#!/bin/sh
app_name="floorp"
set_as_default_package=true
prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false

say 'Adding Repo...' 1
download_key "gpg" "https://ppa.ablaze.one/KEY.gpg" "/usr/share/keyrings/Floorp.gpg"

add_repo "Floorp" "https://ppa.ablaze.one/Floorp.list"

Package_update_

clear

say "Installing ${app_name}..." 1
Package_installer_ "${app_name}" || continue

[ "$set_as_default_package" = true ] && my-alternatives --set "my-www-browser" "${app_name}"
