;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; main colors
background = {background}
foreground = {foreground}
foreground-alt = {foreground}
shade1 = {color1}
shade2 = {color2}
shade3 = {color1}
shade4 = {color2}
shade5 = {color1}
shade6 = {color2}
shade7 = {color1}
shade8 = {color7}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


