[colors]
  [colors.bright]
    black = '0x9da4a3'
    blue = '0xD59DC4'
    cyan = '0xA8DAD9'
    green = '0xD48EB3'
    magenta = '0xFEB3C2'
    red = '0xA5BFBF'
    white = '0xe1ebea'
    yellow = '0xFCB0BD'

  [colors.normal]
    black = '0x2d2b38'
    blue = '0xD59DC4'
    cyan = '0xA8DAD9'
    green = '0xD48EB3'
    magenta = '0xFEB3C2'
    red = '0xA5BFBF'
    white = '0xe1ebea'
    yellow = '0xFCB0BD'

  [colors.primary]
    background = '0x2d2b38'
    foreground = '0xe1ebea'
