[colors]
  [colors.bright]
    black = '0x858e88'
    blue = '0x5E857B'
    cyan = '0x77C3A6'
    green = '0x376464'
    magenta = '0x719789'
    red = '0x294D54'
    white = '0xbfccc3'
    yellow = '0x506D6B'

  [colors.normal]
    black = '0x0a030f'
    blue = '0x5E857B'
    cyan = '0x77C3A6'
    green = '0x376464'
    magenta = '0x719789'
    red = '0x294D54'
    white = '0xbfccc3'
    yellow = '0x506D6B'

  [colors.primary]
    background = '0x0a030f'
    foreground = '0xbfccc3'
