[colors]
  [colors.bright]
    black = '0x626483'
    blue = '0x58AFC2'
    cyan = '0x926BCA'
    green = '0xa6e22e'
    magenta = '0x472575'
    red = '0xfb007a'
    white = '0xf1f1f1'
    yellow = '0xf3e430'

  [colors.normal]
    black = '0x626483'
    blue = '0x19bffe'
    cyan = '0x43fbff'
    green = '0xa6e22e'
    magenta = '0x6800d2'
    red = '0xfb007a'
    white = '0xd9d9d9'
    yellow = '0xf3e430'

  [colors.primary]
    background = '0x070219'
    foreground = '0x27fbfe'
