[colors]
  [colors.bright]
    black = '0x384148'
    blue = '0x8cc1ff'
    cyan = '0x90daff'
    green = '0x94f7c5'
    magenta = '0xe2a6ff'
    red = '0xfc7b81'
    white = '0xfafdff'
    yellow = '0xffeba6'

  [colors.normal]
    black = '0x1c252c'
    blue = '0x70a5eb'
    cyan = '0x74bee9'
    green = '0x78dba9'
    magenta = '0xc68aee'
    red = '0xe05f65'
    white = '0xdee1e6'
    yellow = '0xf1cf8a'

  [colors.primary]
    background = '0x101419'
    foreground = '0xb6beca'
