[colors]
  [colors.bright]
    black = '0x7b8483'
    blue = '0x81533F'
    cyan = '0x97896F'
    green = '0x6D5648'
    magenta = '0x8B664E'
    red = '0x504D4B'
    white = '0xb1bdbc'
    yellow = '0x6C695F'

  [colors.normal]
    black = '0x12181f'
    blue = '0x81533F'
    cyan = '0x97896F'
    green = '0x6D5648'
    magenta = '0x8B664E'
    red = '0x504D4B'
    white = '0xb1bdbc'
    yellow = '0x6C695F'

  [colors.primary]
    background = '0x12181f'
    foreground = '0xb1bdbc'
