[colors]
  [colors.bright]
    black = '0x4c5458'
    blue = '0xa393a6'
    cyan = '0xb54c51'
    green = '0x4f89aa'
    magenta = '0xaa6b76'
    red = '0x5990aa'
    white = '0xc3c6c7'
    yellow = '0x7193aa'

  [colors.normal]
    black = '0x111c21'
    blue = '0xa393a6'
    cyan = '0xb54c51'
    green = '0x4f89aa'
    magenta = '0xaa6b76'
    red = '0x5990aa'
    white = '0xc3c6c7'
    yellow = '0x7193aa'

  [colors.primary]
    background = '0x111c21'
    foreground = '0xc3c6c7'
