[colors]
  [colors.bright]
    black = '0x505358'
    blue = '0x7284aa'
    cyan = '0x7081aa'
    green = '0x6e82aa'
    magenta = '0x6e80aa'
    red = '0x7083aa'
    white = '0xc4c5c7'
    yellow = '0x7586aa'

  [colors.normal]
    black = '0x161a21'
    blue = '0x7284aa'
    cyan = '0x7081aa'
    green = '0x6e82aa'
    magenta = '0x6e80aa'
    red = '0x7083aa'
    white = '0xc4c5c7'
    yellow = '0x7586aa'

  [colors.primary]
    background = '0x161a21'
    foreground = '0xc4c5c7'
