[colors]
  [colors.bright]
    black = '0x343a40'
    blue = '0x495057'
    cyan = '0x6c757d'
    green = '0xadb5bd'
    magenta = '0xced4da'
    red = '0xdee2e6'
    white = '0xf8f9fa'
    yellow = '0xe9ecef'

  [colors.normal]
    black = '0x2C3136'
    blue = '0x495057'
    cyan = '0x6c757d'
    green = '0xadb5bd'
    magenta = '0xced4da'
    red = '0xdee2e6'
    white = '0xf8f9fa'
    yellow = '0xe9ecef'

  [colors.primary]
    background = '0x212529'
    foreground = '0xf8f9fa'
