#!/bin/sh
## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

#### Pre Launch      #################################################################################
(((__distro_path_root)))/bin/X11/WM/pre_launch_wm

# Start compositor
picom-session start &

#### START SETTINGS  #################################################################################
## Themeing --------------------------------------------------#
. "${HOME}/.config/bspwm/theme-bspwm.conf"

## Configurations --------------------------------------------#
#workspace
name=1
for monitor in $(bspc query -M); do
	#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
	#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V'
	#bspc monitor ${monitor} -n "$name" -d '' '' '' '' ''
	bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
	name=$((name + 1))
done

## Apply bspwm configurations --------------------------------#
bspc config border_width       		"$BSPWM_BORDER"
bspc config top_padding       	  	50
bspc config right_padding     	  	9
bspc config left_padding      	  	9
bspc config bottom_padding     	 	9
bspc config window_gap          	"$BSPWM_GAP"
bspc config split_ratio 			"$BSPWM_SRATIO"
bspc config top_monocle_padding  	0
bspc config right_monocle_padding 	0
bspc config left_monocle_padding 	0
bspc config bottom_monocle_padding 	0

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$BSPWM_PFC"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$BSPWM_PBC"
bspc config borderless_monocle ${BSP_BORDERLESS_MONOCLE}
bspc config gapless_monocle ${BSP_GAPLESS_MONOCLE}
bspc config paddingless_monocle ${BSP_PADDINGLESS_MONOCLE}
bspc config single_monocle ${BSP_SINGLE_MONOCLE}
bspc config focus_follows_pointer ${BSP_FOCUS_FOLLOWS_POINTER}
## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

# Alias for: Super key (win) = Control_Left+Tab
xcape -e "Super_L=Control_L|Tab" 									
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout us

# To support other applications that don't work on WMs #
# May have to install wmname
#wmname LG3D

#### Window rules ###############################################################################

# remove all rules first
bspc rule -r *:*

# 1 > terminal
terminal="my-terminal-emulator kitty Alacritty Xfce4-terminal"
for i in ${terminal}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done
bspc rule -a "dev.warp.Warp" state=floating follow=on focus=on

# 2 > web
web="my-www-browser firefox Google-chrome Brave-browser chromium Thunderbird TelegramDesktop Hexchat Discord"
for i in ${web}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done
web2="guiscrcpy kdeconnect.app MEGAsync Element Free Windscribe2 Protonvpn"
for i in ${web2}; do
   bspc rule -a $i desktop='^2' state=floating follow=on focus=on; done
   
# 3 > code
code="Geany code-oss Gucharmap Atril Evince 
libreoffice-writer libreoffice-calc libreoffice-impress 
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice"
for i in ${code}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > media
media="Audacity Music MPlayer Lxmusic Inkscape Gimp obs Mplayer2 qBittorrent"
for i in ${media}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done

# 5 > settings
bspc rule -a 'VirtualBox Manager' desktop='^5' follow=on focus=on
bspc rule -a GParted desktop='^5' follow=on focus=on

settings="Lxappearance Lxtask Lxrandr Arandr
System-config-printer.py Pavucontrol Exo-helper-1
Xfce4-power-manager-settings"
for i in ${settings}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on; done

# special rules
floating="alacritty-float Pcmanfm Thunar Onboard Yad yad 'Firefox:Places'
Viewnior feh Nm-connection-editor"
for i in ${floating}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a wine desktop='^5' state=floating follow=on
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on

#### Autostart ###############################################################################
# Lauch keybindings daemon
sxhkd &

if command -v urxvtc >/dev/null 2>&1;then
	#urxvtc
	(sleep 0.50; urxvtc) &
fi

# Start bspwm scripts
bspfloat 5 &

(((__distro_path_root)))/bin/X11/WM/post_launch_wm
(((__distro_path_root)))/bin/X11/WM/extra_post_launch_wm
