#!/bin/sh
. "$__distro_path_lib"
. "${__distro_path_root}/lib/common/WM"
. "${Distro_config_file}"

DB_FILE="${script_config_path}/bookmarks"
ROFI_BASE_CMD="rofi -no-config -no-lazy-grab -dmenu -r -i -l 20 -theme $HOME/.config/rofi/$ROFI_STYLE/runner.rasi"

if [ ! -f "$DB_FILE" ];then
	touch "$DB_FILE"
fi

mark="$(cat "$DB_FILE" | $ROFI_BASE_CMD -p 'Bookmarks:')"

if [ -z "$mark" ];then
	exit 0
fi

if grep -Fxq "$mark" "$DB_FILE"; then
	my-www-browser "$mark"
else
	action="$(printf "Open & Save\nJust Open" | $ROFI_BASE_CMD -p "New Link:")"
	case "$action" in
		"Open & Save")
			printf "%s\n" "$mark" >> "$DB_FILE"
			my-www-browser "$mark"
			;;
		"Just Open") my-www-browser "$mark" ;;
		*) exit 0 ;;
	esac
fi
