#!/bin/sh
# if this line exist script will be part of hub script.
. "$__distro_path_lib"
. "${__distro_path_root}/lib/common/WM"
. "${Distro_config_file}"

chosen=$(cut -d ';' -f1 "${__distro_path_root}"/lib/emoji/* | rofi -dmenu -i -l 30 -theme "$HOME/.config/rofi/emoji.rasi" | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ];then
	xdotool type "$chosen"
else
	printf "%s" "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
