#!/bin/sh
# Dmenu prompt to easily search for a man page to open
. "$__distro_path_lib"
. "${__distro_path_root}/lib/common/WM"
. "${Distro_config_file}"

man "$(apropos --long "$1" | rofi -no-config -no-lazy-grab -dmenu -r -i -l 20 -theme "$HOME/.config/rofi/$ROFI_STYLE"/runner.rasi -l 10 | cut -d " " -f1)"
