#!/bin/sh

. "$__distro_path_lib"
. "${__distro_path_root}/lib/common/WM"
. "${Distro_config_file}"

which_wm_to_use="$(cat "${WM_name_file_path}")"
shortcut_rofi_file_path="${script_config_path}/shortcut_rofi_${which_wm_to_use}"
RASI="$HOME/.config/rofi/$ROFI_STYLE/launcher.rasi"

column -t -s " | " "$shortcut_rofi_file_path" | rofi -show run -dmenu -i -p "" -no-show-icons -l 10 -theme "${RASI}"
