#!/bin/sh
# need superuser : called by my-installer

app_name="1password"
extra_apps_="1password-cli"

download_key "gpg" "https://downloads.1password.com/linux/keys/1password.asc" "/usr/share/keyrings/1password-archive-keyring.gpg"

# Add apt repository
add_repo "1password" "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main"

# Add the debsig-verify policy
my-superuser mkdir -p /etc/debsig/policies/AC2D62742012EA22/
download_key "download" "https://downloads.1password.com/linux/debian/debsig/1password.pol" "/etc/debsig/policies/AC2D62742012EA22/1password.pol"
my-superuser mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
download_key "gpg" "https://downloads.1password.com/linux/keys/1password.asc" "/usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg"

Package_update_

clear

say 'Installing package...' 1

Package_installer_ "${app_name} ${extra_apps_}" || continue
