;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; main colors
background = #100f0d
foreground = #dfd9cd
red = #E99551
green = #C8A763
yellow = #24768B

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
