#!/bin/sh -e
app_name="code"
set_as_default_package=true
prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false

say "Installing ${app_name}..." 1
Package_installer_ visual-studio-code-bin

[ "$set_as_default_package" = true ] && my-alternatives --set "my-ide" "${app_name}"
