#!/bin/sh -e
app_name="code"
set_as_default_package=true
prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false

say "Installing ${app_name}..." 1
Package_installer_ visual-studio-code-bin

if [ "$set_as_default_package" = true ];then
	my-alternatives --set "my-ide" "${app_name}" || continue
fi
