#!/bin/sh -e
tweek_as_dependency "Enable_multilib" || continue
devel_pakages='tar tree multitail tldr trash-cli unzip cmake make jq'

say 'Installing devel-pakages ...' 1
Package_installer_ "$devel_pakages"
