#!/bin/sh
alias my-superuser=sudo
command_exist(){
	if command -v "${1:-}" >/dev/null 2>&1;then
		return
	else
		return 1
	fi
}

package_exist(){
	if pacman -Ss "${1:-}" >/dev/null 2>&1;then
		return
	else
		return 1
	fi
}

clone_repo(){
	repo="${1:-}"
	path="${2:-}"
	if [ ! -d "$path" ];then
		if ! git clone "$repo" "$path";then
			rm -rdf "$path"
			return 1
		fi
	fi
}

Package_installer_(){
	yay --noconfirm -Sy --sudoloop $@
}

full_upgrade_(){
	say 'Full upgrade your system...' 1
	if ! yay -Syu --noconfirm;then
    	if ! yay --noconfirm -Sy archlinux-keyring;then
    		pacman-key --init
			pacman-key --populate archlinux
			pacman-key --refresh-keys
			yay -Syu --noconfirm
		else
			yay -Syu --noconfirm
    	fi
    fi
}

kill_package_manager(){
	if [ -f "/var/lib/pacman/db.lck" ];then
		rm /var/lib/pacman/db.lck
	fi
	ps aux | grep "pacman" | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1 || :
}

pacman_installer_(){
	my-superuser pacman --noconfirm -Sy $@
}


say() {
    printf '\033[36m:: %s \033[0m\n' "$@"
}

Package_remove_(){
	packges="$@"
	for packge in $packges;do
		if ${package_manger} -Q | grep -q "packge "; then
			packges="$packges $packge"
		fi
	done
	if [ -n "$packges" ];then
		${package_manger} -Rns --noconfirm $packges
	fi
}	

getURL(){
	mode="${1-}"
	url="${2-}"
	path="${3-}"
	file_name="${url##*/}"
	wget --show-progress -O "${file_name}" "${url}" || exit 1
}
__distro_path_wallpaper="$HOME/Pictures/Wallpapers"

#################################################################
set -e

useFahrenheit=false
VSCODE=""
SPOTIFY=""
DISCORD=""
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
__distro_path_wallpaper="$HOME/Pictures/Wallpapers"
sessionGif="logo.svg"
caelestia_conf_path="$HOME/.local/caelestia"
#################################################################

confirm_overwrite() {
    path="$1"
    if [ -e "$path" ] || [ -L "$path" ]; then
        say "Removing $path..."
        /usr/bin/rm -rf "$path"
    fi
}

download_and_Config_caelestia(){
	clone_repo https://github.com/caelestia-dots/caelestia.git "${caelestia_conf_path}"
		
	cd "${caelestia_conf_path}"
	say "Installing packages..."
	package_2_install_pacman=""
	package_2_install_aur=""
		
	for package in caelestia-cli caelestia-shell hyprland xdg-desktop-portal-hyprland xdg-desktop-portal-gtk hyprpicker wl-clipboard cliphist inotify-tools app2unit wireplumber trash-cli foot fish eza fastfetch starship btop jq adw-gtk-theme papirus-icon-theme qt5ct-kde qt6ct-kde ttf-jetbrains-mono-nerd thunar todoist-appimage uwsm gnome-keyring polkit-gnome direnv zoxide;do
		if package_exist "${package}" ;then
			package_2_install_pacman="${package_2_install_pacman} ${package}"
		else
			package_2_install_aur="${package_2_install_aur} ${package}"
		fi
	done
	
	if [ -n "$package_2_install_pacman" ];then
		pacman_installer_ "${package_2_install_pacman}"
	fi
	
	if [ -n "$package_2_install_aur" ];then
		Package_installer_ "${package_2_install_aur}"
	fi
	
	for conf in hypr starship.toml foot fish fastfetch uwsm btop;do
    	ln -s "$(realpath "$conf")" "$CONFIG"
	done
	hypr="$HOME/.config/hypr"
	caelestia_Conf="$HOME/.config/caelestia"
	
	# Variables (colours + other vars)
	cp -L --no-preserve=mode --update=none "$hypr"/scheme/default.conf "$hypr"/scheme/current.conf
	mkdir -p "$caelestia_Conf"
	touch -a "$caelestia_Conf"/hypr-vars.conf
	touch -a "$caelestia_Conf"/hypr-user.conf
cat <<EOF> "$caelestia_Conf"/shell.json
{
    "appearance": {
        "anim": {
            "durations": {
                "scale": 1
            }
        },
        "font": {
            "family": {
                "clock": "Rubik",
                "material": "Material Symbols Rounded",
                "mono": "CaskaydiaCove NF",
                "sans": "Rubik"
            },
            "size": {
                "scale": 1
            }
        },
        "padding": {
            "scale": 1
        },
        "rounding": {
            "scale": 1
        },
        "spacing": {
            "scale": 1
        },
        "transparency": {
            "enabled": false,
            "base": 0.85,
            "layers": 0.4
        }
    },
    "general": {
        "apps": {
            "terminal": ["foot"],
            "audio": ["pavucontrol"],
            "playback": ["mpv"],
            "explorer": ["thunar"]
        },
        "battery": {
            "warnLevels": [
                {
                    "level": 20,
                    "title": "Low battery",
                    "message": "You might want to plug in a charger",
                    "icon": "battery_android_frame_2"
                },
                {
                    "level": 10,
                    "title": "Did you see the previous message?",
                    "message": "You should probably plug in a charger <b>now</b>",
                    "icon": "battery_android_frame_1"
                },
                {
                    "level": 5,
                    "title": "Critical battery level",
                    "message": "PLUG THE CHARGER RIGHT NOW!!",
                    "icon": "battery_android_alert",
                    "critical": true
                }
            ],
            "criticalLevel": 3
        },
        "idle": {
            "lockBeforeSleep": true,
            "inhibitWhenAudio": true,
            "timeouts": [
                {
                    "timeout": 180,
                    "idleAction": "lock"
                },
                {
                    "timeout": 300,
                    "idleAction": "dpms off",
                    "returnAction": "dpms on"
                },
                {
                    "timeout": 600,
                    "idleAction": ["systemctl", "suspend-then-hibernate"]
                }
            ]
        }
    },
    "background": {
        "desktopClock": {
            "enabled": false
        },
        "enabled": true,
        "visualiser": {
            "blur": false,
            "enabled": false,
            "autoHide": true,
            "rounding": 1,
            "spacing": 1
        }
    },
    "bar": {
        "clock": {
            "showIcon": true
        },
        "dragThreshold": 20,
        "entries": [
            {
                "id": "logo",
                "enabled": true
            },
            {
                "id": "workspaces",
                "enabled": true
            },
            {
                "id": "spacer",
                "enabled": true
            },
            {
                "id": "activeWindow",
                "enabled": true
            },
            {
                "id": "spacer",
                "enabled": true
            },
            {
                "id": "tray",
                "enabled": true
            },
            {
                "id": "clock",
                "enabled": true
            },
            {
                "id": "statusIcons",
                "enabled": true
            },
            {
                "id": "power",
                "enabled": true
            }
        ],
        "persistent": true,
        "popouts": {
            "activeWindow": true,
            "statusIcons": true,
            "tray": true
        },
        "scrollActions": {
            "brightness": true,
            "workspaces": true,
            "volume": true
        },
        "showOnHover": true,
        "status": {
            "showAudio": false,
            "showBattery": true,
            "showBluetooth": true,
            "showKbLayout": false,
            "showMicrophone": false,
            "showNetwork": true,
            "showLockStatus": true
        },
        "tray": {
            "background": false,
            "compact": false,
            "iconSubs": [],
            "recolour": false
        },
        "workspaces": {
            "activeIndicator": true,
            "activeLabel": "󰮯",
            "activeTrail": false,
            "label": "  ",
            "occupiedBg": false,
            "occupiedLabel": "󰮯",
            "perMonitorWorkspaces": true,
            "showWindows": true,
            "shown": 5,
            "specialWorkspaceIcons": [
                {
                    "name": "steam",
                    "icon": "sports_esports"
                }
            ]
        },
        "excludedScreens": [""],
        "activeWindow": {
            "inverted": false
        }
    },
    "border": {
        "rounding": 25,
        "thickness": 10
    },
    "dashboard": {
        "enabled": true,
        "dragThreshold": 50,
        "mediaUpdateInterval": 500,
        "showOnHover": true
    },
    "launcher": {
        "actionPrefix": ">",
        "actions": [
            {
                "name": "Calculator",
                "icon": "calculate",
                "description": "Do simple math equations (powered by Qalc)",
                "command": ["autocomplete", "calc"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Scheme",
                "icon": "palette",
                "description": "Change the current colour scheme",
                "command": ["autocomplete", "scheme"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Wallpaper",
                "icon": "image",
                "description": "Change the current wallpaper",
                "command": ["autocomplete", "wallpaper"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Variant",
                "icon": "colors",
                "description": "Change the current scheme variant",
                "command": ["autocomplete", "variant"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Transparency",
                "icon": "opacity",
                "description": "Change shell transparency",
                "command": ["autocomplete", "transparency"],
                "enabled": false,
                "dangerous": false
            },
            {
                "name": "Random",
                "icon": "casino",
                "description": "Switch to a random wallpaper",
                "command": ["caelestia", "wallpaper", "-r"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Light",
                "icon": "light_mode",
                "description": "Change the scheme to light mode",
                "command": ["setMode", "light"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Dark",
                "icon": "dark_mode",
                "description": "Change the scheme to dark mode",
                "command": ["setMode", "dark"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Shutdown",
                "icon": "power_settings_new",
                "description": "Shutdown the system",
                "command": ["systemctl", "poweroff"],
                "enabled": true,
                "dangerous": true
            },
            {
                "name": "Reboot",
                "icon": "cached",
                "description": "Reboot the system",
                "command": ["systemctl", "reboot"],
                "enabled": true,
                "dangerous": true
            },
            {
                "name": "Logout",
                "icon": "exit_to_app",
                "description": "Log out of the current session",
                "command": ["loginctl", "terminate-user", ""],
                "enabled": true,
                "dangerous": true
            },
            {
                "name": "Lock",
                "icon": "lock",
                "description": "Lock the current session",
                "command": ["loginctl", "lock-session"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Sleep",
                "icon": "bedtime",
                "description": "Suspend then hibernate",
                "command": ["systemctl", "suspend-then-hibernate"],
                "enabled": true,
                "dangerous": false
            },
            {
                "name": "Settings",
                "icon": "settings",
                "description": "Configure the shell",
                "command": ["caelestia", "shell", "controlCenter", "open"],
                "enabled": true,
                "dangerous": false
            }
        ],
        "dragThreshold": 50,
        "vimKeybinds": false,
        "enableDangerousActions": false,
        "maxShown": 7,
        "maxWallpapers": 9,
        "specialPrefix": "@",
        "useFuzzy": {
            "apps": false,
            "actions": false,
            "schemes": false,
            "variants": false,
            "wallpapers": false
        },
        "showOnHover": false,
        "hiddenApps": []
    },
    "lock": {
        "recolourLogo": false
    },
    "notifs": {
        "actionOnClick": false,
        "clearThreshold": 0.3,
        "defaultExpireTimeout": 5000,
        "expandThreshold": 20,
        "openExpanded": false,
        "expire": false
    },
    "osd": {
        "enabled": true,
        "enableBrightness": true,
        "enableMicrophone": false,
        "hideDelay": 2000
    },
    "paths": {
        "mediaGif": "root:/assets/bongocat.gif",
        "sessionGif": "root:/assets/${sessionGif}",
        "wallpaperDir": "${__distro_path_wallpaper}"
    },
    "services": {
        "audioIncrement": 0.1,
        "brightnessIncrement": 0.1,
        "maxVolume": 1.0,
        "defaultPlayer": "Spotify",
        "gpuType": "",
        "playerAliases": [{ "from": "com.github.th_ch.youtube_music", "to": "YT Music" }],
        "weatherLocation": "",
        "useFahrenheit": ${useFahrenheit},
        "useTwelveHourClock": false,
        "smartScheme": true,
        "visualiserBars": 45
    },
    "session": {
        "dragThreshold": 30,
        "enabled": true,
        "vimKeybinds": false,
        "commands": {
            "logout": ["loginctl", "terminate-user", ""],
            "shutdown": ["systemctl", "poweroff"],
            "hibernate": ["systemctl", "hibernate"],
            "reboot": ["systemctl", "reboot"]
        }
    },
    "sidebar": {
        "dragThreshold": 80,
        "enabled": true
    },
    "utilities": {
        "enabled": true,
        "maxToasts": 4,
        "toasts": {
            "audioInputChanged": true,
            "audioOutputChanged": true,
            "capsLockChanged": true,
            "chargingChanged": true,
            "configLoaded": true,
            "dndChanged": true,
            "gameModeChanged": true,
            "kbLayoutChanged": true,
            "numLockChanged": true,
            "vpnChanged": true,
            "nowPlaying": false
        },
        "vpn": {
            "enabled": false,
            "provider": [
                {
                    "name": "wireguard",
                    "interface": "your-connection-name",
                    "displayName": "Wireguard (Your VPN)"
                }
            ]
        }
    }
}
EOF
}

install_and_Config_zen(){
	Package_installer_ zen-browser-bin
	setsid zen-browser
	sleep 4
	killall -9 zen-bin >/dev/null 2>&1
	sleep 1
	find "$HOME/.zen" -type f -name 'userChrome.css' |
	while IFS= read -r userChrome; do
   		confirm_overwrite "$userChrome"
   		ln -sf "$(realpath "${caelestia_conf_path}/zen/userChrome.css")" "$userChrome"
	done
		
	HOSTS="$HOME/.mozilla/native-messaging-hosts"
	LIB="$HOME/.local/lib/caelestia"
	
	confirm_overwrite "$HOSTS/caelestiafox.json"
	mkdir -p "$HOSTS"
	sed "s|{{ \$lib }}|$LIB|g" "${caelestia_conf_path}"/zen/native_app/manifest.json > "$HOSTS/caelestiafox.json"
	
	confirm_overwrite "$LIB/caelestiafox"
	mkdir -p "$LIB"
	ln -s "$(realpath "${caelestia_conf_path}"/zen/native_app/app.fish)" "$LIB/caelestiafox"
}

install_and_Config_Spotify(){
	say "Installing spotify (spicetify)..."
    Package_installer_ spotify spicetify-cli spicetify-marketplace-bin

    if ! package_exist spicetify-cli;then
        my-superuser chmod a+wr /opt/spotify /opt/spotify/Apps -R
        spicetify backup apply
    fi

    confirm_overwrite "$CONFIG/spicetify"
    ln -s "$(realpath spicetify)" "$CONFIG/spicetify"
    spicetify config current_theme caelestia color_scheme caelestia custom_apps marketplace
    spicetify apply
}

install_and_Config_VSCodium(){
	say "Installing vscodium..."
	if ! package_exist codium;then
		Package_installer_ codium
	fi

    confirm_overwrite "$CONFIG/VSCodium/User/settings.json"
    confirm_overwrite "$CONFIG/VSCodium/User/keybindings.json"
    confirm_overwrite "$CONFIG/codium-flags.conf"

    mkdir -p "$CONFIG/VSCodium/User"
    ln -s "$(realpath vscode/settings.json)" "$CONFIG/VSCodium/User/settings.json"
    ln -s "$(realpath vscode/keybindings.json)" "$CONFIG/VSCodium/User/keybindings.json"
    ln -s "$(realpath vscode/flags.conf)" "$CONFIG/codium-flags.conf"
    codium --install-extension vscode/caelestia-vscode-integration/caelestia-vscode-integration-*.vsix
}

install_and_Config_Discord(){
    say "Installing discord..."
    Package_installer_ discord equicord-installer-bin
    my-superuser Equilotl -install -location /opt/discord
    my-superuser Equilotl -install-openasar -location /opt/discord
    Package_remove_ equicord-installer-bin
}

#################################################################

kill_package_manager

full_upgrade_
Package_installer_ git

download_and_Config_caelestia
install_and_Config_zen

if [ "$SPOTIFY" = true ]; then
    install_and_Config_Spotify
fi

if [ "$VSCODE" = true ]; then
    install_and_Config_VSCodium
fi

if [ "$DISCORD" = true ]; then
	install_and_Config_Discord
fi

caelestia shell -d >/dev/null

say "Done!"
say "Please install the CaelestiaFox extension from AMO if you have not already done so."
