#!/bin/sh

app_name="qt5ct"
extra_apps_="qt5-style-kvantum libqt5svg5 qml-module-qtquick-controls"

say 'Installing package...' 1

Package_installer_ ${app_name} || continue

say 'Installing extra packages...' 1
Package_installer_ ${extra_apps_} || continue

