#!/usr/bin/env bash
## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

#### Pre Launch      #################################################################################
pre_launch_wm

#### START SETTINGS  #################################################################################
## Environtment

## Java Applications
# wmname LG3D
# export _JAVA_AWT_WM_NONREPARENTING=1

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' ''
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		let name++
	done
}
workspaces

bspc config border_width        0
bspc config top_padding         50
bspc config right_padding       9
bspc config left_padding        9
bspc config bottom_padding      9
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

#bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Alias for: Super key (win) = Control_Left+Tab
xcape -e "Super_L=Control_L|Tab" 									
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout us


#### Window rules ###############################################################################

# remove all rules first
bspc rule -r *:*

# external_rules
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

# 1 > terminal
declare -a terminal=(my-terminal-emulator kitty Alacritty Xfce4-terminal Pcmanfm Thunar)
for i in ${terminal[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

# 2 > web
declare -a web=(firefox chromium Thunderbird TelegramDesktop Hexchat Discord)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3 > code
declare -a code=(Geany code-oss Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > media
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp obs Mplayer2 qBittorrent)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done

# 5 > settings
bspc rule -a 'VirtualBox Manager' desktop='^5' follow=on focus=on
bspc rule -a GParted desktop='^5' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a wine desktop='^5' state=floating follow=on
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on

#### Autostart ###############################################################################
# Lauch keybindings daemon
sxhkd &

if command -v urxvtc &> /dev/null; then
	#urxvtc
	(sleep 0.50; urxvtc) &
fi

# Start panel	
panel_manager --launch

## Enable power management
my_power_manager &

# Start bspwm scripts
bspfloat &

# update notifcation
update-notification -n &
