#!/bin/sh
#called by : my-installer
app_name="heroic"
if [ -f "${__distro_path_system_ready}/Distrobox_ready" ];then
	app_name="heroic-games-launcher-bin"
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
  	pacstall_install heroic-games-launcher-deb || continue
fi
