#!/bin/sh
#called by : my-installer
app_name="stella"
if [ -f "${__distro_path_system_ready}/Distrobox_ready" ];then
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	pacstall_install stellarium || continue
fi
