#!/bin/sh
#called by : my-installer
app_name="yabause"
if check_system_ready_file "Distrobox_ready";then
	app_name="yabause-qt5-git"
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	Package_installer_ "${app_name}" || continue
fi
