# profile file. Runs on login. Environmental variables are set here.

# set tty colours.

# Default programs:
export VISUAL=nano
export EDITOR=$VISUAL
export SUDO_EDITOR="${VISUAL}"
export TERMINAL="my-terminal-emulator"
export BROWSER="firefox"
export CLI_EDITER=nano

# Styling QT apps
export QT_QPA_PLATFORMTHEME=gtk2

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/bash_history/bash_history"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/lesshst"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
#export XDG_RUNTIME_DIR="/run/user/$UID"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DM.
#export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# Other program settings:
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
#export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
#export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
#export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
#export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
#export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
#export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
#export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
#export LESS=-R
#export LESS_TERMCAP_mb="$(printf '%b' '^[[1;31m')"
#export LESS_TERMCAP_md="$(printf '%b' '^[[1;36m')"
#export LESS_TERMCAP_me="$(printf '%b' '^[[0m')"
#export LESS_TERMCAP_so="$(printf '%b' '^[[01;44;33m')"
#export LESS_TERMCAP_se="$(printf '%b' '^[[0m')"
#export LESS_TERMCAP_us="$(printf '%b' '^[[1;32m')"
#export LESS_TERMCAP_ue="$(printf '%b' '^[[0m')"
#export AWT_TOOLKIT="MToolkit wmname LG3D"       #May have to install wmname
export QT_QPA_PLATFORMTHEME="gtk2"      # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"              # Mozilla smooth scrolling/touchpads.

# use PYTHONPYCACHEPREFIX to use a global cache, so python won't create
# __pycache__ directories in my projects
export PYTHONPYCACHEPREFIX="$HOME/.cache/cpython/"

if [ ! -d "$GNUPGHOME" ]; then
	[ -d "$HOME/.gnupg" ] && mv "$HOME/.gnupg" "$GNUPGHOME"
	mkdir -p $GNUPGHOME
	chmod 700 $GNUPGHOME
fi

# bash var
export My_shell_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/myshell"
export BASHDOTDIR="${My_shell_DIR}/bash"
export ZDOTDIR="${My_shell_DIR}/zsh"

# Set environment path
export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin:/usr/games:/usr/local/games
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Manage multiple versions of Python using pyenv
if [ -d "$HOME/.pyenv" ] ; then
    export PYENV_ROOT="$HOME/.pyenv"
    command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
