#!/bin/bash
if [ -z "$ZDOTDIR" ];then
  	export My_shell_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/myshell"
  	source "${My_shell_DIR}/distropath4SSH.sh"
fi
source "${My_shell_DIR}/distropath4SSH.sh"
source "$ZDOTDIR/zshrc"
