#!/bin/zsh
# --------------------------------- checks -----------------------------------
if [ -z "$ZDOTDIR" ];then
  export My_shell_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/myshell"
  export ZDOTDIR="${My_shell_DIR}/bash"
fi

# --------------------------------- Settings -----------------------------------
vim_mode_enabled=true

remote_plugins=(
zsh-users/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search
MichaelAquilina/zsh-you-should-use
MichaelAquilina/zsh-auto-notify
)

# ---------------------------------   Theme  -----------------------------------
ZSH_THEME="pure"

# ---------------------------------  source  -----------------------------------
source $ZDOTDIR/zshrc.sh
