#!/bin/zsh
# --------------------------------- checks ------------------------------------
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
if [ -z "$ZDOTDIR" ];then
  	export My_shell_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/myshell"
  	export ZDOTDIR="${My_shell_DIR}/zsh"
fi

# --------------------------------- Settings ----------------------------------
vim_mode_enabled=true

# --------------------------------- Plugins -----------------------------------
remote_plugins=(
zsh-users/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search
MichaelAquilina/zsh-you-should-use
MichaelAquilina/zsh-auto-notify
)

# ---------------------------------  Theme  -----------------------------------
ZSH_THEME="pure"
SSH_THEME="pure"

# -------------------------------  main file  ---------------------------------
source "$ZDOTDIR"/zshrc.sh
