#!/bin/zsh
# ---------------------------------  Theme  -----------------------------------
ZSH_THEME="headline"

# ---------------------------------  source  -----------------------------------
source $ZDOTDIR/zshrc.sh

# ------------------------------  online plugin  -------------------------------
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"
plug "MichaelAquilina/zsh-you-should-use"
plug "MichaelAquilina/zsh-auto-notify"
plug "jeffreytse/zsh-vi-mode"
