#!/bin/sh

app_name="typora"
Package_update_

download_key "gpg" "https://typora.io/linux/public-key.asc" "/usr/share/keyrings/typora.gpg"
add_repo "typora" "deb [arch=amd64 signed-by=/usr/share/keyrings/typora.gpg] https://typora.io/linux ./"

Package_update_

clear

say 'Installing package...' 1

Package_installer_ "${app_name}" || continue
copy_from_extra_skel ".config/typora" || continue

