#!/bin/sh
# need superuser : called by my-installer
if [ "${1:-}" = "skip_update" ];then
	skip_update=true
else
	skip_update=false
fi

if [ "$(id -u)" -eq 0 ];then
	_SUPERUSER=""
else
	_SUPERUSER="my-superuser"
fi

what_2_grep="non-free"
if [ -f "/etc/apt/sources.list" ];then
	mirror="http://deb.debian.org/debian/"
	mirror_security="http://security.debian.org/debian-security"
	apt_sources_file_path="/etc/apt/sources.list"
	line_2_sed=$(grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" "${apt_sources_file_path}" | grep -vw " $what_2_grep" || :)
elif [ -f "/etc/apt/sources.list.d/debian.sources" ];then
	apt_sources_file_path="/etc/apt/sources.list.d/debian.sources"
	line_2_sed=$(grep "Components: " "${apt_sources_file_path}" | grep -vw " $what_2_grep" || :)
fi

if [ -z "$line_2_sed" ];then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	say "enabling non-free repo."
	printf '%s\n' "$line_2_sed" | while IFS= read -r l; do
		${_SUPERUSER} sed -i "s\\^$l$\\$l ${what_2_grep}\\" "$apt_sources_file_path"
	done
	if [ "$skip_update" = "true" ];then
		Package_update_
	fi
fi
