#!/bin/sh
dist=$(lsb_release -cs)
if [ "n/a" = "$dist" ];then
    dist=testing
fi

what_2_grep="${dist}-backports"
if [ -f "/etc/apt/sources.list" ];then
	mirror="http://deb.debian.org/debian/"
	mirror_security="http://security.debian.org/debian-security"
	apt_sources_file_path="/etc/apt/sources.list"
	deb_lines_nonfree=$(grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" "${apt_sources_file_path}" | grep -v "$what_2_grep" )
elif [ -f "/etc/apt/sources.list.d/debian.sources" ];then
	apt_sources_file_path="/etc/apt/sources.list.d/debian.sources"
	deb_lines_nonfree=$(grep "Components: " "${apt_sources_file_path}" | grep -v "$what_2_grep" )
fi

if [ -z "$deb_lines_backports" ];then # enabled
	exit 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	exit 1
fi

for l in $deb_lines_backports; do
	my-superuser sed -i "s\\^$l$\\$l ${what_2_grep}\\" "$apt_sources_file_path"
done
my-superuser apt-get update
my-superuser ln -s /usr/share/my_stuff/Distro_Specific/tweeks_center/Extra/backports_install /usr/share/my_stuff/system_files/bin
my-superuser ln -s /usr/share/my_stuff/Distro_Specific/tweeks_center/Extra/backports_install_auto_completion /usr/share/my_stuff/system_files/auto_completion/backports_install
