#!/bin/sh
mirror="http://deb.debian.org/debian/"
mirror_security="http://security.debian.org/debian-security"
if [ -f "/etc/apt/sources.list" ];then
	apt_sources_file_path="/etc/apt/sources.list"
elif [ -f /etc/apt/sources.list ];then
	apt_sources_file_path="/etc/apt/sources.list"
fi

deb_lines_nonfree=$(grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" "${apt_sources_file_path}" | grep -vw " non-free")

if [ -z "$deb_lines_nonfree" ];then # enabled
	exit 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	exit 1
fi

for l in $deb_lines_nonfree; do
	my-superuser sed -i "s\\^$l$\\$l non-free\\" "${apt_sources_file_path}"
done
my-superuser apt-get update
