#!/bin/sh
mirror="http://deb.debian.org/debian/"
mirror_security="http://security.debian.org/debian-security"
deb_lines_nonfree_firmware=$(egrep -E "^(deb|deb-src) (${mirror}|${mirror_security})" /etc/apt/sources.list | grep -v non-free-firmware)

if [ -z "$deb_lines_nonfree_firmware" ];then # enabled
	exit 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	exit 1
fi

for l in $deb_lines_nonfree_firmware; do
	my-superuser sed -i "s\\^$l$\\$l non-free-firmware\\" /etc/apt/sources.list
done
my-superuser apt-get update
