#!/bin/sh
what_2_grep="non-free-firmware"
if [ -f "/etc/apt/sources.list" ];then
	mirror="http://deb.debian.org/debian/"
	mirror_security="http://security.debian.org/debian-security"
	apt_sources_file_path="/etc/apt/sources.list"
	line_2_sed=$(grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" "${apt_sources_file_path}" | grep -v "$what_2_grep" )
elif [ -f "/etc/apt/sources.list.d/debian.sources" ];then
	apt_sources_file_path="/etc/apt/sources.list.d/debian.sources"
	line_2_sed=$(grep "Components: " "${apt_sources_file_path}" | grep -v "$what_2_grep" )
fi

if [ -z "$line_2_sed" ];then # enabled
	return 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	return 1
fi

printf '%s\n' "$line_2_sed" | while IFS= read -r l; do
	my-superuser sed -i "s\\^$l$\\$l ${what_2_grep}\\" "$apt_sources_file_path"
done

Package_update_
