# Modules ---------------------------------------------------#

[module/backlight]
type = internal/backlight

card = intel_backlight

use-actual-brightness = true

enable-scroll = true

format = <label>
format-prefix = "DISP "
format-prefix-foreground = ${color.primary}
label = %percentage%

ramp-0 = 🌕
ramp-1 = 🌔
ramp-2 = 🌓
ramp-3 = 🌒
ramp-4 = 🌑

[module/title]
type = internal/xwindow

format = <label>
;format-background = ${color.shade2}
format-foreground = ${color.primary}
format-padding = 2

label = %title%
label-maxlen = 30

label-empty = AtmoZki
label-empty-foreground = #707880

[module/battery]
type = internal/battery

full-at = 99
low-at = 25

battery = BAT0
adapter = AC0

#format-full-prefix = " "
format-charging-prefix = "BAT "
format-discharging-prefix = "BAT "
format-charging-prefix-foreground = ${color.primary}
format-discharging-prefix-foreground = ${color.disabled}

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = ITS OVER 9000
label-low = I NEED JUICE

label-full-foreground = ${color.secondary}
label-low-foreground = ${color.alert-alt}

format-full = <label-full>
format-charging = <label-charging>
format-discharging = <label-discharging>
format-low = <label-low>


[module/volume]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${color.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${color.disabled}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:nm-connection-editor:}%{F#F0C674}WIFI%{F-} %essid%
;%{F#F0C674}%ifname%%{F-} %essid% %local_ip%
label-disconnected = No NET :/

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %a, %I:%M %p
date-alt = %a, %d-%b-%Y %I:%M %p

label = %date%
label-foreground = ${color.primary}

[module/date2]
type = internal/date
interval = 1

date =%a, %I:%M %p 
date-alt = %a, %d-%b-%Y %I:%M %p
module-padding = 30
label-active-padding = 30s

label = %date%
label-foreground = ${color.primary}
label-mounted-margin = 10
format-module-padding = 10
format-module-margin = 10
format-module-spacing = 10

[module/desktopNameWorkspace]
type = internal/bspwm
pin-workspaces = true
label-active = %name%
label-active-background = ${color.background-alt}
label-active-underline= ${color.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${color.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${color.disabled}
label-empty-padding = 1

; ws-icon-0 = term;♚
; ws-icon-1 = office;♛
; ws-icon-2 = graphics;♜
; ws-icon-3 = mail;♝
; ws-icon-4 = web;♞
; ws-icon-default = ♟

; vim:ft=dosini
