#!/bin/sh
## Openbox autostart
## ====================
## When you login to Openbox this autostart script will be executed to set-up your environment 
## and launch any applications you want to run at startup.
## This script is executed by default shell (sh), so 'bashisms' are not supported.
##
## Note: some programs, such as 'nm-applet' are run via XDG autostart.
## To see a list of any XDG autostarted programs run:
## 	/usr/lib/x86_64-linux-gnu/openbox-xdg-autostart --list
## 	/usr/lib/i386-linux-gnu/openbox-xdg-autostart --list
##
## More information about this can be found at: http://openbox.org/wiki/Help:Autostart

#### Pre Launch      #################################################################################
(((__distro_path_root)))/bin/X11/WM/pre_launch_wm

# Start compositor
picom-session start &

#### START SETTINGS  #################################################################################
# Set keyboard settings to 250ms delay and 25cps (characters per second)
xset r rate 250 25
# Alias for: Super key (win) = Control_Left+Tab
if command -v xcape >/dev/null 2>&1;then
	xcape -e "Super_L=Control_L|Tab" 									
	xcape -e 'Super_L=Alt_L|F1' &
	xcape -e 'Super_R=Alt_L|F1' &
fi

# Load xmodmap keys mapping
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap &							

# Touchpad settings
if [ -f "(((__distro_path_system_ready)))/this_is_laptop" ];then
	# Configure touchpad
	synclient VertEdgeScroll=1 HorizEdgeScroll=1 TapButton1=1 2>/dev/null	
	# Disable touchpad while typing
	syndaemon -i .5 -K -t -R -d & 											
fi

# Lauch keybindings daemon
keybinds-session start openbox

#### START APPLICATIONS ###############################################################################
(((__distro_path_root)))/bin/X11/WM/post_launch_wm
(((__distro_path_root)))/bin/X11/WM/extra_post_launch_wm
