#!/bin/sh -e
app_name="fastfetch"
say "Installing ${app_name}..." 1

getURL 'download2' "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb" "/tmp/fastfetch.deb"
Package_installer_ /tmp/fastfetch.deb
rm /tmp/fastfetch.deb

say "Copying Fastfetch config files..."
if [ -d "${HOME}/.config/fastfetch" ] && [ ! -d "${HOME}/.config/fastfetch-bak" ]; then
	cp -r "${HOME}/.config/fastfetch" "${HOME}/.config/fastfetch-bak"
fi
mkdir -p "${HOME}/.config/fastfetch/"
getURL 'download2' "https://raw.githubusercontent.com/ChrisTitusTech/mybash/main/config.jsonc" "${HOME}/.config/fastfetch/config.jsonc"
