ln -sf /usr/share/my_stuff/lib/mutt-wizard/bin/mw /usr/share/my_stuff/system_files/bin
ln -sf /usr/share/my_stuff/lib/mutt-wizard/bin/mailsync /usr/share/my_stuff/system_files/bin

mkdir -p /usr/local/share/man/man1
ln -sf /usr/share/my_stuff/lib/mutt-wizard/mailsync.1 /usr/local/share/man/man1
ln -sf /usr/share/my_stuff/lib/mutt-wizard/mw.1 /usr/local/share/man/man1

mkdir -p /usr/local/share/zsh/site-functions/
chmod 755 /usr/local/share/zsh/site-functions/
cp -f completion/_mutt-wizard.zsh /usr/local/share/zsh/site-functions/_mutt-wizard.zsh
chmod 644 /usr/local/share/zsh/site-functions/_mutt-wizard.zsh
