#!/bin/bash
set -eu

. "/usr/share/my_stuff/lib/common/API"

# It seems that in conky the execi command will start before curl has completely
# written the file. For some reason adding a sleep before calling curl fixes it.
#####################################################################################
appid=$(cat "${API_path}/${weather}" || :)
api_prefix="api.openweathermap.org/data/2.5/"
place="1716924"
units="metric"
lang=""

cache_folder="$HOME/.cache/conky-vision"
image_folder="$HOME/.config/conky/vision/"

#####################################################################################
appid="APPID=$appid"
units="&units=$units"

if [[ -z "$appid" ]] &>/dev/null;then
    echo "No API key"
    echo "Weather information unavailable"
    echo "Get API KEY by registering for one at http://openweathermap.org/api"
    echo "And save it at ${API_path}/."
    exit 1
fi

if [[ -z $place ]] &>/dev/null;then
	# Geolocate IP:
	latlong=$(get_scripts --latlong)
	# Parse the latitude and longitude
	lat=${latlong%,*}
	long=${latlong#*,}
	id="lat=$lat&lon=$long"
else
	# check if numeric id, or placename is being used
	[[ ${place##*[!0-9]*} ]] &>/dev/null && id="id=$place" || id="q=$place"
fi

if [[ -n "${lang}" ]];then
	lang="${1%%_*}" 
	lang="&lang=$lang"
fi

parse_weather(){
	res=""
	get_time () {
    	local idx="$1"
	
    	time=$(echo "$forecast_info" | jq ".list[$idx].dt_txt")
    	time="${time##* }"
    	time="${time%%\"}"
	
    	echo "$time"
	}
	
	find_position () {
    	local day="$1"
    	local pos=0
    	local idx=0
    	local time=""
	
    	[[ $day == 0 ]] && echo "$idx" && return
	
    	while true; do
        	time=$(get_time "$idx")
	
        	[[ $time == "00:00:00" ]] && ((pos++))
	
        	[[ $time == "null" ]] && break
        	[[ $pos == "$day" ]] && break
	
        	((idx++))
    	done
	
    	echo "$idx"
	}
	
	get_min_property () {
    	local res=0
	
    	local prop="$1"
    	local day="$2"
	
    	local idx
    	idx=$(find_position "$day")
	
    	local time=0
	
    	local i=0
	
    	local outarray=()
	
    	while true; do
        	[[ $time == "null" ]] && break
	
        	outarray[$i]="$(echo "$forecast_info" | jq ".list[$idx]$prop")"
	
        	(( i++ ))
        	(( idx++ ))
	
        	time=$(get_time "$idx")
	
        	# The records for every 3 hours are dumped in an array with no
        	# indication to which day they belong.
        	# The first record of each day (except today) is calculated at time
        	# '00:00:00', so we use that to know when a new day starts.
        	[[ $time == "00:00:00" ]] && break
    	done
	
    	IFS=$'\n'
    	res=($(sort -n<<<"${outarray[*]}" | head -n1))
    	unset IFS
	
    	[[ $res == "null" ]] && echo $res && return
	
    	LC_NUMERIC=C printf %.0f $res
	}
	
	get_max_property () {
    	local res=0
	
    	local prop="$1"
    	local day="$2"
	
    	local idx
    	idx=$(find_position "$day")
	
    	local time=0
	
    	local i=0
	
    	local outarray=()
	
    	while true; do
        	[[ $time == "null" ]] && break
	
        	outarray[$i]="$(echo "$forecast_info" | jq ".list[$idx]$prop")"
	
        	(( i++ ))
        	(( idx++ ))
	
        	time=$(get_time "$idx")
	
        	# The records for every 3 hours are dumped in an array with no
        	# indication to which day they belong.
        	# The first record of each day (except today) is calculated at time
        	# '00:00:00', so we use that to know when a new day starts.
        	[[ $time == "00:00:00" ]] && break
    	done
    	IFS=$'\n'
    	res=($(sort -nr <<<"${outarray[*]}" | head -n1))
	
    	unset IFS
	
    	[[ $res == "null" ]] && echo $res && return
	
    	LC_NUMERIC=C printf %.0f $res
	}
	
	# Certain values cannot be averaged (e.g., the weather description).
	# In that case we just use the value from the first record for that day.
	get_first_property () {
	
    	local res=0
	
    	local prop="$1"
    	local day="$2"
	
    	local idx
    	idx=$(find_position "$day")
	
    	res=$(echo "$forecast_info" | jq ".list[$idx]$prop")
	
    	[[ $res == "null" ]] && echo $res && return
	
    	LC_NUMERIC=C printf %.0f $res
	}
	current_weather="$(echo "$weather_info" | jq .main.temp | awk '{print int($1+0.5)}')"
	echo "${current_weather}°" > ${parse_weather_file}
	echo "$(get_max_property '.main.temp' '1')°" >> ${parse_weather_file}
	echo "$(get_max_property '.main.temp' '2')°" >> ${parse_weather_file}
	echo "$(get_max_property '.main.temp' '3')°" >> ${parse_weather_file}
	echo "$(get_max_property '.main.temp' '4')°" >> ${parse_weather_file}
	
	echo "$(get_min_property '.main.temp' '1')°" >> ${parse_weather_file}
	echo "$(get_min_property '.main.temp' '2')°" >> ${parse_weather_file}
	echo "$(get_min_property '.main.temp' '3')°" >> ${parse_weather_file}
	echo "$(get_min_property '.main.temp' '4')°" >> ${parse_weather_file}
	current_file="$(echo "$weather_info" | jq .weather[0].id)"
	forecast1_file="$(get_first_property '.weather[0].id' '1')"
	forecast2_file="$(get_first_property '.weather[0].id' '2')"
	forecast3_file="$(get_first_property '.weather[0].id' '3')"
	forecast4_file="$(get_first_property '.weather[0].id' '4')"
	cp -f $HOME/.config/conky/vision/#fff__32/$current_file.png ${cache_folder}/current.png
	cp -f $HOME/.config/conky/vision/#fff__32/$forecast1_file.png ${cache_folder}/forecast-1.png
	cp -f $HOME/.config/conky/vision/#fff__32/$forecast2_file.png ${cache_folder}/forecast-2.png
	cp -f $HOME/.config/conky/vision/#fff__32/$forecast3_file.png ${cache_folder}/forecast-3.png
	cp -f $HOME/.config/conky/vision/#fff__32/$forecast4_file.png ${cache_folder}/forecast-4.png
}
parse_weather_file="${cache_folder}/parse_weather_file"

forecast_info=$(curl -s "${api_prefix}forecast?${appid}${id}${units}${lang}")
weather_info=$(curl -s "${api_prefix}weather?${appid}${id}${units}${lang}")

mkdir -p "${image_folder}"
mkdir -p "${cache_folder}"

parse_weather
