#!/bin/sh
# need superuser : called by my-installer
app_name="scrcpy"
say "Installing ${app_name}..." 1
Package_installer_ "${app_name}" || failed_to_run "failed to install ${app_name} ."

my-superuser ln -sf "${__distro_path_root}/bin/not_add_2_path/ScrcpyGUI" "${__distro_path_root}/system_files/bin"
generate_applicationsdotdesktop_link "${app_name}" "ScrcpyGUI" "Android"
