#!/bin/sh -e
app_name="codium"

say "Add Repo..." 1
my-superuser rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
printf "%b\n" "[gitlab.com_paulcarroty_vscodium_repo]\nname=gitlab.com_paulcarroty_vscodium_repo\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | my-superuser tee -a /etc/zypp/repos.d/vscodium.repo

say "Update Repo..." 1
Package_update_

say "Installing ${app_name}..." 1
Package_installer_ ${app_name}
