#!/bin/sh

TLP_ENABLE__ID_DESCRIPTION="Enable/disable TLP"

TLP_WARN_LEVEL__ID_DESCRIPTION="Control how warnings about invalid settings are issued:\n 0=disabled,\n 1=background tasks (boot, resume, change of power source) report to syslog,\n 2=shell commands report to the terminal (stderr),\n 3=combination of 1 and 2"

TLP_DEFAULT_MODE__ID_DESCRIPTION="Operation mode when no power supply can be detected: AC, BAT.\n Concerns some desktop and embedded hardware only"

TLP_PERSISTENT_DEFAULT__ID_DESCRIPTION="Operation mode select:\n 0=depend on power source\n 1=always use TLP_DEFAULT_MODE\n Hint: use in conjunction with TLP_DEFAULT_MODE=BAT for BAT settings on AC"

TLP_PS_IGNORE__ID_DESCRIPTION="Power supply classes to ignore when determining operation mode: AC, USB, BAT.\n Separate multiple classes with spaces.\n Note: try on laptops where operation mode AC/BAT is incorrectly detected"

SOUND_POWER_SAVE__GROUP_DESCRIPTION="Enable audio power saving for Intel HDA, AC97 devices (timeout in secs).\n A value of 0 disables, >= 1 enables power saving.\n Note: 1 is recommended for Linux desktop environments with PulseAudio,\n systems without PulseAudio may require 10"

SOUND_POWER_SAVE_CONTROLLER__ID_DESCRIPTION="Disable controller too (HDA only): Y/N.\n Note: effective only when SOUND_POWER_SAVE_ON_AC/BAT is activated"

DISK_IDLE_SECS__GROUP_DESCRIPTION="Seconds laptop mode has to wait after the disk goes idle before doing a sync.\n Non-zero value enables, zero disables laptop mode"

MAX_LOST_WORK_SECS__GROUP_DESCRIPTION="Dirty page values (timeouts in secs)"

DISK_DEVICES__ID_DESCRIPTION="Define disk devices on which the following DISK/AHCI_RUNTIME parameters act.\n Separate multiple devices with spaces.\n Devices can be specified by disk ID also (lookup with: tlp diskid)"

DISK_APM_LEVEL__GROUP_DESCRIPTION="Hard disk advanced power management level: 1..254, 255 (max saving, min, off)\n Levels 1..127 may spin down the disk; 255 allowable on most drives.\n Separate values for multiple disks with spaces. Use the special value 'keep'\n to keep the hardware default for the particular disk"

DISK_APM_CLASS_DENYLIST__ID_DESCRIPTION="Exclude disk classes from advanced power management (APM):\n - sata, ata, usb, ieee1394.\n Separate multiple classes with spaces.\n CAUTION: USB and IEEE1394 disks may fail to mount or data may get corrupted with APM enabled.\n Be careful and make sure you have backups of all affected media before removing 'usb' or 'ieee1394' from the denylist(!)"

DISK_SPINDOWN_TIMEOUT__GROUP_DESCRIPTION="Hard disk spin down timeout:\n 0:\t\t\tspin down disabled\n 1..240:\t\ttimeouts from 5s to 20min (in units of 5s)\n 241..251:\ttimeouts from 30min to 5.5 hours (in units of 30min)\n (see 'man hdparm' for details)"

DISK_IOSCHED__ID_DESCRIPTION="Select io scheduler for the disk devices: noop/deadline/cfq (Default: cfq)\n Separate values for multiple devices with spaces"

SATA_LINKPWR__GROUP_DESCRIPTION="AHCI link power management (ALPM) for SATA disks:\n - min_power, med_power_with_dipm(*), medium_power, max_performance.\n (*) Kernel 4.15 (or newer) required, then recommended.\n Multiple values separated with spaces are tried sequentially until success"

SATA_LINKPWR_DENYLIST__ID_DESCRIPTION="Exclude SATA links from AHCI link power management (ALPM).\n  SATA links are specified by their host. Refer to the output of\n  tlp-stat -d to determine the host; the format is 'hostX'.\n Separate multiple hosts with spaces"

SATA_LINKPWR_BLACKLIST__ID_DESCRIPTION="Exclude SATA host devices from link power management.\n Separate multiple hosts with spaces"

AHCI_RUNTIME_PM__GROUP_DESCRIPTION="Runtime Power Management for NVMe, SATA, ATA and USB disks as well as SATA ports:\n - on=disable, auto=enable.\n  Note: SATA controllers are PCIe bus devices and handled by RUNTIME_PM further down"

AHCI_RUNTIME_PM_TIMEOUT__ID_DESCRIPTION="Seconds of inactivity before disk is suspended"

BAY_POWEROFF__GROUP_DESCRIPTION="Power off optical drive in UltraBay/MediaBay: 0=disable, 1=enable.\n 
Drive can be powered on again by releasing (and reinserting) the eject 
lever\n 
or by pressing the disc eject button on newer models.\n 
Note: an UltraBay/MediaBay hard disk is never powered off"

BAY_POWEROFF_ON_BAT__ID_DESCRIPTION="Set to power off optical drive in UltraBay/MediaBay when running on 
battery.\n 
Otherwise this feature is disabled (Default).\n 
Drive can be powered on again by releasing (and reinserting) the\n 
eject lever or by pressing the disc eject button on newer models.\n Note: an UltraBay/MediaBay hard disk is never powered off"

BAY_DEVICE__ID_DESCRIPTION="Optical drive device to power off (default sr0)"

INTEL_GPU_FREQ__GROUP_DESCRIPTION="Set the min/max/turbo frequency for the Intel GPU.\n Possible values depend on your hardware. For available frequencies see\n the output of tlp-stat -g"

RADEON_POWER_PROFILE__GROUP_DESCRIPTION="Graphics clock speed (profile method): low, mid, high, auto, default;\n auto = mid on BAT, high on AC.\n Note: radeon driver on legacy ATI hardware only (where DPM is not available)"

RADEON_DPM_STATE__GROUP_DESCRIPTION="Dynamic power management method (DPM): balanced, battery, performance.\n Note: radeon driver only"

RADEON_DPM_PERF_LEVEL__GROUP_DESCRIPTION="AMD GPU power management.\n Performance level (DPM): auto, low, high; auto is recommended.\n Note: requires amdgpu or radeon driver"

WIFI_PWR__GROUP_DESCRIPTION="Wi-Fi power saving mode"

WOL_DISABLE__ID_DESCRIPTION="Disable wake on LAN"

PCIE_ASPM__GROUP_DESCRIPTION="PCIe Active State Power Management (ASPM):\n - default(*), performance, powersave, powersupersave.\n (*) keeps BIOS ASPM defaults (recommended)"

RUNTIME_PM__GROUP_DESCRIPTION="Runtime Power Management for PCIe bus devices"

RUNTIME_PM_DENYLIST__ID_DESCRIPTION="Exclude listed PCIe device adresses from Runtime PM.\n Note: this preserves the kernel driver default, to force a certain state\n - use RUNTIME_PM_ENABLE/DISABLE instead.\n Separate multiple addresses with spaces.\n Use lspci to get the addresses (1st column)"

RUNTIME_PM_DRIVER_DENYLIST__ID_DESCRIPTION="Exclude PCIe devices assigned to the listed drivers from Runtime PM.\n Note: this preserves the kernel driver default, to force a certain state\n - use RUNTIME_PM_ENABLE/DISABLE instead.\n Separate multiple drivers with spaces.\n Leave empty to disable completely"

RUNTIME_PM_DEVICE__GROUP_DESCRIPTION="Permanently enable/disable Runtime PM for listed PCIe device addresses (independent of the power source).\n This has priority over all preceding Runtime PM settings. Separate multiple addresses with spaces.\n Use lspci to get the adresses (1st column)"

RUNTIME_PM_BLACKLIST__ID_DESCRIPTION="Exclude PCI(e) device addresses the following list from Runtime PM\n (separate with spaces). Use lspci to get the adresses (1st column)"

RUNTIME_PM_DRIVER_BLACKLIST__ID_DESCRIPTION="Exclude PCI(e) devices assigned to the listed drivers from Runtime PM\n (should prevent accidential power on of hybrid graphics' discrete part).\n Default is \"radeon nouveau\"; use \"\" to disable the feature completely.\n Separate multiple drivers with spaces"

RUNTIME_PM_GROUP__ID_DESCRIPTION="Runtime PM for *all* PCI(e) bus devices, except blacklisted ones"

CPU_DRIVER_OPMODE__GROUP_DESCRIPTION="Select a CPU scaling driver operation mode.\n Intel CPU with intel_pstate driver: active, passive\n AMD Zen 2 or newer CPU with amd-pstate_driver as of kernel 6.3/6.4:\n active, passive, guided"

CPU_SCALING_GOVERNOR__GROUP_DESCRIPTION="Select a CPU frequency scaling governor.\n Intel processor with intel_pstate driver:\n - performance, powersave(*).\n Intel processor with intel_cpufreq driver (aka intel_pstate passive mode):\n - conservative, ondemand, userspace, powersave, performance, schedutil(*).\n Intel and other processor brands with acpi-cpufreq driver:\n - conservative, ondemand(*), userspace, powersave, performance, schedutil(*).\n Use tlp-stat -p to show the active driver and available governors.\n Important:\n - Governors marked (*) above are power efficient for *almost all* workloads\n - and therefore kernel and most distributions have chosen them as defaults.\n - You should have done your research about advantages/disadvantages *before* changing the governor"

CPU_SCALING_FREQ__GROUP_DESCRIPTION="Set the min/max frequency available for the scaling governor.\n Possible values depend on your CPU. For available frequencies see\n the output of tlp-stat -p.\n Notes:\n - Min/max frequencies must always be specified for both AC *and* BAT\n - Not recommended for use with the intel_pstate scaling driver, use CPU_MIN/MAX_PERF_ON_AC/BAT instead"

CPU_ENERGY_PERF_POLICY__GROUP_DESCRIPTION="Set Intel CPU energy/performance policies HWP.EPP and EPB:\n - performance, balance_performance, default, balance_power, power.\n Values are given in order of increasing power saving.\n Notes:\n - HWP.EPP: requires kernel 4.10, intel_pstate scaling driver and Intel Core i 6th gen. or newer CPU\n - EPB: requires kernel 5.2 or module msr and x86_energy_perf_policy from linux-tools, intel_pstate or intel_cpufreq scaling driver and Intel Core i 2nd gen. or newer CPU\n - When HWP.EPP is available, EPB is not set"

CPU_HWP__GROUP_DESCRIPTION="Set energy performance hints (HWP) for Intel P-state governor:\n default, performance, balance_performance, balance_power, power\n Values are given in order of increasing power saving.\n Note: Intel Skylake or newer CPU and Kernel >= 4.10 required"

CPU_PERF__GROUP_DESCRIPTION="Set Intel CPU P-state performance: 0..100 (%).\n Limit the max/min P-state to control the power dissipation of the CPU.\n Values are stated as a percentage of the available performance.\n Requires intel_pstate or intel_cpufreq driver and Intel Core i 2nd gen. or\n newer CPU"

CPU_BOOST__GROUP_DESCRIPTION="Set the CPU \"turbo boost\" (Intel) or \"turbo core\" (AMD) feature:\n - 0=disable, 1=allow.\n Note: a value of 1 does *not* activate boosting, it just allows it"

CPU_HWP_DYN_BOOST__GROUP_DESCRIPTION="Set the Intel CPU HWP dynamic boost feature:\n - 0=disable, 1=enable.\n Requires intel_pstate scaling driver in 'active' mode and Intel Core i 6th gen. or newer CPU"

SCHED_POWERSAVE__GROUP_DESCRIPTION="Minimize number of used cpu cores/hyper-threads under light load conditions"

NMI_WATCHDOG__ID_DESCRIPTION="Kernel NMI Watchdog\n off: saves power, on: for kernel debugging only"

PHC_CONTROLS__ID_DESCRIPTION="Change CPU voltages aka \'undervolting\'\n Kernel with PHC patch required\n Freq:voltage pairs are written to /sys/devices/system/cpu/cpu0/cpufreq/phc_controls\n CAUTION: only use this, if you thoroughly understand what you are doing(!)"

PLATFORM_PROFILE__GROUP_DESCRIPTION="Select platform profile:\n - performance, balanced, low-power.\n Controls system operating characteristics around power/performance levels,\n thermal and fan speed. Values are given in order of increasing power saving.\n Note: check the output of tlp-stat -p to determine availability on your hardware and additional profiles such as: balanced-performance, quiet, cool"

MEM_SLEEP__GROUP_DESCRIPTION="System suspend mode:\n s2idle: Idle standby - a pure software, light-weight, system sleep state\n deep: Suspend to RAM - the whole system is put into a low-power state, except for memory, usually resulting in higher savings than s2idle\n CAUTION: changing suspend mode may lead to system instability and even data loss. As for the availability of different modes on your system, check the output of tlp-stat -s. If unsure, stick with the system default by not enabling this"

#ENERGY_PERF_POLICY__GROUP_DESCRIPTION="Set CPU performance versus energy savings policy.\n Requires kernel module msr and x86_energy_perf_policy from linux-tools"

RESTORE_DEVICE_STATE_ON_STARTUP__ID_DESCRIPTION="Restore radio device state (Bluetooth, WiFi, WWAN) from previous shutdown on system startup.\n Note: The parameters DEVICES_TO_DISABLE/ENABLE_ON_STARTUP/SHUTDOWN are ignored when this is enabled"

DEVICES_TO_DISABLE_ON_STARTUP__ID_DESCRIPTION="Radio devices to disable on startup: bluetooth wifi wwan"

DEVICES_TO_ENABLE_ON_STARTUP__ID_DESCRIPTION="Radio devices to enable on startup: bluetooth wifi wwan"

DEVICES_TO_DISABLE_ON_SHUTDOWN__ID_DESCRIPTION="Radio devices to disable on shutdown: bluetooth wifi wwan\n (workaround for devices that are blocking shutdown)"

DEVICES_TO_ENABLE_ON_SHUTDOWN__ID_DESCRIPTION="Radio devices to enable on shutdown: bluetooth wifi wwan\n (to prevent other operating systems from missing radios)"

DEVICES_TO_ENABLE_ON_AC__ID_DESCRIPTION="Radio devices to enable on AC: bluetooth, wifi, wwan"

DEVICES_TO_DISABLE_ON_BAT__ID_DESCRIPTION="Radio devices to disable on battery: bluetooth, wifi, wwan"

DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE__ID_DESCRIPTION="Radio devices to disable on battery when not in use (not connected):\n bluetooth, wifi, wwan"

DEVICES_TO_DISABLE_ON_CONNECT__GROUP_DESCRIPTION="Radio devices to disable on connect"

DEVICES_TO_ENABLE_ON_DISCONNECT__GROUP_DESCRIPTION="Radio devices to enable on disconnect"

DEVICES_ON_DOCK__GROUP_DESCRIPTION="Radio devices to enable/disable when docked"

DEVICES_ON_UNDOCK__GROUP_DESCRIPTION="Radio devices to enable/disable when undocked"

USB_AUTOSUSPEND__ID_DESCRIPTION="USB autosuspend feature"

USB_DENYLIST__ID_DESCRIPTION="Exclude listed devices from USB autosuspend (separate with spaces).\n Use lsusb to get the ids.\n Note: input devices (usbhid) and libsane-supported scanners are excluded automatically"

USB_EXCLUDE_AUDIO__ID_DESCRIPTION="Exclude audio devices from USB autosuspend:\n - 0=do not exclude, 1=exclude"

USB_EXCLUDE_BTUSB__ID_DESCRIPTION="Exclude bluetooth devices from USB autosuspend:\n - 0=do not exclude, 1=exclude"

USB_EXCLUDE_PHONE__ID_DESCRIPTION="Exclude phone devices from USB autosuspend:\n - 0=do not exclude, 1=exclude (enable charging)"

USB_EXCLUDE_PRINTER__ID_DESCRIPTION="Exclude printers from USB autosuspend:\n - 0=do not exclude, 1=exclude"

USB_EXCLUDE_WWAN__ID_DESCRIPTION="Exclude WWAN devices from USB autosuspend:\n - 0=do not exclude, 1=exclude"

USB_ALLOWLIST__ID_DESCRIPTION="Allow USB autosuspend for listed devices even if already denylisted or\n excluded above (separate with spaces). Use lsusb to get the ids"

USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN__ID_DESCRIPTION="Set to disable autosuspend before shutdown / otherwise to do nothing\n (workaround for USB devices that cause shutdown problems)"

#USB_BLACKLIST__ID_DESCRIPTION="Devices from the following list are excluded from autosuspend\n (separate with spaces). Use lsusb to get the ids.\n Note: input devices (usbhid) are excluded automatically"

#USB_BLACKLIST_BTUSB__ID_DESCRIPTION="Bluetooth devices are excluded from USB autosuspend"

#USB_BLACKLIST_PHONE__ID_DESCRIPTION="Phone devices are excluded from USB autosuspend"

#USB_BLACKLIST_PRINTER__ID_DESCRIPTION="Printers are excluded from USB autosuspend"

#USB_BLACKLIST_WWAN__ID_DESCRIPTION="WWAN devices are excluded from autosuspend.\n Note: works for ids 05c6:* 0bdb:* 1199:* only"

#USB_WHITELIST__ID_DESCRIPTION="Include listed devices into autosuspend even if already excluded\n by the driver or WWAN blacklists above (separate with spaces).\n Use lsusb to get the ids"

CHARGE_THRESH_BAT0__GROUP_DESCRIPTION="Battery Care -- Charge thresholds\n Charging starts when the charge level is below the START_CHARGE_THRESH value when the charger is connected. It stops when the STOP_CHARGE_THRESH value is reached.\n Required hardware: Lenovo ThinkPads and select other laptop brands are driven via specific plugins, the actual support status is shown by tlp-stat -b.\n For more explanations and vendor specific details refer to https://linrunner.de/tlp/settings/battery.html\n Notes:\n - ThinkPads may require external kernel module(s), refer to the output of tlp-stat -b\n - Vendor specific parameter value ranges are shown by tlp-stat -b\n - If your hardware supports a start *and* a stop threshold, you must specify both, otherwise TLP will refuse to apply the single threshold\n - If your hardware supports only a stop threshold, set the start value to 0\n \n BAT0: Primary / Main / Internal battery (values in %)\n  Note: also use for batteries BATC, BATT and CMB0"

CHARGE_THRESH_BAT1__GROUP_DESCRIPTION="BAT1: Secondary / Ultrabay / Slice / Replaceable battery (values in %)"

RESTORE_THRESHOLDS_ON_BAT__ID_DESCRIPTION="Restore charge thresholds when AC is unplugged"

NATACPI_ENABLE__ID_DESCRIPTION="Control battery care drivers: 0=disable, 1=enable"

TPACPI_ENABLE__ID_DESCRIPTION="ThinkPad battery drivers: 0=disable, 1=enable"

TPSMAPI_ENABLE__ID_DESCRIPTION="ThinkPad battery drivers: 0=disable, 1=enable"
