#!/bin/sh
# need superuser : called by my-installer -e
app_name="code"
set_as_default_package=true
prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false

say "Add Repo..." 1
my-superuser rpm --import https://packages.microsoft.com/keys/microsoft.asc
printf "%b\n" '[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc' | my-superuser tee /etc/yum.repos.d/vscode.repo > /dev/null

say "Installing ${app_name}..." 1
Package_installer_ "${app_name}"

[ "$set_as_default_package" = true ] && my-alternatives --set "my-ide" "${app_name}"
