#!/bin/sh -e
app_name="github-desktop"

say "Add Repo..." 1
my-superuser rpm --import https://rpm.packages.shiftkey.dev/gpg.key
printf "%b\n" '[shiftkey-packages]\nname=GitHub Desktop\nbaseurl=https://rpm.packages.shiftkey.dev/rpm/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://rpm.packages.shiftkey.dev/gpg.key\n' | my-superuser tee /etc/yum.repos.d/shiftkey-packages.repo > /dev/null
              
say "Installing ${app_name}..." 1              
Package_installer_ ${app_name}
