#!/bin/sh
app_name="Fingerprint Drivers"

packages_list="fprintd libfprint"

say "Installing $app_name ..." 1

Package_installer_ "$packages_list" || continue

say 'Adding fingerprint_gui to bin ...' 1
my-superuser ln -sf /usr/share/my_stuff/bin/X11/not_add_2_path/fingerprint_gui /usr/share/my_stuff/system_files/bin
