#!/bin/sh
# need superuser : called by my-installer
app_name="gh"
download_key "download" "https://cli.github.com/packages/githubcli-archive-keyring.gpg" "/usr/share/keyrings/githubcli-archive-keyring.gpg"
my-superuser chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
add_repo "github-cli" "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"

Package_update_

clear

say "Installing ${app_name} ..." 1

Package_installer_ "${app_name}" || continue
