#!/bin/sh
# Install vim and add lazydocker distro
no_neovim="${1:-}"
distro_path="/usr/share/my_stuff/system_files"
skel_path="${distro_path}/skel"
lazydocker_skel_path="${skel_path}/.config/lazydocker"
Title="lazydocker"

__choice=""
if [ "${no_neovim}" = "no_neovim" ];then
	say "Installing Neovim..." 1
	install_as_dependency Neovim
fi

say "Installing ${Title} updater and installer..." 1
my_installer_ln_script "lazydocker_updater" || failed_to_run "failed to run lazydocker_updater ."
