#!/bin/bash
is_it_zero_byte=false

source "/usr/share/my_stuff/system_files/var_for_distro_uninstaller"
source "/usr/share/my_stuff/system_files/Package-manager"
for backup in icons themes fonts;do
	sudo find /usr/share/${backup} -depth -maxdepth 1 -type l -delete
	sudo mv /usr/share/my_stuff/system_files/backup/${backup} /usr/share/${backup}
done

echo "delete all symbolic links in /usr/share/{applications;xsessions;lightdm;man/man1}"
sudo find /usr/share/applications -depth -maxdepth 1 -type l -delete
sudo find /usr/share/xsessions -depth -maxdepth 1 -type l -delete
sudo find /usr/share/lightdm/lightdm.conf.d -depth -maxdepth 1 -type l -delete
sudo find /usr/share/lightdm/lightdm-gtk-greeter.conf.d -depth -maxdepth 1 -type l -delete
sudo find /usr/share/man/man1 -depth -maxdepth 1 -type l -delete
echo "delete all symbolic links in /etc/xdg/autostart"
sudo find /etc/xdg/autostart -depth -maxdepth 1 -type l -delete

if [ -f "/etc/sysctl.d/90-disable_ipv6.conf" ];then
	echo "remove ipv6 from sysctl and kernal"
	sudo rm -rdf /etc/sysctl.d/90-disable_ipv6.conf || :
	sudo rm -rdf /boot/grub/${grub_image_name} || :
	
	if grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | grep -q 'ipv6.disable=1';then
		sudo sed -i 's/ipv6.disable=1//g' /etc/default/grub
	fi
	if grep 'GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | grep -q 'ipv6.disable=1';then
		sudo sed -i 's/ipv6.disable=1//g' /etc/default/grub
	fi
fi

echo "restoring home dirs"
for d in /home/*; do
    [ "$(dirname "$d")" = "/home" ] && ! id "$(basename "$d")" &>/dev/null && continue # Skip dirs that no are homes 
    user_and_group=$(stat "$(dirname "$d/.config")" -c %u:%g)
    if [ -d "${d}/.backup"* ];then
    	sudo rm -rdf "$d/.config"
		sudo rm -rdf "$d/.bashrc"
		sudo rm -rdf "$d/.Xresources"
		sudo rm -rdf "$d/.xsessionrc"
		
		sudo cp -rf /etc/skel/. $d || sudo cp -rf /etc/skel/. $d
		
		sudo wc -c "$d/.bashrc" | grep "^0" &>/dev/null && is_it_zero_byte="true"
		
		[ "${is_it_zero_byte}" = "true" ] && sudo cp -rf /etc/skel/. $d
		
		backuped="$(sudo ls "$d/.backup"*/.config)"
		for movethis in ${backuped[@]}; do
			sudo mv "${movethis}" "$d/.config"  &> /dev/null;
		done
		
		sudo rm -rdf "$d/.backup"*/.config
		
		backuped="$(sudo ls "$d/.backup"*)"
		for movethis in ${backuped[@]}; do
			sudo mv "${movethis}" "$d"  &> /dev/null;
		done
		sudo chown -R $user_and_group "$d"
		sudo rm -rdf "$d/.backup"*
	fi
done

echo "switch default xsession to ${switch_default_xsession}."
sudo update-alternatives --set x-session-manager ${switch_default_xsession}

echo "removing Packages"
Package_remove_ "${List_of_pakages_installed_}"

echo "delete /usr/bin/my-superuser"
sudo rm -rdf /usr/bin/my-superuser || :

echo "updating fc-cache"
sudo fc-cache -vf > /dev/null 2>&1
echo "updating gtk-update"
sudo gtk-update-icon-cache > /dev/null 2>&1
sudo sync > /dev/null 2>&1
echo "updating grub"
sudo grub-mkconfig -o /boot/grub/grub.cfg > /dev/null 2>&1
echo "removing /usr/share/my_stuff"
sudo rm -rdf "/usr/share/my_stuff"
echo "Done"
sudo reboot
