#!/bin/sh
is_it_zero_byte=false

. "$__distro_path_lib"
. "${__distro_path_uninstaller_var}"
. "${__distro_path_root}/lib/common/common"
. "${__distro_path_root}/Distro_Specific/Package-manager.sh"
. "${__distro_path_root}/lib/common/my_installer_and_DB_dir"

for backup in icons themes fonts;do
	my-superuser find /usr/share/${backup} -depth -maxdepth 1 -type l -delete
	my-superuser mv ${__distro_path_root}/system_files/backup/${backup} /usr/share/${backup}
done

if ls "$CHROOT_SCRIPT_PATH"/chroot-* >/dev/null 2>&1;then
	my-superuser rm -rdf "$CHROOT_SCRIPT_PATH"/chroot-*
fi

if grep -q "$CHROOT_SCRIPT_PATH/chroot-" ${__distro_path_root}/system_files/doas.conf 2>&1;then
	my-superuser sed -i "|$CHROOT_SCRIPT_PATH/chroot-|d" ${__distro_path_root}/system_files/doas.conf
	my-superuser sed -i "|$CHROOT_SCRIPT_PATH/chroot-|d" /etc/doas.conf
fi

if ls /usr/local/bin/chroot-* >/dev/null 2>&1;then
	my-superuser rm -rdf /usr/local/bin/chroot-*
fi

say "delete all symbolic links in /usr/share/{applications;xsessions;lightdm;man/man1}"
my-superuser find /usr/share/applications -depth -maxdepth 1 -type l -delete
my-superuser find /usr/share/xsessions -depth -maxdepth 1 -type l -delete
my-superuser find /usr/share/lightdm/lightdm.conf.d -depth -maxdepth 1 -type l -delete
my-superuser find /usr/share/lightdm/lightdm-gtk-greeter.conf.d -depth -maxdepth 1 -type l -delete
my-superuser find /usr/share/man/man1 -depth -maxdepth 1 -type l -delete

say "delete all symbolic links in /etc/xdg/autostart"
my-superuser find /etc/xdg/autostart -depth -maxdepth 1 -type l -delete

if [ -f "/etc/sysctl.d/90-disable_ipv6.conf" ];then
	echo "remove ipv6 from sysctl and kernal"
	my-superuser rm -rdf /etc/sysctl.d/90-disable_ipv6.conf || :
	my-superuser rm -rdf /boot/grub/${grub_image_name} || :
	
	if grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | grep -q 'ipv6.disable=1';then
		my-superuser sed -i 's/ipv6.disable=1//g' /etc/default/grub
	fi
	if grep 'GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | grep -q 'ipv6.disable=1';then
		my-superuser sed -i 's/ipv6.disable=1//g' /etc/default/grub
	fi
fi

say "restoring home dirs"
for d in /home/*; do
    [ "$(dirname "$d")" = "/home" ] && ! id "$(basename "$d")" >/dev/null 2>&1 && continue # Skip dirs that no are homes 
    user_and_group=$(stat "$(dirname "$d/.config")" -c %u:%g)
    if [ -d "${d}/.backup"* ];then
    	my-superuser rm -rdf "$d/.config"
		my-superuser rm -rdf "$d/.bashrc"
		my-superuser rm -rdf "$d/.Xresources"
	
		my-superuser cp -rf /etc/skel/. $d || my-superuser cp -rf /etc/skel/. $d
		
		my-superuser wc -c "$d/.bashrc" | grep "^0" >/dev/null 2>&1 && is_it_zero_byte="true"
		
		[ "${is_it_zero_byte}" = "true" ] && my-superuser cp -rf /etc/skel/. "$d"
		
		backuped="$(my-superuser ls "$d/.backup"*/.config)"
		for movethis in ${backuped}; do
			my-superuser mv "${movethis}" "$d/.config"  >/dev/null 2>&1;
		done
		
		my-superuser rm -rdf "$d/.backup"*/.config
		
		backuped="$(my-superuser ls "$d/.backup"*)"
		for movethis in ${backuped}; do
			my-superuser mv "${movethis}" "$d"  >/dev/null 2>&1;
		done
		my-superuser chown -R $user_and_group "$d"
		my-superuser rm -rdf "$d/.backup"*
	fi
done

if [ -n "${switch_default_xsession}" ];then
	say "switch default xsession to ${switch_default_xsession}."
	my-superuser update-alternatives --set x-session-manager ${switch_default_xsession}
fi

if [ -n "${List_of_pakages_installed_}" ];then
	say "removing Packages"
	Package_remove_ "${List_of_pakages_installed_}"
fi

say "updating fc-cache"
my-superuser fc-cache -vf > /dev/null 2>&1

say "updating gtk-update"
my-superuser gtk-update-icon-cache > /dev/null 2>&1

say "updating grub"
grub_updater_function

say "running myautorandr.sh"
my-superuser ${__distro_path_root}/bin/X11/not_add_2_path/myautorandr.sh uninstall || echo "failed to run myautorandr.sh uninstaller"

say "removing ${__distro_path_root}"
my-superuser rm -rdf "${__distro_path_root}"

say "delete /usr/bin/my-superuser"
my-superuser rm -rdf /usr/bin/my-superuser || :

say "Done"
