#!/bin/sh
# need superuser : called by my-superuser

skip_internet_check=false
packages_only=false

__opt="${1:-}"

if [ "$__opt" = "help" ] || [ "$__opt" = "--help" ] || [ "$__opt" = "-h" ];then
	echo ""
	echo "runs full system and distro upgrade."
	echo ""
	exit 0
elif [ "$__opt" = "--skip-internet-check" ];then
	skip_internet_check=true
elif [ "$__opt" = "--packages-only" ] || [ "$__opt" = "-p" ];then
	packages_only=true
fi

. "$__distro_path_lib"
. "${__distro_path_root}/lib/common/common"
. "${__distro_path_root}/Distro_Specific/Package-manager.sh"

export PATH="${__distro_path_root}/system_files/bin:${__distro_path_root}/bin/status:$PATH" 
Theme_repo_name="Theme_Stuff"

update_full_upgrade_script(){
	if [ "${skip_internet_check}" = true ];then
		return
	fi
	connectiontest
	print_purple "check if full upgrade need update. "
	do_full_upgrade_need_update=false
	mkdir -p "/tmp/$USER/disto_updater"
	getURL 'download2' "https://raw.githubusercontent.com/dari862/${__custom_distro_name}/refs/heads/main/distro_manager/full-upgrade" "/tmp/$USER/disto_updater/full-upgrade"
	chmod +x "/tmp/$USER/disto_updater/full-upgrade"
	if [ -n "$(diff "/tmp/$USER/disto_updater/full-upgrade" "${__distro_path_root}/distro_manager/full-upgrade")" ];then
		do_full_upgrade_need_update=true
	fi
	
	if [ "${do_full_upgrade_need_update}" = true ];then
		print_purple "running new version of full-upgrade. "
		if "/tmp/$USER/disto_updater"/full-upgrade --skip-internet-check;then
			exit
		else
			print_RED "failed to do full upgrade"
			exit 1
		fi
	fi
}

print_RED() {
	_msg_="${1-}"
	printf "\n\033[0;31m==> ${_msg_}\033[0m\n"
	exit 1
}

print_GREEN() {
	_msg_="${1-}"
	printf "\n\033[0;32m==> ${_msg_}\033[0m\n"
}

print_purple() {
	_msg_="${1-}"
	printf "\n\033[1;35m==> ${_msg_}\033[0m\n"
}

__upgrade_current_repo_(){
	  print_purple "status"
	  if git status | grep -q "^Your branch is up to date";then
	  	print_GREEN "Distro is up to date." 
	  	return
	  elif git status 2>&1 | grep -q 'fatal: unknown index entry format';then
	  	my-superuser rm -f "${__distro_path_root}"/.git/index
	  	my-superuser git status || :
	  fi
	  
      print_purple "Fetching"
      my-superuser git fetch || print_RED "git fetch failed... "
      
      print_purple "Stash (dont apply local changes)."
      my-superuser git stash  || print_RED "git stash failed... "
      
      print_purple "Pulling"
      my-superuser git pull  || print_RED "git pull failed... "
}

update_packages(){
	print_purple "sync package repositories"
	Package_update_
	print_GREEN "sync completed"

	print_purple "full system upgrade"
	full_upgrade_
	print_GREEN "full system upgraded"
	
	print_purple "upgrade linux kernel"
	update_linux_kernel
	print_GREEN "linux kernel upgraded"
	
	print_purple "clean package repository and remove orphan packages"
	Package_remove_ || :
	print_GREEN "orphan packages removed "

	if [ -d "$__distro_path_updater" ];then
		print_purple "updating packages(s)."
		update_packages
		print_GREEN "updating packages(s) completed. "
	fi

	if command -v yt-dlp >/dev/null 2>&1;then
		my-superuser yt-dlp -U
	fi
	
	if [ -f "${__distro_path_neverremove}/installs.json" ];then
		print_purple "runing repobin updater."
		"${__distro_path_root}"/bin/cli/repobin update
	fi
	
	if command -v flatpak >/dev/null 2>&1;then
		print_purple "updating flatpak(s)."
		my-superuser flatpak update -y
		print_GREEN "fully flatpak(s) updated."
	fi
	
	if [ "${packages_only}" = true ];then
		exit
	fi
}

Updating_Distro(){
	print_purple "checking Distro for update."
	cd "${__distro_path_root}"
	
	skel_modified=false
	print_purple "Fetching Distro repo."
	my-superuser git remote set-url origin "https://github.com/dari862/${__custom_distro_name}.git" >/dev/null 2>&1
	my-superuser git fetch || print_RED "git fetch failed... "
	if git status | grep -q "^Your branch is up to date";then
		print_GREEN "Distro is up to date." 
	  	return
	else
		print_purple "Updating Distro."
		
		if ! git diff --quiet HEAD -- skel/ skel_extra/; then
  			skel_modified=true
		fi
		
		if __upgrade_current_repo_;then
			for d in /home/*; do
				[ "$(dirname "$d")" = "/home" ] && ! id "$(basename "$d")" >/dev/null 2>&1 && continue	# Skip dirs that no are homes
    			f="${d}/${usr_flag_setup_path}"
    			if [ "$skel_modified" = true ];then
    				if my-superuser ls -A "${f}" >/dev/null 2>&1;then
						my-superuser rm -f "${f}"
					fi
				fi
			done
		else
			print_RED "Updating Distro Failed... "
		fi

		print_GREEN "Distro is up to date." 
	fi
}

Updating_Themes(){
	cd "${__distro_path_root}/${Theme_repo_name}"
	my-superuser git remote set-url origin "https://github.com/dari862/${Theme_repo_name}.git" >/dev/null 2>&1
	if __upgrade_current_repo_;then
		print_GREEN "${Theme_repo_name} is up to date." 
	else
		print_RED "Updating ${Theme_repo_name} Failed... "
	fi
}

post_updating(){
	print_purple "post updating."
	print_purple "running system_files_creater."
	"${__distro_path_root}/distro_manager"/system_files_creater
	print_GREEN "post updating completed ."
}

__Done(){
	print_GREEN "Done"
	exit 0
}
##########################################################################################################################3

update_packages

update_full_upgrade_script

Updating_Distro
Updating_Themes

post_updating

__Done
