#!/bin/sh
set -e
__distro_path="/usr/share/my_stuff"
_hub_script_dir="${__distro_path}/system_files/hub_script"

PATH="${__distro_path}/bin/bin:$PATH"
##################################################################################
show_m(){
	message="${1-}"
	printf '%b' "\n==[ \\033[1;32m${message}\\033[0m ]==\n"
}

show_wm(){
	message="${1-}"
	printf '%b' "\\033[1;33m[!]\\033[0m${message}\n"
}

show_em(){
	message="${1-}"
	printf '%b' "\\033[1;31m[-]${message}\\033[0m\n"
	exit 1 # show_em
}

show_im(){
	message="${1-}"
	printf '%b' "\\033[1;34m[*]\\033[0m${message}\n"
}
##################################################################################
show_im "update Databases ex: locate"
my-superuser updatedb

############
# terminator
############
if command -v terminator >/dev/null;then
	show_im "fix terminator"
	[ ! -d "/root/.config/terminator" ] && my-superuser mkdir -p "/root/.config/terminator"
	[ ! -f "/root/.config/terminator/config" ] && my-superuser cp -r "${__distro_path}"/extra_skel/.config/terminator/config "/root/.config/terminator"
	if my-superuser grep -q 'always_on_top =' "/root/.config/terminator/config";then
		my-superuser sed -i "s/always_on_top =.*/always_on_top = True/g" "/root/.config/terminator/config"
	else
		my-superuser sed -i '0,/[global_config]/a dddddddddddddddddddd' "/root/.config/terminator/config"
		my-superuser sed -i 's/dddddddddddddddddddd/  always_on_top = True/g' "/root/.config/terminator/config"
	fi
	
	if my-superuser grep -q 'hide_window =' "/root/.config/terminator/config";then
		my-superuser sed -i "s/hide_window =.*/hide_window = F10/g" "/root/.config/terminator/config"
	else
		my-superuser sed -i '0,/[keybindings]/a xxxxxxxxxxxxxxxxxxxxx' "/root/.config/terminator/config"
		my-superuser sed -i 's/xxxxxxxxxxxxxxxxxxxxx/  hide_window = F10/g' "/root/.config/terminator/config"
	fi
fi

############
# Remove "Set as wallpaper" from Thunar Context Menu and replace it with  "Set as wallpaper" from thunar config uac file
############
if command -v thunar >/dev/null;then
	show_im "fix thunar"
	__thunar_wall_plug="$(locate thunar | grep wall || :)"
	[ -n "${__thunar_wall_plug}" ] && my-superuser mv "${__thunar_wall_plug}" "${__thunar_wall_plug}.backup"
fi

my-superuser mkdir -p "/root/Templates"

##################################################################################

show_im "prepares for hub script"
my-superuser mkdir -p "${_hub_script_dir}"
my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/pmxkcd/pmxkcd "${_hub_script_dir}"
my-superuser ln -sf ${__distro_path}/bin/not_add_2_path/utilities/* "${_hub_script_dir}"
my-superuser ln -sf ${__distro_path}/bin/rofi/* "${_hub_script_dir}" 
my-superuser ln -sf ${__distro_path}/bin/bin/displayselect "${_hub_script_dir}"
my-superuser ln -sf ${__distro_path}/bin/apps/* "${_hub_script_dir}"
my-superuser ln -sf ${__distro_path}/bin/not_add_2_path/pmxkcd/pmxkcd "${_hub_script_dir}"
command -v systemctl >/dev/null 2>&1 && my-superuser rm -f "${_hub_script_dir}"/yautostart

show_im "remove not need script for hub script"
command -v systemctl >/dev/null 2>&1 && my-superuser ln -sf ${__distro_path}/bin/not_add_2_path/utilities/errcheck "${_hub_script_dir}"
remove_this_script_="hub rofi-launcher rofi-runner"
for script in ${remove_this_script_};do
	my-superuser rm "${_hub_script_dir}"/"$script"
done

show_im "creating missing dir"

my-superuser mkdir -p "${__distro_path}"/bin/not_add_2_path/distrobox_center/Apps
my-superuser mkdir -p "${__distro_path}"/bin/not_add_2_path/distrobox_center/Gaming

show_im "create uniq system files"
my-superuser mkdir -p "${__distro_path}"/system_files/updater
my-superuser mkdir -p "${__distro_path}"/system_files/downloaded
my-superuser mkdir -p "${__distro_path}"/system_files/git
my-superuser mkdir -p "${__distro_path}"/system_files/deployed_containers/deployed
my-superuser mkdir -p "${__distro_path}"/system_files/auto_completion
my-superuser mkdir -p "${__distro_path}"/system_files/applications

show_im "LN essional files"
my-superuser mkdir -p "${__distro_path}"/system_files/bin
my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/pmxkcd/pmxkcd "${__distro_path}"/system_files/bin/
command -v systemctl >/dev/null 2>&1 && my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/utilities/errcheck "${__distro_path}"/system_files/bin/

show_im "copy skell file to system_files/skel ."
my-superuser cp -r "${__distro_path}/skel" "${__distro_path}/system_files" 
my-superuser cp -r "${__distro_path}/lib/rc.xml" "${__distro_path}/system_files/rc.xml"
my-superuser mkdir -p "${__distro_path}/system_files/skel/.local/bin"

my-superuser mkdir -p "${__distro_path}"/system_files/skel/.config/mpd/playlists
my-superuser touch "${__distro_path}"/system_files/skel/.config/mpd/database
my-superuser mkdir -p "${__distro_path}"/system_files/skel/.local/share/bash_history

if command -v geany >/dev/null ; then
	show_im "copy geany skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/geany" "${__distro_path}/system_files/skel/.config" 
fi

if command -v lf >/dev/null ; then
	show_im "copy lf skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/lf" "${__distro_path}/system_files/skel/.config" 
fi

if command -v nsxiv >/dev/null || command -v sxiv >/dev/null ; then
	show_im "copy nsxiv skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/nsxiv" "${__distro_path}/system_files/skel/.config"
	my-superuser cp -r "${__distro_path}/extra_skel/.config/sxiv" "${__distro_path}/system_files/skel/.config" 
fi

if command -v viewnior >/dev/null ; then
	show_im "copy viewnior skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/viewnior" "${__distro_path}/system_files/skel/.config"
fi

if command -v terminator >/dev/null ; then
	show_im "copy terminator skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/terminator" "${__distro_path}/system_files/skel/.config" 
fi

if command -v pcmanfm >/dev/null ; then
	show_im "copy pcmanfm skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/pcmanfm" "${__distro_path}/system_files/skel/.config" 
fi

if command -v thunar >/dev/null ; then
	show_im "copy gigolo skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/Thunar" "${__distro_path}/system_files/skel/.config" 
fi

if command -v gigolo >/dev/null ; then
	show_im "copy gigolo skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/gigolo" "${__distro_path}/system_files/skel/.config" 
fi

if command -v plank >/dev/null ; then
	show_im "copy plank skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/plank" "${__distro_path}/system_files/skel/.config" 
	my-superuser cp -r "${__distro_path}/extra_skel/.local/share/plank" "${__distro_path}/system_files/skel/.local/share/" 
fi

if command -v xbindkey >/dev/null ; then
	show_im "copy xbindkey skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.xbindkeysrc" "${__distro_path}/system_files/skel" 
fi

if command -v clipit >/dev/null ; then
	show_im "copy clipit skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/clipit" "${__distro_path}/system_files/skel/.config" 
fi

if command -v jgmenu >/dev/null ; then
	show_im "copy jgmenu skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/jgmenu" "${__distro_path}/system_files/skel/.config" 
fi

if command -v greenclip >/dev/null ; then
	show_im "copy greenclip skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/greenclip.toml" "${__distro_path}/system_files/skel/.config" 
fi

if command -v zathura >/dev/null ; then
	show_im "copy zathura skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/zathura" "${__distro_path}/system_files/skel/.config" 
fi

if command -v tint2 >/dev/null ; then
	show_im "copy tint2 skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/tint2" "${__distro_path}/system_files/skel/.config" 
fi

if command -v xfce4-panel >/dev/null ; then
	show_im "copy xfce4-panel skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/xfce4" "${__distro_path}/system_files/skel/.config"
	my-superuser cp -r "${__distro_path}/extra_skel/.local/share/xfce4" "${__distro_path}/system_files/skel/.local/share/"
fi

if command -v lxterminal >/dev/null ; then
	show_im "copy lxterminal skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/lxterminal" "${__distro_path}/system_files/skel/.config" 
fi

if command -v alacritty >/dev/null ; then
	show_im "copy alacritty skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/alacritty" "${__distro_path}/system_files/skel/.config" 
fi

if command -v bspwm >/dev/null ; then
	show_im "copy bspwm skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/bspwm" "${__distro_path}/system_files/skel/.config" 
	my-superuser cp -r "${__distro_path}/extra_skel/.config/sxhkd" "${__distro_path}/system_files/skel/.config" 
fi

if command -v polybar >/dev/null ; then
	show_im "copy polybar skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/polybar" "${__distro_path}/system_files/skel/.config"
	
	if [ -d "${__distro_path}/bin/polybar" ] ; then
		my-superuser ln -sf "${__distro_path}"/bin/polybar/* "${__distro_path}"/system_files/bin
	fi
fi

if command -v polybar >/dev/null ; then
	show_im "copy polybar skell file to system_files/skel ."
	my-superuser cp -r "${__distro_path}/extra_skel/.config/polybar" "${__distro_path}/system_files/skel/.config"
	
	if [ -d "${__distro_path}/bin/polybar" ] ; then
		my-superuser ln -sf "${__distro_path}"/bin/polybar/* "${__distro_path}"/system_files/bin
	fi
fi

show_im "LN bin files to system_files/bin ."

if [ -d "${__distro_path}/bin/bin" ] ; then
	show_im "bin bin files to system_files/bin ."
	my-superuser ln -sf "${__distro_path}"/bin/bin/* "${__distro_path}"/system_files/bin
fi

if [ -d "${__distro_path}/bin/apps" ] ; then
	show_im "apps bin files to system_files/bin ."
	my-superuser ln -sf "${__distro_path}"/bin/apps/* "${__distro_path}"/system_files/bin
	command -v systemctl >/dev/null 2>&1 && my-superuser rm -f "${__distro_path}"/system_files/bin/yautostart
fi

if [ -d "${__distro_path}/bin/rofi" ] ; then
	show_im "rofi bin files to system_files/bin ."
	my-superuser ln -sf "${__distro_path}"/bin/rofi/* "${__distro_path}"/system_files/bin
fi

if [ -d "${__distro_path}/bin/session_managers" ] ; then
	show_im "session_managers bin files to system_files/bin ."
	my-superuser ln -sf "${__distro_path}"/bin/session_managers/* "${__distro_path}"/system_files/bin
fi

show_im "nbrowser bin files to system_files/bin ."
my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/nbrowser/nbrowser "${__distro_path}"/system_files/bin
my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/nbrowser/nbrowser.desktop /usr/share/applications

if [ -f "${__distro_path}/system_files/this_is_laptop" ];then
	show_im "laptop stuff."
	my-superuser ln -sf "${__distro_path}"/bin/laptop/gpu-switcher-session "${__distro_path}"/system_files/skel/.config/autostartscripts/
	my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/laptop/yadtlp.desktop "${__distro_path}"/system_files/applications
	my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/laptop/yadtlp.desktop /usr/share/applications
	my-superuser ln -sf "${__distro_path}"/bin/not_add_2_path/laptop/toggletouch "${__distro_path}"/system_files/bin
	if [ -d "${__distro_path}/bin/laptop" ] ; then
		show_im "laptop bin files to system_files/bin ."
		my-superuser ln -sf "${__distro_path}"/bin/laptop/* "${__distro_path}"/system_files/bin
	fi
fi

if [ -f "${__distro_path}"/system_files/fingerprint_exist ];then 
	show_im "fingerprint bin files to system_files/bin ."
	my-superuser ln -sf ${__distro_path}/bin/not_add_2_path/fingerprint_gui ${__distro_path}/system_files/bin
fi

##################################################################################

show_im "Running script for create_DB.sh --all"
my-superuser ${__distro_path}/bin/not_add_2_path/create_DB.sh --all

show_im "Running must_create_script."
for script in "${__distro_path}"/bin/not_add_2_path/must_create_script/*;do
	show_im "running $(basename "$script"). from must_create_script ."
	. "$script"/make
done

show_im "Create keybinds."
my-superuser "${__distro_path}"/system_files/bin/keybinds --initial-step

my-superuser ln -sf ${__distro_path}/distro_manager/full-upgrade ${__distro_path}/system_files/bin
