#!/bin/sh

app_name="sublime-text"
say "Configuring repositories..."
download_key "gpg" "https://download.sublimetext.com/sublimehq-pub.gpg" "/usr/share/keyrings/sublimetext-keyring.gpg"
add_repo "sublimetext" "deb [arch=amd64 signed-by=/usr/share/keyrings/sublimetext-keyring.gpg] https://download.sublimetext.com/ apt/stable/"

Package_update_

clear

say "Installing ${app_name} ..." 1

Package_installer_ "${app_name}" || continue
