##  Picom user configuration file (~/.config/picom.conf)
##  with reference to: /usr/share/doc/picom/examples/picom.sample.conf
##
##  Various people have contributed to this file,
##  so the meaning of "I" is not well defined.
##
##  In most cases 'man picom' has more information.
##  See also: https://wiki.archlinux.org/title/Picom


#################################
#  Shadows
#################################
@include "Shadows.conf"

#################################
#           Fading              #
#################################
@include "Fading.conf"

#################################
#   Transparency / Opacity      #
#################################
@include "Opacity.conf"

#################################
#     Background-Blurring       #
#################################
@include "Blurring.conf"

#################################
#       	corner		        #
#################################
@include "corner.conf"

#################################
#       General Settings        #
#################################
@include "General.conf"

#################################
#  Backend
#################################
@include "Backend.conf"

#################################
#  rules
#################################
@include "rules.conf"
