#!/bin/sh

if grep -q "^\s*\[multilib\]" /etc/pacman.conf; then # enabled
	return 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	return 1
fi

echo "[multilib]" | my-superuser tee -a /etc/pacman.conf
echo "Include = /etc/pacman.d/mirrorlist" | my-superuser tee -a /etc/pacman.conf
Package_update_
