#!/bin/sh
if [ "$Distro_installer_mode" = false ];then
	_SUPERUSER="my-superuser"
	[ "$(id -u)" -eq 0 ] && _SUPERUSER=""
fi


if grep -q "^\s*\[multilib\]" /etc/pacman.conf; then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	echo "[multilib]" | ${_SUPERUSER} tee -a /etc/pacman.conf
	echo "Include = /etc/pacman.d/mirrorlist" | ${_SUPERUSER} tee -a /etc/pacman.conf
	Package_update_
fi
