#!/bin/sh
if [ "$(id -u)" -eq 0 ];then
	_SUPERUSER=""
else
	_SUPERUSER="my-superuser"
fi

Packages_2_install=""
add_nvidia=false
add_amd=false
add_intel=false

if grep -q "LIBVA_DRIVER_NAME=nvidia" /etc/environment && grep -q "MOZ_DISABLE_RDD_SANDBOX=1" /etc/environment && grep -q "LIBVA_DRIVER_NAME=nvidia" /etc/environment; then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	say "enabling HardwareAcceleration"
	if [ "$(lspci | grep -i nvidia | grep VGA -c)" != "0" ];then
		say "Nvidia detected."
		Packages_2_install="nvidia nvidia-utils libva libva-utils nvidia-vaapi-driver" || continue
	fi

	if [ "$(lspci | grep -i amd | grep VGA -c)" != "0" ];then
		say "AMD detected."
		Packages_2_install="mesa libva-mesa-driver mesa-vdpau libva-utils" || continue
	fi

	if [ "$(lspci | grep -i intel | grep VGA -c)" != "0" ];then
		say "Intel detected."
		Packages_2_install="intel-media-driver libva-intel-driver libva-utils" || continue
	fi

	say "Installing Packages..."
	Package_installer_ "$Packages_2_install"

	if [ "$(lspci | grep -i nvidia | grep VGA -c)" != "0" ];then
		ENV_FILE="/etc/environment"
		# Remove old entries if they exist
		${_SUPERUSER} sed -i '/^__NV_PRIME_RENDER_OFFLOAD/d' "$ENV_FILE" || :
		${_SUPERUSER} sed -i '/^__GLX_VENDOR_LIBRARY_NAME/d' "$ENV_FILE" || :
		${_SUPERUSER} sed -i '/^__VK_LAYER_PATH/d' "$ENV_FILE" || :
		${_SUPERUSER} sed -i '/^MOZ_DISABLE_RDD_SANDBOX/d' "/etc/environment" || :
		${_SUPERUSER} sed -i '/^LIBVA_DRIVER_NAME/d' "/etc/environment" || :
		printf "LIBVA_DRIVER_NAME=nvidia\nMOZ_DISABLE_RDD_SANDBOX=1\n__NV_PRIME_RENDER_OFFLOAD=1\n__GLX_VENDOR_LIBRARY_NAME=nvidia\n__VK_LAYER_PATH=/usr/share/vulkan/implicit_layer.d" | ${_SUPERUSER} tee -a /etc/environment >/dev/null
	fi

	say "Hardware Acceleration setup completed successfully."
fi
