#!/bin/sh
# need superuser : called by my-installer

app_name="firefox"
set_as_default_package=true
remove_esr_firefox=false

prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false
is_installed firefox-esr && prompt "  Do you want remove ${app_name}-esr?"  && remove_esr_firefox=true || :
say "Installing ${app_name}..." 1

say 'Adding Repo...' 1
getURL "2term" "https://packages.mozilla.org/apt/repo-signing-key.gpg" | my-superuser tee /etc/apt/keyrings/packages.mozilla.org.asc
add_repo "mozilla" "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | my-superuser tee /etc/apt/preferences.d/mozilla

Package_update_

clear

say "Installing ${app_name}..." 1
Package_installer_ "${app_name}" || continue

if [ "$remove_esr_firefox" = true ];then
	Package_remove_ "${app_name}-esr"
fi

if [ "$set_as_default_package" = true ];then
	my-alternatives --set "my-www-browser" "${app_name}" || continue
fi
