#!/bin/sh -e
app_name="vivaldi-stable"

say 'Adding Repo...' 1
download_key "gpg" "https://repo.vivaldi.com/archive/linux_signing_key.pub" "/usr/share/keyrings/vivaldi-browser.gpg"
echo "deb [signed-by=/usr/share/keyrings/vivaldi-browser.gpg arch=$(dpkg --print-architecture)] https://repo.vivaldi.com/archive/deb/ stable main" | my-superuser tee /etc/apt/sources.list.d/vivaldi-archive.list >/dev/null 2>&1

Package_update_

say "Installing ${app_name}..." 1
Package_installer_ ${app_name} || continue
