#!/bin/sh -e
app_name="freeoffice"

say "Installing ${app_name}..." 1
getURL 'download2' 'https://shop.softmaker.com/repo/softmaker.repo' "/tmp/softmaker.repo"
my-superuser chown root:root "/tmp/softmaker.repo"
my-superuser mv "/tmp/softmaker.repo" "/etc/yum.repos.d/"
Package_update_
Package_installer_ softmaker-freeoffice-2024
