#!/bin/sh
# need superuser : called by my-installer
app_name="lua luarocks stylua"
say "Installing ${app_name}..." 1
Package_installer_ "${app_name}" || continue
my-superuser luarocks install luacheck

