#!/bin/sh

app_name="openrgb"
if [ -f '/usr/share/my_stuff/system_files/Distrobox_ready' ];then
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	pacstall_install openrgb-git || continue
fi
