#!/bin/sh
#called by : my-installer
app_name="openrgb"
if check_system_ready_file "Distrobox_ready";then
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	pacstall_install openrgb-git || continue
fi
