#!/bin/sh
xrgba_it() {
   	hex=$1
   	# Extract the two-digit hex values and convert to decimal
	r=$(echo "$hex" | cut -c 1-2)
   	g=$(echo "$hex" | cut -c 3-4)
   	b=$(echo "$hex" | cut -c 5-6)
   	
   	echo "$r/$g/$b/ff"
}
	
strip_it(){
	echo "$1" | sed 's/#//g'
}

theme_color_file_builder(){
	dynamic_theme_scripts_dir="${__distro_path_root}/bin/not_add_2_path/bashwal"
	palette_extractor_output_file="${temp_theme_file_dir}/temp_${style}_colors.sh"
	
	# Create palette if the theme file doesn't exist
	if [ ! -f "$palette_extractor_output_file" ]; then
    	"${dynamic_theme_scripts_dir}"/bashwal -i "${wallpaper_are}" -o "$palette_extractor_output_file"
	fi
	
	# Source the theme file
	if ! . "${palette_extractor_output_file}" >/dev/null 2>&1; then
    	show_em "failed to source ${palette_extractor_output_file}"
	fi
	
	[ -z "$alpha" ] && alpha="100"
	background="$color0"
	foreground="$color15"
	background="$(strip_it $background)"
	foreground="$(strip_it $foreground)"
	cursor="$(strip_it $foreground)"
	color0="$(strip_it $color0)"
	color1="$(strip_it $color1)"
	color2="$(strip_it $color2)"
	color3="$(strip_it $color3)"
	color4="$(strip_it $color4)"
	color5="$(strip_it $color5)"
	color6="$(strip_it $color6)"
	color7="$(strip_it $color7)"
	color8="$(strip_it $color8)"
	color9="$(strip_it $color9)"
	color10="$(strip_it $color10)"
	color11="$(strip_it $color11)"
	color12="$(strip_it $color12)"
	color13="$(strip_it $color13)"
	color14="$(strip_it $color14)"
	color15="$(strip_it $color15)"
	
	active="${foreground}"
	inactive="${color3}"
	
	background_xrgba="$(xrgba_it $background)"
	foreground_xrgba="$(xrgba_it $foreground)"
	cursor_xrgba="$(xrgba_it $foreground)"
	color0_xrgba="$(xrgba_it $color0)"
	color1_xrgba="$(xrgba_it $color1)"
	color2_xrgba="$(xrgba_it $color2)"
	color3_xrgba="$(xrgba_it $color3)"
	color4_xrgba="$(xrgba_it $color4)"
	color5_xrgba="$(xrgba_it $color5)"
	color6_xrgba="$(xrgba_it $color6)"
	color7_xrgba="$(xrgba_it $color7)"
	color8_xrgba="$(xrgba_it $color8)"
	color9_xrgba="$(xrgba_it $color9)"
	color10_xrgba="$(xrgba_it $color10)"
	color11_xrgba="$(xrgba_it $color11)"
	color12_xrgba="$(xrgba_it $color12)"
	color13_xrgba="$(xrgba_it $color13)"
	color14_xrgba="$(xrgba_it $color14)"
	color15_xrgba="$(xrgba_it $color15)"
	
	panel_style_name=""
	
	if [ "$_panel_name_" = 'polybar' ];then
		panel_style_name="polybar_STYLE"
	elif [ "$_panel_name_" = 'tint2' ];then
		panel_style_name="tint2_STYLE"
	fi
	
	tee "$HOME/.config/blob/${_panel_name_}/${_style}/style.conf" <<-EOF >/dev/null
	Style_name="dynamic"
	
	# Distro_config
	##############
	_panel_name_="$_panel_name_"
	${panel_style_name}="dynamic"
	ROFI_STYLE="cyber"
	conky_sessionfile="openbox-conky.conf"
	tint2_sessionfile="dynamic.tint2rc"
	layout_are="zoom"
	
	# wallpaper_mode
	##############
	wallpaper_are="${wallpaper_are}"
	random_wallpaper=false
	
	# dunstrc
	##############
	dunstrc_icon_position=left
	dunstrc_frame_color="#${foreground}"
	dunstrc_separator_color=auto
	dunstrc_transparency=0
	dunstrc_origin=top-right
	dunstrc_offset="(10, 46)"
	dunstrc_frame_width=6
	dunstrc_format="<b>%a</b>\n%s\n%b"
	dunstrc_low_timeout=2
	dunstrc_low_background="#${background}"
	dunstrc_low_foreground="#${foreground}"
	dunstrc_low_frame_color="#${foreground}"
	dunstrc_normal_timeout=5
	dunstrc_normal_background="#${background}"
	dunstrc_normal_foreground="#${foreground}"
	dunstrc_normal_frame_color="#${color3}"
	dunstrc_critical_timeout=0
	dunstrc_critical_background="#${background}"
	dunstrc_critical_foreground="#${foreground}"
	dunstrc_critical_frame_color="#${color1}"
	
	# gtkrc_theme
	##############
	gtk_theme_name="dynamic"
	gtk_icon_name="dynamic"
	gtk_font_name="Noto Sans 9"
	gtk_cursor_name="Qogirr-dark"
	
	# openbox
	##############
	openbox_menu=menu-icons
	openbox_bottom=10
	openbox_top=0
	openbox_right=10
	openbox_left=10
	openbox_font=JetBrainsMono
	openbox_size=9
	openbox_theme=dynamic
	openbox_titleLayout=MLC
	openbox_gtk_icon_name="dynamic"
	
	# rofi
	##############
	rofi_background="#${background}FF"
	rofi_active="#${color1}FF"
	rofi_background_alt="#${background}FF"
	rofi_foreground="#${foreground}FF"
	rofi_selected="#${color2}FF"
	rofi_urgent="#${color3}FF"
	rofi_font="Iosevka 10"
	rofi_text_font='@font'
	rofi_icon_font="Material 14"
	
	# bspwm
	##############
	## Bspwm colors
	BSPWM_FBC="#${color3}"
	BSPWM_NBC="#${background}"
	BSPWM_ABC="#${foreground}"
	BSPWM_PFC="#${background}"
	BSPWM_PBC="#${background}"
	
	## Bspwm appearance
	BSPWM_BORDER="1"
	BSPWM_GAP="10"
	BSPWM_SRATIO="0.50"
	
	## Bspwm Extra
	BSP_BORDERLESS_MONOCLE=true
	BSP_GAPLESS_MONOCLE=true
	BSP_PADDINGLESS_MONOCLE=true
	BSP_SINGLE_MONOCLE=false
	BSP_FOCUS_FOLLOWS_POINTER=true
	BSP_PRESEL_FEEDBACK=true
	
	# alacritty
	##############
	alacritty_family="JetBrainsMonoNerdFont"
	alacritty_size=10
	
	# jgmenu
	##############
	jgmenu_font="JetBrainsMono"
	jgmenu_size="9"
	jgmenu_color_menu_bg="#${color8} 100"
	jgmenu_color_menu_border="#${background} 100"
	jgmenu_color_norm_bg="#${background} 00"
	jgmenu_color_norm_fg="#${foreground} 100"
	jgmenu_color_sel_bg="#${color5} 100"
	jgmenu_color_sel_fg="#${color15} 100"
	jgmenu_color_sel_border="#${color5} 100"
	jgmenu_color_title_bg="#${color6} 100"
	jgmenu_color_title_fg="#${color15} 100"
	jgmenu_color_title_border="#${color6} 100"
	jgmenu_color_sep_fg="#${background} 100"
	jgmenu_item_margin_x="1"
	jgmenu_item_margin_y="1"
	jgmenu_stay_alive="1"
	jgmenu_menu_padding_right="0"
	jgmenu_menu_padding_bottom="0"
	jgmenu_menu_padding_left="0"
	jgmenu_menu_radius="1"
	jgmenu_sep_halign="right"
	jgmenu_icon_size="0"
	jgmenu_icon_theme="Material-Solarized-Suru++"
	jgmenu_menu_border="0"
	
	# lightdm-greeter
	##############
	greeter_icon_theme_name='Bunsen-lightdm'
	greeter_position='57%,start 22%,start'
	
	# plank
	##############
	plank_use_plank="yes"
	plank_hide_mode='auto'
	plank_offset=0
	plank_position=bottom
	
	# GTK Colors
	##############
	alpha="$alpha"
	active="$active"
	inactive="$inactive"
	
	background="$background"
	foreground="$foreground"
	
	cursor="$cursor"
	color0="$color0"
	color1="$color1"
	color2="$color2"
	color3="$color3"
	color4="$color4"
	color5="$color5"
	color6="$color6"
	color7="$color7"
	color8="$color8"
	color9="$color9"
	color10="$color10"
	color11="$color11"
	color12="$color12"
	color13="$color13"
	color14="$color14"
	color15="$color15"
	EOF
}

create_polybar_file(){
	tee "$HOME/.config/polybar/${_style}/colors.ini" << EOF >/dev/null
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; main colors
background = #${background}
foreground = #${foreground}
RED = #${color3}
fontcolor = #${foreground}

;; shades
shade1 = #${color1}
shade2 = #${color2}
shade3 = #${color4}
shade4 = #${color5}
shade5 = #${color6}
shade6 = #${color7}
shade7 = #${color8}
shade8 = #${color9}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
EOF
}

create_tint2_file(){
	tee "$HOME/.config/tint2/${_style}.tint2rc" << EOF >/dev/null
## Configuration for tint2 panel.
#-------------------------------------
# Gradients
#-------------------------------------
# Backgrounds
# Background 1: Panel, Tooltip
rounded = 0
border_width = 0
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #${background} 100
border_color = #${foreground} 0
background_color_hover = #${background} 0
border_color_hover = #${foreground} 0
background_color_pressed = #${background} 0
border_color_pressed = #${foreground} 0

# Background 2: Battery, Button, Default task, Executor, Inactive desktop name, Normal task, Systray
rounded = 10
border_width = 0
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #${background} 100
border_color = #${foreground} 0
background_color_hover = #${background} 100
border_color_hover = #${foreground} 0
background_color_pressed = #${background} 100
border_color_pressed = #${foreground} 0

# Background 3: Active desktop name, Active task
rounded = 10
border_width = 0
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #${background} 100
border_color = #${foreground} 0
background_color_hover = #${background} 100
border_color_hover = #${foreground} 0
background_color_pressed = #${background} 100
border_color_pressed = #${foreground} 0

# Background 4: Iconified task
rounded = 10
border_width = 0
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #${background} 100
border_color = #${foreground} 0
background_color_hover = #${background} 100
border_color_hover = #${foreground} 0
background_color_pressed = #${background} 100
border_color_pressed = #${foreground} 0

# Background 5: Urgent task
rounded = 10
border_width = 0
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #${background} 100
border_color = #${foreground} 0
background_color_hover = #${background} 100
border_color_hover = #${foreground} 0
background_color_pressed = #${background} 100
border_color_pressed = #${foreground} 0

#-------------------------------------
# Panel
panel_items = PTSEEEEEC
panel_size = 100% 38
panel_margin = 0 0
panel_padding = 6 6 6
panel_background_id = 1
wm_menu = 1
panel_dock = 0
panel_pivot_struts = 0
panel_position = top center horizontal
panel_layer = top
panel_monitor = all
panel_shrink = 0
autohide = 0
autohide_show_timeout = 0
autohide_hide_timeout = 0.5
autohide_height = 2
strut_policy = follow_size
panel_window_name = tint2
disable_transparency = 1
mouse_effects = 1
font_shadow = 0
mouse_hover_icon_asb = 100 0 10
mouse_pressed_icon_asb = 100 0 0
scale_relative_to_dpi = 0
scale_relative_to_screen_height = 0

#-------------------------------------
# Taskbar
taskbar_mode = single_desktop
taskbar_hide_if_empty = 1
taskbar_padding = 0 0 6
taskbar_background_id = 0
taskbar_active_background_id = 0
taskbar_name = 1
taskbar_hide_inactive_tasks = 0
taskbar_hide_different_monitor = 0
taskbar_hide_different_desktop = 0
taskbar_always_show_all_desktop_tasks = 0
taskbar_name_padding = 10 0
taskbar_name_background_id = 2
taskbar_name_active_background_id = 3
taskbar_name_font = JetBrainsMono Nerd Font 10
taskbar_name_font_color = #${foreground} 100
taskbar_name_active_font_color = #${foreground} 100
taskbar_distribute_size = 1
taskbar_sort_order = none
task_align = left

#-------------------------------------
# Task
task_text = 1
task_icon = 1
task_centered = 0
urgent_nb_of_blink = 100000
task_maximum_size = 180 30
task_padding = 10 5 5
task_font = JetBrainsMono Nerd Font 9
task_tooltip = 1
task_thumbnail = 1
task_thumbnail_size = 256
task_font_color = #${foreground} 100
task_normal_font_color = #${foreground} 100
task_active_font_color = #${foreground} 100
task_urgent_font_color = #${foreground} 100
task_iconified_font_color = #${background} 100
task_background_id = 2
task_normal_background_id = 2
task_active_background_id = 3
task_urgent_background_id = 5
task_iconified_background_id = 4
mouse_left = toggle_iconify
mouse_middle = shade
mouse_right = close
mouse_scroll_up = toggle
mouse_scroll_down = iconify

#-------------------------------------
# System tray (notification area)
systray_padding = 10 0 8
systray_background_id = 2
systray_sort = right2left
systray_icon_size = 16
systray_icon_asb = 100 0 0
systray_monitor = primary
systray_name_filter = 

#-------------------------------------
# Launcher
launcher_padding = 10 0 5
launcher_background_id = 2
launcher_icon_background_id = 0
launcher_icon_size = 20
launcher_icon_asb = 100 0 0
launcher_icon_theme_override = 0
startup_notifications = 1
launcher_tooltip = 1
launcher_item_app = /usr/share/applications/my-terminal-emulator.desktop
launcher_item_app = /usr/share/applications/my-www-browser.desktop
launcher_item_app = /usr/share/applications/my-file-manager.desktop
launcher_item_app = /usr/share/applications/my-text-editor.desktop

#-------------------------------------
# Clock
time1_format = %I:%M %p
time2_format = 
time1_font = JetBrainsMono Nerd Font Bold 12
time1_timezone = 
time2_timezone = 
clock_font_color = #${foreground} 100
clock_padding = 0 0
clock_background_id = 0
clock_tooltip = %A, %d %B %Y
clock_tooltip_timezone = 
clock_lclick_command = 
clock_rclick_command = 
clock_mclick_command = 
clock_uwheel_command = 
clock_dwheel_command = 

#-------------------------------------
# Battery
battery_tooltip = 1
battery_low_status = 20
battery_low_cmd = dunstify -u low -h string:x-dunst-stack-tag:tint2 'Battery Low!'
battery_full_cmd = dunstify -u low -h string:x-dunst-stack-tag:tint2 'Battery Charged!'
bat1_font = JetBrainsMono Nerd Font 10
battery_font_color = #${foreground} 100
bat1_format = %p
bat2_format = 
battery_padding = 10 0
battery_background_id = 2
battery_hide = 100
battery_lclick_command = power_manager_settings
battery_rclick_command = ${__distro_path_root}/bin/not_add_2_path/batt_notifcation -n
battery_mclick_command = 
battery_uwheel_command = 
battery_dwheel_command = 
ac_connected_cmd = dunstify -u low -h string:x-dunst-stack-tag:tint2 'Charger Plugged!'
ac_disconnected_cmd = dunstify -u low -h string:x-dunst-stack-tag:tint2 'Charger Unplugged!'

#-------------------------------------
# Executor 1
execp = new
execp_command = ${__distro_path_root}/system_files/volume_cli_control
execp_interval = 0
execp_has_icon = 0
execp_cache_icon = 0
execp_continuous = 0
execp_markup = 1
execp_monitor = all
execp_tooltip = Volume
execp_lclick_command = ${__distro_path_root}/system_files/volume_cli_control --toggle
execp_rclick_command = ${__distro_path_root}/system_files/volume_cli_control --toggle-mic
execp_mclick_command = volume_controller
execp_uwheel_command = ${__distro_path_root}/system_files/volume_cli_control --inc
execp_dwheel_command = ${__distro_path_root}/system_files/volume_cli_control --dec
execp_font = JetBrainsMono Nerd Font 10
execp_font_color = #${foreground} 100
execp_padding = 10 0
execp_background_id = 2
execp_centered = 0
execp_icon_w = 0
execp_icon_h = 0

#-------------------------------------
# Executor 2
execp = new
execp_command = ${__distro_path_root}/bin/X11/WM/disto_brightness_controller
execp_interval = 0
execp_has_icon = 0
execp_cache_icon = 0
execp_continuous = 0
execp_markup = 1
execp_monitor = all
execp_tooltip = Brightness
execp_lclick_command = 
execp_rclick_command = 
execp_mclick_command = 
execp_uwheel_command = ${__distro_path_root}/bin/X11/WM/disto_brightness_controller --inc
execp_dwheel_command = ${__distro_path_root}/bin/X11/WM/disto_brightness_controller --dec
execp_font = JetBrainsMono Nerd Font 10
execp_font_color = #${foreground} 100
execp_padding = 10 0
execp_background_id = 2
execp_centered = 0
execp_icon_w = 0
execp_icon_h = 0

#-------------------------------------
# Executor 3
execp = new
execp_command = ${__distro_path_root}/bin/not_add_2_path/bluetooth.sh
execp_interval = 1
execp_has_icon = 0
execp_cache_icon = 0
execp_continuous = 0
execp_markup = 1
execp_monitor = all
execp_tooltip = Bluetooth
execp_lclick_command = rofi-bluetooth
execp_rclick_command = ${__distro_path_root}/bin/not_add_2_path/bluetooth_manager
execp_mclick_command = 
execp_uwheel_command = 
execp_dwheel_command = 
execp_font = JetBrainsMono Nerd Font 10
execp_font_color = #${foreground} 100
execp_padding = 10 0
execp_background_id = 2
execp_centered = 0
execp_icon_w = 0
execp_icon_h = 0

#-------------------------------------
# Executor 4
execp = new
execp_command = get_network
execp_interval = 1
execp_has_icon = 0
execp_cache_icon = 0
execp_continuous = 0
execp_markup = 1
execp_monitor = all
execp_tooltip = Networks
execp_lclick_command = rofi-network-manager
execp_rclick_command = nm-connection-editor
execp_mclick_command = 
execp_uwheel_command = 
execp_dwheel_command = 
execp_font = JetBrainsMono Nerd Font 10
execp_font_color = #${foreground} 100
execp_padding = 10 0
execp_background_id = 2
execp_centered = 0
execp_icon_w = 0
execp_icon_h = 0

#-------------------------------------
# Executor 5
execp = new
execp_command = get_battery
execp_interval = 10
execp_has_icon = 0
execp_cache_icon = 0
execp_continuous = 0
execp_markup = 1
execp_monitor = all
execp_tooltip = Battery
execp_lclick_command = power_manager_settings
execp_rclick_command = power_manager_settings
execp_mclick_command = 
execp_uwheel_command = 
execp_dwheel_command = 
execp_font = JetBrainsMono Nerd Font 10
execp_font_color = #${foreground} 100
execp_padding = 10 0
execp_background_id = 2
execp_centered = 0
execp_icon_w = 0
execp_icon_h = 0

#-------------------------------------
# Button 1
button = new
button_icon = ${__distro_path_root}/Distro_Specific/icons/user.svg
button_text = 
button_tooltip = Application Launcher
button_lclick_command = rofi-launcher
button_rclick_command = rofi-runner
button_mclick_command = 
button_uwheel_command = 
button_dwheel_command = 
button_font = JetBrainsMono Nerd Font 10
button_font_color = #${foreground} 100
button_padding = 5 0
button_background_id = 2
button_centered = 0
button_max_icon_size = 24

#-------------------------------------
# Tooltip
tooltip_show_timeout = 0.5
tooltip_hide_timeout = 0.1
tooltip_padding = 10 10
tooltip_background_id = 1
tooltip_font_color = #${foreground} 100
tooltip_font = JetBrainsMono Nerd Font 10
EOF
}

create_geany_file(){
	tee "$HOME/.config/geany/colorschemes/${_style}.conf" << EOF >/dev/null
[theme_info]
name=${_style}
description=${_style} theme from ${wallpaper_are}
compat=1.22;1.23;1.23.1;1.24

[named_colors]
color0=#${color0}
color1=#${color1}
color2=#${color2}
color3=#${color3}
color4=#${color4}
color5=#${color5}
color6=#${color6}
color7=#${color7}
color8=#${color8}
color9=#${color9}
color10=#${color10}
color11=#${color11}
color12=#${color12}
color13=#${color13}
color14=#${color14}
color15=#${color15}

[named_styles]
#### General styling
default=color6;color0;false;false
error=color11;;false;false
margin_line_number=color3;color0;false;false
margin_folding=color2;color0;false;false
fold_symbol_highlight=color0

selection=0x0;color2;false;true
current_line=0x0;color1;true;false
caret=color4;0x0;false;false
indicator_error=color11

brace_good=color6;color10;true;false
brace_bad=color6;color11;true;false
indent_guide=color3;0x0;false;false
white_space=color3;color0;true;true

marker_line=color1;color1;false;false
marker_search=0x0;color10;false;false
marker_mark=color1;color1;false;false
marker_translucency=1;1;false;false

folding_style=1;1
folding_horiz_line=0;0;false;false

### Programing languages
# General Syntax highlight
comment=color3
comment_doc=comment,bold
comment_line=comment
comment_line_doc=comment
comment_doc_keyword=color10
comment_doc_keyword_error=color11;;true;true

number=color15
number_1=number
number_2=number

type=color7
class=type
function=color8
parameter=function

keyword=color9
keyword_1=keyword
keyword_2=keyword
keyword_3=keyword
keyword_4=keyword

identifier=default
identifier_1=identifier
identifier_2=identifier
identifier_3=identifier
identifier_4=identifier

string=color14
string_1=string
string_2=string
string_3=default
string_4=default
string_eol=string,italic
character=string
backticks=string
here_doc=string

scalar=string_2
label=color8,bold
preprocessor=color10
regex=color13
operator=default
decorator=color12
other=default

# Markup-type languages
tag=color9
tag_unknown=tag
tag_end=tag
attribute=color7
attribute_unknown=attribute
value=color12
entity=default
strong=entity,bold
emphasis=entity,italic
ulist_item=tag
olist_item=tag
blockquote=attribute
strikeout=tag_unknown
hrule=tag_unknown
link=color13
code=blockquote
codebk=blockquote

# CSS Language specific
id=color15
pseudoclass=color14
pseudoelement=color14
unknown_pseudoclass=color11
unknown_identifier=default
doublestring=string
singlestring=string
variable=color12
important=color11
directive=color10
extended_identifier=color13
extended_pseudoclass=extended_identifier
extended_pseudoelement=extended_identifier
media=color15

# Diff
line_added=color14
line_removed=color11
line_changed=color13
EOF
}

create_kitty_file(){
	tee "$HOME/.config/kitty/themes/${_style}.conf" << EOF >/dev/null
# ============================
# ========== Colors ==========
# ============================

foreground            #${foreground}
background            #${background}
cursor                #${cursor}

selection_foreground  #${background}
selection_background  #${foreground}

active_border_color   #${color7}
inactive_border_color #${color8}
bell_border_color     #${color8}

color0  #${color0}
color1  #${color1}
color2  #${color2}
color3  #${color3}
color4  #${color4}
color5  #${color5}
color6  #${color6}
color7  #${color7}
color8  #${color8}
color9  #${color9}
color10 #${color10}
color11 #${color11}
color12 #${color12}
color13 #${color13}
color14 #${color14}
color15 #${color15}

active_tab_foreground   #${color2}
active_tab_background   #${background}
active_tab_font_style   normal

inactive_tab_foreground #${foreground}
inactive_tab_background #${background}

# vim:ft=conf	
EOF
}

create_alacritty_file(){
	tee "$HOME/.config/alacritty/colorschemes/${_style}.yml" << EOF >/dev/null
colors:
  # Default colors
  primary:
    background: "0x${background}"
    foreground: "0x${foreground}"

    dim_foreground:    "0x${color8}"
    bright_foreground: "0x${color12}"
    dim_background:    "0x${color8}"
    bright_background: "0x${background}"

  # Cursor colors
  # cursor:
    # text:   "0x${foreground}"
    # cursor: "0x${background}"

  # Normal colors
  normal:
    black:   "0x${color0}"
    red:     "0x${color1}"
    green:   "0x${color2}"
    yellow:  "0x${color3}"
    blue:    "0x${color4}"
    magenta: "0x${color5}"
    cyan:    "0x${color6}"
    white:   "0x${color7}"

  # Bright colors
  bright:
    black:   "0x${color8}"
    red:     "0x${color9}"
    green:   "0x${color10}"
    yellow:  "0x${color11}"
    blue:    "0x${color12}"
    magenta: "0x${color13}"
    cyan:    "0x${color14}"
    white:   "0x${color15}"

  # Dim colors
  dim:
    black:   "0x${color0}"
    red:     "0x${color1}"
    green:   "0x${color2}"
    yellow:  "0x${color3}"
    blue:    "0x${color4}"
    magenta: "0x${color5}"
    cyan:    "0x${color6}"
    white:   "0x${color7}"
EOF
}

create_Xresources_file(){
	tee "$HOME/.config/x11/Xresources.d/themes/${_style}" << EOF >/dev/null
! X colors.
! Generated by 'wal'
*foreground:        #${foreground}
*background:        #${background}
*.foreground:       #${foreground}
*.background:       #${background}
emacs*foreground:   #${foreground}
emacs*background:   #${background}
URxvt*foreground:   #${foreground}
XTerm*foreground:   #${foreground}
UXTerm*foreground:  #${foreground}
URxvt*background:   [#${alpha}]#${background}
XTerm*background:   #${background}
UXTerm*background:  #${background}
URxvt*cursorColor:  #${cursor}
XTerm*cursorColor:  #${cursor}
UXTerm*cursorColor: #${cursor}
URxvt*borderColor:  [#${alpha}]#${background}

! Colors 0-15.
*.color0: #${color0}
*color0:  #${color0}
*.color1: #${color1}
*color1:  #${color1}
*.color2: #${color2}
*color2:  #${color2}
*.color3: #${color3}
*color3:  #${color3}
*.color4: #${color4}
*color4:  #${color4}
*.color5: #${color5}
*color5:  #${color5}
*.color6: #${color6}
*color6:  #${color6}
*.color7: #${color7}
*color7:  #${color7}
*.color8: #${color8}
*color8:  #${color8}
*.color9: #${color9}
*color9:  #${color9}
*.color10: #${color10}
*color10:  #${color10}
*.color11: #${color11}
*color11:  #${color11}
*.color12: #${color12}
*color12:  #${color12}
*.color13: #${color13}
*color13:  #${color13}
*.color14: #${color14}
*color14:  #${color14}
*.color15: #${color15}
*color15:  #${color15}

! Black color that will not be affected by bold highlighting.
*.color66: #${color0}
*color66:  #${color0}

! Xclock colors.
XClock*foreground: #${foreground}
XClock*background: #${background}
XClock*majorColor:  rgba:${color15_xrgba}
XClock*minorColor:  rgba:${color15_xrgba}
XClock*hourColor:   rgba:${color15_xrgba}
XClock*minuteColor: rgba:${color15_xrgba}
XClock*secondColor: rgba:${color15_xrgba}

! Set depth to make transparency work.
URxvt*depth: 32
EOF
}

dynamic_check_theme_files(){
	
	GLOBALDYNAMICBLOBPATH="${__distro_path_all_distro_themes}/dynamic_theme"
	
	if [ ! -d "$gtk_theme_path/dynamic" ];then
		mkdir -p "$gtk_theme_path/dynamic"
		cp -r "${GLOBALDYNAMICBLOBPATH}"/themes/* "$gtk_theme_path" || show_em "failed to cp -r \"${GLOBALDYNAMICBLOBPATH}\" \"${gtk_theme_path}\""
	fi
	
	if [ ! -d "$gtk_icon_path/dynamic" ];then
		mkdir -p "$gtk_icon_path/dynamic"
		cp -r "${GLOBALDYNAMICBLOBPATH}"/icons/* "$gtk_icon_path" || show_em "failed to cp -r \"${GLOBALDYNAMICBLOBPATH}\" \"${gtk_icon_path}\""
	fi
}

gtk_theme_builder(){
	gtk_theme_path="$HOME/.themes"
	gtk_icon_path="$HOME/.icons"
	gtk_templates_path="${__distro_path_all_distro_themes}/dynamic_theme"
	gtk_templates_path_tmp_dir="${temp_theme_file_dir}/dynamic_theme_templates"

	if [ "$current_mode_are" = "dynamic" ];then
		dynamic_check_theme_files
	fi

	if [ ! -d "$gtk_templates_path_tmp_dir" ];then
		mkdir -p "$gtk_templates_path_tmp_dir"
	fi

	cp -r "${gtk_templates_path}"/gtk-icons "$gtk_templates_path_tmp_dir"

tee "$gtk_theme_path"/dynamic/gtk-2.0/gtkrc << EOF >/dev/null 2>&1
#modded Numix gtkrc

gtk-color-scheme = "bg_color:#${color0}
color0:#${color0}
color1:#${color1}
color2:#${color2}
color3:#${color3}
color4:#${color4}
color5:#${color5}
color6:#${color6}
color7:#${color7}
color8:#${color8}
color9:#${color9}
color10:#${color10}
color11:#${color11}
color12:#${color12}
color13:#${color13}
color14:#${color14}
color15:#${color15}
text_color:#${color15}
selected_bg_color:#${active}
selected_fg_color:#${color15}
tooltip_bg_color:#${color0}
tooltip_fg_color:#${color15}
titlebar_bg_color:#${color0}
titlebar_fg_color:#${color15}
menu_bg_color:#${color0}
menu_fg_color:#${color15}
link_color:#${active}"
gtk-auto-mnemonics	= 1

# Default Style
# DO --NOT-- CHANGE ACTIVE
# IT's THE COLOR THAT WPGTK REPLACES
# FEEL FREE TO MODIFY EVERYTHING ELSE IN gtkrc.base

style "murrine-default" {
	GtkArrow::arrow-scaling= 0.6

	GtkButton::child-displacement-x = 0
	GtkButton::child-displacement-y = 0

	GtkButton::default-border = { 0, 0, 0, 0 }

	GtkButtonBox::child-min-height = 26

	GtkCheckButton::indicator-size = 16

	# The following line hints to gecko (and possibly other appliations)
	# that the entry should be drawn transparently on the canvas.
	# Without this, gecko will fill in the background of the entry.
	GtkEntry::honors-transparent-bg-hint = 1
	GtkEntry::state-hint = 0

	GtkExpander::expander-size = 16

	GtkImage::x-ayatana-indicator-dynamic = 1

	GtkMenu::horizontal-padding = 0
	GtkMenu::vertical-padding = 0

	GtkMenuBar::internal-padding = 0
	GtkMenuBar::window-dragging = 1

	GtkMenuItem::arrow-scaling= 0.5

	GtkPaned::handle-size = 1

	GtkProgressBar::min-horizontal-bar-height = 12
	GtkProgressBar::min-vertical-bar-width = 12

	GtkRange::trough-border = 0
	GtkRange::slider-width = 8
	GtkRange::stepper-size = 12
	GtkRange::stepper_spacing = 0
	GtkRange::trough-under-steppers = 1

	GtkScale::slider-length = 16
	GtkScale::slider-width = 16
	GtkScale::trough-side-details = 1

	GtkScrollbar::activate-slider = 1
	GtkScrollbar::has-backward-stepper = 0
	GtkScrollbar::has-forward-stepper = 0
	GtkScrollbar::has-secondary-backward-stepper = 0
	GtkScrollbar::has-secondary-forward-stepper = 0
	GtkScrollbar::min-slider-length = 80
	GtkScrollbar::slider-width = 8
	GtkScrollbar::trough-border = 0

	GtkScrolledWindow::scrollbar-spacing = 0
	GtkScrolledWindow::scrollbars-within-bevel = 1

	GtkSeparatorMenuItem::horizontal-padding = 0

	GtkToolbar::internal-padding = 0

	GtkTreeView::expander-size = 11
	GtkTreeView::vertical-separator = 0

	GtkWidget::focus-line-width = 1
	# The following line prevents the Firefox tabs
	# from jumping a few pixels when you spawn a new tab
	GtkWidget::focus-padding = 0

	GtkWidget::wide-separators = 1
	GtkWidget::separator-width = 1
	GtkWidget::separator-height = 1

	GtkWindow::resize-grip-height = 0
	GtkWindow::resize-grip-width = 0

	WnckTasklist::fade-overlay-rect = 0

	GnomeHRef::link_color = @link_color
	GtkHTML::link-color = @link_color
 	GtkIMHtmlr::hyperlink-color = @link_color
	GtkIMHtml::hyperlink-color = @link_color
	GtkWidget::link-color = @link_color
	GtkWidget::visited-link-color = @text_color

	GtkToolbar::shadow-type = GTK_SHADOW_NONE # Makes toolbars flat and unified
	GtkMenuBar::shadow-type = GTK_SHADOW_NONE # Makes menubars flat and unified

	xthickness = 1
	ythickness = 1

	fg[NORMAL] = @text_color
	fg[PRELIGHT] = @text_color
	fg[SELECTED] = @selected_fg_color
	fg[ACTIVE] = @text_color
	fg[INSENSITIVE] = mix (0.5, @bg_color, @text_color)

	bg[NORMAL] = @bg_color
	bg[PRELIGHT] = shade (1.02, @bg_color)
	bg[SELECTED] = @selected_bg_color
	bg[ACTIVE] = @bg_color
	bg[INSENSITIVE] = @bg_color

	base[NORMAL] = shade(0.85, @color0)
	base[PRELIGHT] = shade (0.85, @color0)
	base[SELECTED] = @selected_bg_color
	base[ACTIVE] = @selected_bg_color
	base[INSENSITIVE] = shade (0.85, @bg_color)

	text[NORMAL] = @text_color
	text[PRELIGHT] = @text_color
	text[SELECTED] = @selected_fg_color
	text[ACTIVE] = @selected_fg_color
	text[INSENSITIVE] = mix (0.5, @bg_color, @text_color)

	engine "murrine" {
		animation = FALSE
		arrowstyle = 1 # 0 = normal arrows, 1 = filled arrows
		border_shades = { 1.0, 1.0 } # gradient to draw on border
		colorize_scrollbar = TRUE
		comboboxstyle = 0 # 0 = normal combobox, 1 = colorized combobox below arrow
		contrast = 0.0 # overal contrast with borders
		focusstyle = 1 # 0 = none, 1 = grey dotted, 2 = colored with fill, 3 = colored glow
		glazestyle = 0 # 0 = flat highlight, 1 = curved highlight, 2 = concave, 3 = top curved highlight, 4 = beryl highlight
		glowstyle = 0 # 0 = glow on top, 1 = glow on bottom, 2 = glow on top and bottom, 3 = glow on middle vertically, 4 = glow on middle horizontally, 5 = glow on all sides
		glow_shade = 1.0 # amount of glow
		gradient_shades = { 1.0, 1.0, 1.0, 1.0 } # gradient to draw on widgets
		highlight_shade = 1.0 # amount of highlight
		lightborder_shade = 1.0 # amount of inset light border
		lightborderstyle = 1 # 0 = lightborder on top side, 1 = lightborder on all sides
		listviewheaderstyle = 0 # 0 = flat, 1 = glassy, 2 = raised
		listviewstyle = 0 # 0 = none, 1 = dotted, 2 = line
		menubaritemstyle = 0 # 0 = menuitem look, 1 = button look
		menubarstyle = 0 # 0 = flat, 1 = glassy, 2 = gradient, 3 = striped
		menuitemstyle = 0 # 0 = flat, 1 = glassy, 2 = striped
		menustyle = 0 # 0 = none, 1 = vertical striped
		progressbarstyle = 0 # 0 = none, 1 = diagonal striped, 2 = vertical striped
		reliefstyle = 0 # 0 = flat, 1 = inset, 2 = shadow, 3 = shadow with gradient, 4 = stronger shadow with gradient
		roundness = 0 # roundness of widgets
		scrollbarstyle = 0 # 0 = none, 1 = circles, 2 = handles, 3 = diagonal stripes, 4 = diagonal stripes and handles, 5 = horizontal stripes, 6 = horizontal stripes and handles
		sliderstyle = 0 # 0 = none, 1 = handles
		stepperstyle = 1 # 0 = standard, 1 = integrated stepper handles
		toolbarstyle = 0 # 0 = flat, 1 = glassy, 2 = gradient
   }
}

style "murrine-wide" {
	xthickness = 2
	ythickness = 2
}

style "murrine-wider" {
	xthickness = 3
	ythickness = 3
}

style "murrine-thin" {
	xthickness = 0
	ythickness = 0
}

# Notebook

style "murrine-notebook-bg" {
	bg[NORMAL] = @bg_color
	bg[ACTIVE] = shade (0.70, @bg_color)
}

style "murrine-notebook" = "murrine-notebook-bg" {
	xthickness = 2
	ythickness = 2

	engine "murrine" {
		roundness = 0
	}
}

# Various Standard Widgets

style "murrine-button"  = "murrine-wider" {
	bg[NORMAL] = shade (1.3, @bg_color)
	bg[PRELIGHT] = shade (0.80, @selected_bg_color)
	bg[ACTIVE] = shade (1.00, @selected_bg_color)
	bg[INSENSITIVE] = shade (0.85, @bg_color)

  	engine "murrine" {
	}
}

style "murrine-scrollbar" {
	bg[NORMAL] = @bg_color
	bg[PRELIGHT] = mix (0.31, @text_color, @bg_color)
	bg[ACTIVE] = @selected_bg_color

	engine "murrine" {
		roundness = 0
		contrast = 0.0
		border_shades = { 0.9, 0.9 }
		trough_shades = { 0.97, 0.97 }
		trough_border_shades = { 1.0, 1.0 }
	}
}

style "murrine-overlay-scrollbar" {
	bg[ACTIVE] = shade (0.8, @bg_color)
	bg[INSENSITIVE] = shade (0.97, @bg_color)

	base[SELECTED] = shade (0.6, @bg_color)
	base[INSENSITIVE] = shade (0.85, @bg_color)
}

style "murrine-scale" = "murrine-thin" {
	bg[NORMAL] = @bg_color
	bg[ACTIVE] = @bg_color
	bg[SELECTED] = @selected_bg_color
	bg[INSENSITIVE] = shade (0.95, @bg_color)

	engine "murrine" {
		roundness = 8
		gradient_shades = { 1.08, 1.08, 1.08, 1.08 }
		border_shades = { 1.0, 1.0 }
		trough_shades = { 1.08, 1.08 }
		trough_border_shades = { 0.8, 0.8 }
	}
}

style "murrine-progressbar" = "murrine-thin" {
	bg[NORMAL] = @bg_color
	bg[ACTIVE] = shade(0.60, @bg_color)

	fg[PRELIGHT] = @selected_fg_color

	engine "murrine" {
		roundness = 0
		border_shades = { 1.2, 1.2 }
		trough_border_shades = { 0.8, 0.8 }
	}
}

style "murrine-treeview-header" = "murrine-button" {
  	engine "murrine" {
		roundness = 0
	}
}

style "murrine-treeview" {
  	engine "murrine" {
		roundness = 0
	}
}

style "murrine-frame-title" {
	fg[NORMAL] = lighter (@text_color)
}

style "murrine-tooltips" {
	xthickness = 5
	ythickness = 5

	bg[NORMAL] = @tooltip_bg_color
	bg[SELECTED] = @tooltip_bg_color

	fg[NORMAL] = @text_color

	engine "murrine" {
		textstyle = 0
		roundness = 0
		rgba = FALSE
	}
}

style "murrine-spinbutton" = "murrine-button" {
	engine "murrine" {
	}
}

style "murrine-radiocheck" = "murrine-default" {
	bg[SELECTED] = @bg_color

	text[NORMAL] = @selected_bg_color
	text[PRELIGHT] = @selected_bg_color
}

style "murrine-entry" = "murrine-wider" {
        bg[SELECTED] = @selected_bg_color

	engine "murrine" {
		border_shades = { 1.15, 1.15 }
	}
}

style "metacity-frame" = "murrine-default" {
	bg[SELECTED] = @selected_bg_color
}

style "murrine-statusbar" { 
  bg[NORMAL] = @bg_color
}
style "murrine-comboboxentry" = "murrine-entry" { }
style "murrine-hscale" = "murrine-scale" { }
style "murrine-vscale" = "murrine-scale" { }
style "murrine-hscrollbar" = "murrine-scrollbar" { }
style "murrine-vscrollbar" = "murrine-scrollbar" { }

# Menus

style "murrine-menu" = "murrine-thin" {
	bg[NORMAL] = shade(0.8, @menu_bg_color)
	bg[PRELIGHT] = @selected_bg_color
	bg[SELECTED] = @selected_bg_color
	bg[ACTIVE] = @menu_bg_color
	bg[INSENSITIVE] = @menu_bg_color

	fg[NORMAL] = @menu_fg_color
	fg[PRELIGHT] = @selected_fg_color
	fg[SELECTED] = @selected_fg_color
	fg[ACTIVE] = @selected_fg_color
	fg[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)

	text[NORMAL] = @menu_fg_color
	text[PRELIGHT] = @selected_fg_color
	text[SELECTED] = @selected_fg_color
	text[ACTIVE] = @selected_fg_color
	text[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)

	engine "murrine" {
		roundness = 0
	}
}

style "murrine-menu-item" = "murrine-wider" {
	bg[PRELIGHT] = @selected_bg_color
	bg[SELECTED] = @selected_bg_color
	bg[ACTIVE] = @selected_bg_color

	fg[NORMAL] = @menu_fg_color # Fix for XFCE menu text
	fg[PRELIGHT] = @selected_fg_color
	fg[SELECTED] = @selected_fg_color
	fg[ACTIVE] = @selected_fg_color
	fg[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)

	engine "murrine" {
		textstyle = 0
		border_shades = { 1.2, 1.2 }
	}
}

style "murrine-separator-menu-item" = "murrine-thin" { }

style "murrine-menubar" {
	bg[NORMAL] = @bg_color
	bg[PRELIGHT] =  mix (0.21, @text_color, @bg_color)
	bg[SELECTED] =  mix (0.21, @text_color, @bg_color)
	bg[ACTIVE] = shade (0.9, @bg_color)
	bg[INSENSITIVE] = @bg_color

	fg[NORMAL] = @text_color
	fg[PRELIGHT] = shade (1.08, @text_color)
	fg[SELECTED] = shade (1.08, @text_color)
	fg[ACTIVE] = @text_color
	fg[INSENSITIVE] = mix (0.5, @bg_color, @text_color)

	engine "murrine" {
		roundness = 0
	}
}

style "murrine-menubaritem" {
	bg[NORMAL] = @bg_color
	bg[PRELIGHT] =  @selected_bg_color
	bg[SELECTED] =  @selected_bg_color
	bg[ACTIVE] = shade (0.9, @bg_color)
	bg[INSENSITIVE] = @bg_color

	fg[NORMAL] = @text_color
	fg[PRELIGHT] = shade (1.08, @text_color)
	fg[SELECTED] = shade (1.08, @text_color)
	fg[ACTIVE] = @text_color
	fg[INSENSITIVE] = mix (0.5, @bg_color, @text_color)

	engine "murrine" {
		roundness = 0
	}
}

# Toolbars

style "murrine-toolbar" = "murrine-thin" {
	bg[NORMAL] = @bg_color
	bg[PRELIGHT] = shade (1.02, @bg_color)
	bg[SELECTED] = @selected_bg_color
	bg[ACTIVE] = shade (0.9, @bg_color)
	bg[INSENSITIVE] = @bg_color

	fg[NORMAL] = @text_color
	fg[PRELIGHT] = @text_color
	fg[SELECTED] = @selected_fg_color
	fg[ACTIVE] = @text_color
	fg[INSENSITIVE] = mix (0.5, @bg_color, @text_color)

	engine "murrine" {
	}
}

style "murrine-toolbutton" = "murrine-button" {
	bg[NORMAL] = shade (1.08, @bg_color)
	bg[PRELIGHT] = shade (1.10, @bg_color)
	bg[SELECTED] = @selected_bg_color
	bg[ACTIVE] = shade (0.95, @bg_color)
	bg[INSENSITIVE] = shade (0.85, @bg_color)

	fg[NORMAL] = @text_color
	fg[PRELIGHT] = @text_color
	fg[SELECTED] = @selected_fg_color
	fg[ACTIVE] = @text_color
	fg[INSENSITIVE] = mix (0.5, @bg_color, @text_color)

	engine "murrine" {
	}
}

class "GtkToolbar" style "murrine-toolbar"
class "GtkHandleBox" style "murrine-toolbar"
widget_class "*Toolbar*.*Separator*" style "murrine-toolbar"

# Panels

style "murrine-panel" = "murrine-thin" {
	xthickness = 2

	bg[NORMAL] = @menu_bg_color
	bg[PRELIGHT] =  shade(0.8, @selected_bg_color)
	bg[SELECTED] =  @selected_bg_color
	bg[ACTIVE] = @selected_bg_color
	bg[INSENSITIVE] = @menu_bg_color

	fg[NORMAL] = @text_color
	fg[PRELIGHT] = @text_color
	fg[SELECTED] = @text_color
	fg[ACTIVE] = @text_color
	fg[INSENSITIVE] = shade(0.8, @text_color)

	base[NORMAL] = @menu_bg_color
	base[PRELIGHT] =  mix (0.21, @text_color, @menu_bg_color)
	base[SELECTED] =  @selected_bg_color
	base[ACTIVE] = @selected_bg_color
	base[INSENSITIVE] = @menu_bg_color

	text[NORMAL] = @text_color
	text[PRELIGHT] = shade (1.08, @text_color)
	text[SELECTED] = shade (1.08, @text_color)
	text[ACTIVE] = @text_color
	text[INSENSITIVE] = mix (0.5, @menu_bg_color, @text_color)

	engine "murrine" {
		roundness = 0
		contrast = 0.0
	}
}

widget "*PanelWidget*" style "murrine-panel"
widget "*PanelApplet*" style "murrine-panel"
widget "*fast-user-switch*" style "murrine-panel"
widget "*CPUFreq*Applet*" style "murrine-panel"
widget "*indicator-applet*" style "murrine-panel"
class "PanelApp*" style "murrine-panel"
class "PanelToplevel*" style "murrine-panel"
widget_class "*PanelToplevel*" style "murrine-panel"
widget_class "*notif*" style "murrine-panel"
widget_class "*Notif*" style "murrine-panel"
widget_class "*Tray*" style "murrine-panel" 
widget_class "*tray*" style "murrine-panel"
widget_class "*computertemp*" style "murrine-panel"
widget_class "*Applet*Tomboy*" style "murrine-panel"
widget_class "*Applet*Netstatus*" style "murrine-panel"
widget "*gdm-user-switch-menubar*" style "murrine-panel"

style "bold-panel-item" {
	font_name = "Bold"

	engine "murrine" {
		roundness = 0
	}
}

widget "*Panel*MenuBar*" style "bold-panel-item"
widget "*gimmie*" style "bold-panel-item"

# widget_class "*Mail*" style "murrine-panel" # Disabled to fix Evolution bug
# class "*Panel*" style "murrine-panel" # Disabled to fix bug

# XFCE Styles

style "workspace-switcher" = "murrine-panel" {
	bg[SELECTED] = @selected_bg_color
}

style "xfce-header" {
	bg[NORMAL] = shade (0.9, @bg_color)
	base[NORMAL] = shade (1.18, @bg_color)
}

style "xfdesktop-windowlist" {
	bg[NORMAL] = @bg_color
	fg[INSENSITIVE] = shade (0.95, @bg_color)
	text[INSENSITIVE] = shade (0.95, @bg_color)
}

style "xfdesktop-icon-view" {
	XfdesktopIconView::label-alpha = 0
	XfdesktopIconView::selected-label-alpha = 60
	XfdesktopIconVIew::ellipsize-icon-labels = 1

	base[NORMAL] = @selected_bg_color
	base[SELECTED] = @selected_bg_color
	base[ACTIVE] = @selected_bg_color

	fg[NORMAL] = @selected_fg_color
	fg[SELECTED] = @selected_fg_color
	fg[ACTIVE] = @selected_fg_color

	engine "murrine" {
		textstyle = 5
		text_shade = 0.05
	}
}

style "xfwm-tabwin" {
	Xfwm4TabwinWidget::border-width = 0
	Xfwm4TabwinWidget::icon-size = 64

	bg[NORMAL] = @menu_bg_color
	fg[NORMAL] = @menu_fg_color

	engine "murrine" {
		focusstyle = 0
	}
}

style "xfsm-logout" {
	bg[NORMAL] = @menu_bg_color
	bg[ACTIVE] = @menu_bg_color
	bg[PRELIGHT] = shade (1.1, @menu_bg_color)
	bg[SELECTED] = shade (0.5, @menu_bg_color)
	bg[INSENSITIVE] = shade (1.3, @menu_bg_color)

	fg[NORMAL] = @menu_fg_color
	fg[PRELIGHT] = @menu_fg_color

	text[NORMAL] = @menu_fg_color

	engine "murrine" {
	}
}

style "xfsm-logout-button" {
	bg[NORMAL] = shade (1.2, @menu_bg_color)
	bg[PRELIGHT] = shade (1.4, @menu_bg_color)

	engine "murrine" {
	}
}

widget "*WnckPager*" style "workspace-switcher"

widget "*Xfce*Panel*" style "murrine-panel"
class "*Xfce*Panel*" style "murrine-panel"

# Thunar Styles

style "sidepane" {
	base[NORMAL] = @bg_color
	base[INSENSITIVE] = shade(0.90, @bg_color)
	bg[NORMAL] = @bg_color
	text[NORMAL] = @text_color
}

widget_class "*ThunarShortcutsView*" style "sidepane"
widget_class "*ThunarTreeView*" style "sidepane"
widget_class "*ThunarLocationEntry*" style "murrine-entry"

# Gtk2 Open-File Dialog

widget_class "*GtkFileChooserWidget.GtkFileChooserDefault.GtkVBox.GtkHPaned.GtkVBox.GtkScrolledWindow.GtkTreeView*" style "sidepane"
widget_class "*GtkFileChooserWidget.GtkFileChooserDefault.GtkVBox.GtkHPaned.GtkVBox.GtkScrolledWindow.<GtkTreeView>.<GtkButton>" style "murrine-treeview-header"

# Google Chrome/Chromium Styles (requires 9.0.597 or newer)

style "chromium-toolbar-button" {
	engine "murrine" {
		roundness = 2
		textstyle = 0
	}
}

style "chrome-gtk-frame" {
	ChromeGtkFrame::frame-color = @titlebar_bg_color
	ChromeGtkFrame::inactive-frame-color = @titlebar_bg_color

	ChromeGtkFrame::frame-gradient-size = 0
	ChromeGtkFrame::frame-gradient-color = @titlebar_bg_color

	ChromeGtkFrame::incognito-frame-color = @titlebar_bg_color
	ChromeGtkFrame::incognito-inactive-frame-color = @titlebar_bg_color

	ChromeGtkFrame::incognito-frame-gradient-size = 0
	ChromeGtkFrame::incognito-frame-gradient-color = @titlebar_bg_color

	ChromeGtkFrame::scrollbar-trough-color = @bg_color
	ChromeGtkFrame::scrollbar-slider-normal-color =  mix (0.21, @text_color, @bg_color)
	ChromeGtkFrame::scrollbar-slider-prelight-color =  mix (0.31, @text_color, @bg_color)
}

class "ChromeGtkFrame" style "chrome-gtk-frame"

widget_class "*Chrom*Button*" style "chromium-toolbar-button"

# General Styles

class "GtkWidget" style "murrine-default"

class "GtkFrame" style "murrine-wide"
class "MetaFrames" style "metacity-frame"
class "GtkWindow" style "metacity-frame"

class "GtkSeparator" style "murrine-wide"
class "GtkCalendar" style "murrine-wide"

class "GtkSpinButton" style "murrine-spinbutton"

class "GtkScale" style "murrine-scale"
class "GtkVScale" style "murrine-vscale"
class "GtkHScale" style "murrine-hscale"
class "GtkScrollbar" style "murrine-scrollbar"
class "GtkVScrollbar" style "murrine-vscrollbar"
class "GtkHScrollbar" style "murrine-hscrollbar"

class "GtkRadio*" style "murrine-radiocheck"
class "GtkCheck*" style "murrine-radiocheck"

class "GtkEntry" style "murrine-entry"

widget_class "*<GtkNotebook>" style "murrine-notebook"
widget_class "*<GtkNotebook>*<GtkEventBox>" style "murrine-notebook-bg"
widget_class "*<GtkNotebook>*<GtkDrawingArea>" style "murrine-notebook-bg"
widget_class "*<GtkNotebook>*<GtkLayout>" style "murrine-notebook-bg"
widget_class "*.GtkNotebook.*.GtkViewport" style "murrine-notebook"

widget_class "*<GtkButton>" style "murrine-button"
widget_class "*<GtkStatusbar>*" style "murrine-statusbar"
widget_class "*<GtkProgress>" style "murrine-progressbar"
widget_class "*<GtkProgressBar>" style "murrine-progressbar"

widget_class "*<GtkComboBoxEntry>*" style "murrine-comboboxentry"
widget_class "*<GtkCombo>*" style "murrine-comboboxentry"

widget_class "*<GtkMenu>*" style "murrine-menu"
widget_class "*<GtkMenuItem>*" style "murrine-menu-item"
widget_class "*<GtkSeparatorMenuItem>*" style "murrine-separator-menu-item"
widget_class "*Menu*.*Sepa*"  style "murrine-separator-menu-item"
widget_class "*<GtkMenuBar>*" style "murrine-menubar"
widget_class "*<GtkMenuBar>*<GtkMenuItem>*" style "murrine-menubaritem"

widget_class "*GtkToolButton*" style "murrine-toolbutton"
widget_class "*GtkToggleToolButton*" style "murrine-toolbutton"
widget_class "*GtkMenuToolButton*" style "murrine-toolbutton"
widget_class "*GtkToolbar*Button" style "murrine-toolbutton"

widget_class "*.<GtkFrame>.<GtkLabel>" style "murrine-frame-title"

widget_class "*.<GtkTreeView>*" style "murrine-treeview"
widget_class "*.<GtkTreeView>.<GtkButton>" style "murrine-treeview-header"
widget_class "*.<GtkCTree>.<GtkButton>" style "murrine-treeview-header"
widget_class "*.<GtkList>.<GtkButton>" style "murrine-treeview-header"
widget_class "*.<GtkCList>.<GtkButton>" style "murrine-treeview-header"

widget "gtk-tooltip*" style "murrine-tooltips"

widget_class "*<GtkScrolledWindow>*<OsScrollbar>" style "murrine-overlay-scrollbar"

# Workarounds and Non-Standard Styling

style "text-is-fg-color-workaround" {
	text[NORMAL] = @text_color
	text[PRELIGHT] = @text_color
	text[SELECTED] = @selected_fg_color
	text[ACTIVE] = @text_color
	text[INSENSITIVE] = mix (0.5, @bg_color, @text_color)
}

widget_class "*.<GtkComboBox>.<GtkCellView>" style "text-is-fg-color-workaround"

style "fg-is-text-color-workaround" {
	fg[NORMAL] = @text_color
	fg[PRELIGHT] = @text_color
	fg[ACTIVE] = @selected_fg_color
	fg[SELECTED] = @selected_fg_color
	fg[INSENSITIVE] = darker (@text_color)
}

widget_class "*<GtkListItem>*" style "fg-is-text-color-workaround"
widget_class "*<GtkCList>" style "fg-is-text-color-workaround"
widget_class "*<EelEditableLabel>" style "fg-is-text-color-workaround"

style "murrine-evo-new-button-workaround" {
	engine "murrine" {
		toolbarstyle = 0
	}
}

widget_class "EShellWindow.GtkVBox.BonoboDock.BonoboDockBand.BonoboDockItem*" style "murrine-evo-new-button-workaround"

style "inkscape-toolbar-fix" {
	engine "murrine" {
		gradient_shades = { 1.0, 1.0, 1.0, 1.0 }
		highlight_shade = 1.0
	}
}

#widget "*GtkHandleBox*" style "inkscape-toolbar-fix"
#widget "*HandleBox*CommandsToolbar*" style "inkscape-toolbar-fix"
#widget "*HandleBox*SnapToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*SelectToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*NodeToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*TweakToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*ZoomToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*StarToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*RectToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*3DBoxToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*ArcToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*SpiralToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*PencilToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*PenToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*CalligraphyToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*EraserToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*LPEToolToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*DropperToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*ConnectorToolbar*" style "inkscape-toolbar-fix"
widget "*HandleBox*PaintbucketToolbar*" style "inkscape-toolbar-fix"

# Performance Fixes

style "performance-fix" {
	engine "murrine" {
		textstyle = 0
	}
}

widget_class "*gtkmm__GtkWindow*" style "performance-fix" # Inkscape
widget_class "*GimpDisplayShell*" style "performance-fix" # Gimp
widget_class "*GimpToolbox*" style "performance-fix"
widget_class "*GimpMenuDock*" style "performance-fix"
widget "*OOoFixed*" style "performance-fix" # Openoffice/Libreoffice
widget_class "*MozContainer*" style "performance-fix" # Firefox (Not sure if this one does anything though.)

widget_class "*XfceHeading*" style "xfce-header"
widget_class "*XfceDesktop*" style "xfdesktop-windowlist"
widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"
widget "xfwm4-tabwin*" style "xfwm-tabwin"
widget_class "*XfsmLogoutDialog*" style "xfsm-logout"
widget_class "*XfsmLogoutDialog*GtkButton" style "xfsm-logout-button"
EOF

tee "$gtk_theme_path"/dynamic/gtk-3.0/gtk.css << EOF >/dev/null 2>&1

/* Default color scheme */
@define-color bg_color #${color0};
@define-color fg_color #${color15};
@define-color base_color #${color1};
@define-color text_color #${color15};
@define-color selected_bg_color #${active};
@define-color selected_fg_color #${color15};
@define-color tooltip_bg_color #${color0};
@define-color tooltip_fg_color #${color15};

/* colormap actually used by the theme, to be overridden in other css files */
@define-color theme_bg_color @bg_color;
@define-color theme_fg_color @fg_color;
@define-color theme_base_color @base_color;
@define-color theme_text_color @text_color;
@define-color theme_selected_bg_color @selected_bg_color;
@define-color theme_selected_fg_color @selected_fg_color;
@define-color theme_tooltip_bg_color @tooltip_bg_color;
@define-color theme_tooltip_fg_color @tooltip_fg_color;

/* shadow effects */
@define-color light_shadow #eeeeee;
@define-color dark_shadow #222222;

/* misc colors used by gtk+ */
@define-color info_fg_color white;
@define-color info_bg_color #BACF66;
@define-color warning_fg_color white;
@define-color warning_bg_color #E6A682;
@define-color question_fg_color white;
@define-color question_bg_color #74C47B;
@define-color error_fg_color white;
@define-color error_bg_color #E682C8;
@define-color link_color mix (@theme_selected_bg_color, black, 0.15);
@define-color success_color #53a93f;
@define-color warning_color #f57900;
@define-color error_color #cc0000;

/* widget colors*/
@define-color border_color #363D43;
@define-color button_normal_color #3F474A;
@define-color button_info_color #72B279;
@define-color button_default_active_color shade(@theme_selected_bg_color, 0.857);
@define-color entry_border_color shade(@theme_base_color, 0.9);
@define-color frame_border_bottom_color #E3E4E7;
@define-color sel_color #B98CD7;
@define-color switch_bg_color #C9CBCF;
@define-color panel_bg_color @bg_color;
@define-color panel_fg_color @fg_color;
@define-color borders #FAFAFA;
@define-color scrollbar_trough shade(@theme_base_color, 0.9);
@define-color scrollbar_slider_prelight mix(@scrollbar_trough, @theme_fg_color, 0.5);


/* osd */
@define-color osd_separator #49525B;
@define-color osd_fg #ABB4BD;
@define-color osd_bg #434A54;

/* window manager colors */
@define-color wm_bg @theme_bg_color;
@define-color wm_title_focused @theme_fg_color;
@define-color wm_title_unfocused @theme_text_color;
@define-color wm_border_focused @border_color;
@define-color wm_border_unfocused @border_color;

@import url("gtk-widgets.css");
@import url("gtk-widgets-assets.css");
@import url("unity.css");
@import url("widgets/button.css");
@import url("widgets/cell-row.css");
@import url("widgets/check-radio.css");
@import url("widgets/column-header.css");
@import url("widgets/calendar.css");
@import url("widgets/entry.css");
@import url("widgets/infobar.css");
@import url("widgets/menu.css");
@import url("widgets/notebook.css");
@import url("widgets/progress-scale.css");
@import url("widgets/scrollbar.css");
@import url("widgets/separator.css");
@import url("widgets/sidebar.css");
@import url("widgets/spinbutton.css");
@import url("widgets/spinner.css");
@import url("widgets/switch.css");
@import url("widgets/color-chooser.css");
@import url("widgets/toolbar.css");
@import url("widgets/header-bar.css");
@import url("widgets/osd.css");
@import url("widgets/csd.css");
@import url("widgets/combobox.css");
@import url("widgets/selection-mode.css");
EOF

tee "$gtk_theme_path"/dynamic/gtk-3.20/gtk.css << EOF >/dev/null 2>&1
/* Default color scheme */
@define-color color0 #${color0};
@define-color color1 #${color1};
@define-color color2 #${color2};
@define-color color3 #${color3};
@define-color color4 #${color4};
@define-color color5 #${color5};
@define-color color6 #${color6};
@define-color color7 #${color7};
@define-color color8 #${color8};
@define-color color9 #${color9};
@define-color color10 #${color10};
@define-color color11 #${color11};
@define-color color12 #${color12};
@define-color color13 #${color13};
@define-color color14 #${color14};
@define-color color15 #${color15};
@define-color selected_bg_color #${active};
@define-color bg_color mix(@color0, @color15, 0.12);
@define-color tooltip_bg_color mix(@color0, @color15, 0.04);
@define-color base_color mix(@color0, @color15, 0);
@define-color fg_color @color15;
@define-color text_color @color15;
@define-color selected_fg_color @color15;
@define-color tooltip_fg_color @color15;

/* colormap actually used by the theme, to be overridden in other css files */
@define-color theme_bg_color @bg_color;
@define-color theme_fg_color @fg_color;
@define-color theme_base_color @base_color;
@define-color theme_text_color @text_color;
@define-color theme_selected_bg_color @selected_bg_color;
@define-color theme_selected_fg_color @selected_fg_color;
@define-color theme_tooltip_bg_color @tooltip_bg_color;
@define-color theme_tooltip_fg_color @tooltip_fg_color;

/* shadow effects */
@define-color light_shadow #eeeeee;
@define-color dark_shadow #222222;

/* misc colors used by gtk+ */
@define-color info_fg_color @text_color;
@define-color info_bg_color @bg_color;
@define-color warning_fg_color @text_color;
@define-color warning_bg_color @bg_color;
@define-color question_fg_color @text_color;
@define-color question_bg_color @theme_selected_bg_color;
@define-color error_fg_color @text_color;
@define-color error_bg_color #f52400;
@define-color link_color mix (@theme_selected_bg_color, black, 0.15);
@define-color success_color #53a93f;
@define-color warning_color #f57900;
@define-color error_color #f52400;

/* widget colors*/
@define-color border_color shade(@theme_selected_bg_color, 0.2);
@define-color button_normal_color shade(@theme_bg_color, 1.20);
@define-color button_info_color @theme_selected_bg_color;
@define-color button_default_active_color @theme_selected_bg_color;
@define-color entry_border_color shade(@theme_base_color, 0.9);
@define-color frame_border_bottom_color shade(@bg_color, 0.8);
@define-color sel_color shade(@theme_selected_bg_color, 0.857);
@define-color switch_bg_color shade(@bg_color, 0.8);
@define-color panel_bg_color @bg_color;
@define-color panel_fg_color @fg_color;
@define-color borders shade(@theme_selected_bg_color, 0.857);
@define-color scrollbar_trough shade(@theme_base_color, 0.9);
@define-color scrollbar_slider_prelight mix(@scrollbar_trough, @theme_fg_color, 0.5);


/* osd */
@define-color osd_separator #49525B;
@define-color osd_fg #ABB4BD;
@define-color osd_bg #434A54;

/* window manager colors */
@define-color wm_bg @theme_bg_color;
@define-color wm_title_focused @theme_fg_color;
@define-color wm_title_unfocused @theme_text_color;
@define-color wm_border_focused @border_color;
@define-color wm_border_unfocused @border_color;

@import url("gtk-widgets.css");
@import url("unity.css");
@import url("widgets/button.css");
@import url("widgets/cell-row.css");
@import url("widgets/check-radio.css");
@import url("widgets/column-header.css");
@import url("widgets/calendar.css");
@import url("widgets/entry.css");
@import url("widgets/infobar.css");
@import url("widgets/menu.css");
@import url("widgets/notebook.css");
@import url("widgets/progress-scale.css");
@import url("widgets/scrollbar.css");
@import url("widgets/separator.css");
@import url("widgets/sidebar.css");
@import url("widgets/chrome.css");
@import url("widgets/spinbutton.css");
@import url("widgets/spinner.css");
@import url("widgets/switch.css");
@import url("widgets/color-chooser.css");
@import url("widgets/toolbar.css");
@import url("widgets/header-bar.css");
@import url("widgets/osd.css");
@import url("widgets/csd.css");
@import url("widgets/combobox.css");
@import url("widgets/selection-mode.css");
EOF

tee "$gtk_theme_path"/dynamic/openbox-3/themerc << EOF >/dev/null 2>&1
border.width: 0
padding.height: 5
window.label.text.justify: Center
window.client.padding.width: 0
window.handle.width: 0

menu.border.width: 0
menu.items.active.bg: Solid Flat
menu.items.active.bg.color: #${active}
menu.items.active.text.color: #${color15}
menu.items.bg: Flat Solid
menu.items.bg.color: #${color0}
menu.items.disabled.text.color: #c3c3c3
menu.items.font: shadow=n
menu.items.text.color: #${color15}
menu.overlap: 0
menu.separator.color: #${color0}
menu.title.bg: Solid Flat
menu.title.bg.color: #${color0}
menu.title.text.color: #${color15}
menu.title.text.font: shadow=n
menu.title.text.justify: Left

osd.bg: flat border vertical gradient
osd.bg.color: #${color0}
osd.bg.colorTo: #${color0}
osd.bg.border.color: #${active}
osd.border.color: #${active}
osd.border.width: 3
osd.label.bg: parentrelative
osd.label.text.color: #${color15}

window.active.border.color: #${active}
window.active.button.disabled.bg: Solid Flat
window.active.button.disabled.bg.color: #${active}
window.active.button.disabled.bg.border.color: #${active}
window.active.button.disabled.image.color: #${active}
window.active.button.hover.bg: Solid Flat
window.active.button.hover.bg.color: #${active}
window.active.button.hover.bg.border.color: #${active}
window.active.button.hover.image.color: #${inactive}
window.active.button.pressed.bg: Solid Flat
window.active.button.pressed.bg.color: #${active}
window.active.button.pressed.bg.border.color: #${active}
window.active.button.pressed.image.color: #${inactive}
Window.active.button.toggled.bg: Solid Flat
window.active.button.toggled.bg.color: #${active}
window.active.button.toggled.bg.border.color: #${active}
window.active.button.toggled.image.color: #${color15}
window.active.button.unpressed.bg: Solid Flat
window.active.button.unpressed.bg.color: #${active}
window.active.button.unpressed.bg.border.color: #${active}
window.active.button.unpressed.image.color: #${color15}
window.active.client.color: #${color0}
window.active.grip.bg: Solid Flat
window.active.grip.bg.color: #${color0}
window.active.handle.bg: Solid Flat
window.active.handle.bg.color: #4A848F
window.active.label.bg: Parentrelative
window.active.label.text.color: #${color15}
window.active.label.text.font: shadow=n
window.active.title.bg: Solid Flat
window.active.title.bg.color: #${active}

window.inactive.border.color: #${inactive}
window.inactive.button.disabled.bg: Solid Flat
window.inactive.button.disabled.bg.color: #${inactive}
window.inactive.button.disabled.bg.border.color: #${inactive}
window.inactive.button.disabled.image.color: #${inactive}
window.inactive.button.hover.bg: Solid Flat
window.inactive.button.hover.bg.color: #${inactive}
window.inactive.button.hover.bg.border.color: #${inactive}
window.inactive.button.hover.image.color: #2E2920
window.inactive.button.pressed.bg: Solid Flat
window.inactive.button.pressed.bg.color: #${inactive}
window.inactive.button.pressed.image.color: #${inactive}
window.inactive.button.toggled.image.color: #${inactive}
window.inactive.button.unpressed.bg: Solid Flat
window.inactive.button.unpressed.bg.color: #${inactive}
window.inactive.button.unpressed.bg.border.color: #${inactive}
window.inactive.button.unpressed.image.color: #${inactive}
window.inactive.client.color: #${color0}
window.inactive.grip.bg: Solid Flat
window.inactive.grip.bg.color: #${inactive}
window.inactive.handle.bg: Solid Flat
window.inactive.handle.bg.color: #${inactive}
window.inactive.label.bg: Parentrelative
window.inactive.label.text.color: #${inactive}
window.inactive.label.text.font: shadow=n
window.inactive.title.bg: Solid Flat
window.inactive.title.bg.color: #${inactive}
EOF

find "${gtk_templates_path_tmp_dir}/gtk-icons" -type f -exec sed -i "s/{background}/#${background}/g;s/{foreground}/#${foreground}/g;s/{color3}/#${color3}/g" {} +
cp -r "${gtk_templates_path_tmp_dir}/gtk-icons"/* "${gtk_icon_path}"/dynamic

"${__distro_path_root}"/bin/X11/WM/reload_gtk23 || show_em "failed to run reload_gtk23"
}

themes_builder(){
	gtk_theme_builder
	
	if [ "$_panel_name_" = 'polybar' ];then
		create_polybar_file
	elif [ "$_panel_name_" = 'tint2' ];then
		create_tint2_file
	fi
	
	if [ -d "$HOME/.config/geany" ];then
		create_geany_file
	fi
	
	if [ -d "$HOME/.config/kitty" ];then
		create_kitty_file
	fi
	
	if [ -d "$HOME/.config/alacritty" ];then
		create_alacritty_file
	fi
	
	if [ -d "$HOME/.config/x11/Xresources.d" ];then
		create_Xresources_file
	fi
	
	if pgrep openbox >/dev/null 2>&1;then
		reconfigure-openbox || show_em "failed to run reconfigure-openbox "
	fi
}
