#!/bin/bash
set -e
unalias -a
. "$__distro_path_lib"
. "${__distro_path_root}/lib/common/WM"

"${__distro_path_root}/bin/not_add_2_path"/check_4_dependencies_if_installed mpv $use_external_menu || exit 1

tv_config_dir="${script_config_path}/My_TV"
tv_config_file="${tv_config_dir}/termv.conf"
TERMV_DIR="${__distro_for_all_path}/termv"
Channels_List_DB="${TERMV_DIR}/Channels_List.txt"

if [ ! -d "${tv_config_dir}" ];then
	mkdir -p "$tv_config_dir"
fi

if [ ! -f "$tv_config_file" ];then
    tee "$tv_config_file" <<- 'EOF' >/dev/null 2>&1
    use_external_menu="auto"
    
    TERMV_CATEGORY=""
    TERMV_LANGUAGE=""
    TERMV_COUNTRY=""
    TERMV_FILTER_NSFW=TRUE

    TERMV_SWALLOW=false
    TERMV_MPV_FLAGS="--no-resume-playback"
EOF
fi

. "$tv_config_file"
use_external_menu="rofi"
if [ "$use_external_menu" = "auto" ];then
	if [ -t 1 ];then #on_terminal
		use_external_menu=fzf
	else
		use_external_menu=rofi
	fi
fi

if [ "$use_external_menu" = "fzf" ];then
	launcher() {	
		cat "${Channels_List_DB}" |\
		fzf -e -i --reverse --cycle --with-nth="1..-2"\
			--bind "enter:execute(_play {})"\
			--bind "double-click:execute(_play {})"\
			--header="Select channel (press Escape to exit)" -q "${*:-}"
	}
elif [ "$use_external_menu" = "rofi" ];then
	. "${Distro_config_file}"
	launcher() {
		Chosen_channel="$(cat "${Channels_List_DB}" |\
	    rofi -dmenu -i -p "Select channel (press Escape to exit)" -theme "$HOME/.config/rofi/$ROFI_STYLE"/runner.rasi -width 1500)"
	    _play "${Chosen_channel}"
	}
fi

if [ "${TERMV_SWALLOW}" = true ];then
	"${__distro_path_root}/bin/not_add_2_path"/check_4_dependencies_if_installed xdo || exit 1
	_play() {
		printf '%s\n' "Fetching channel, please wait..."
		WID=$(xdo id)
		xdo hide
		# shellcheck disable=SC2086
		mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate
		xdo show "$WID" && xdo activate "$WID"
	}
else
	_play() {
		printf '%s\n' "Fetching channel, please wait..."
		# shellcheck disable=SC2086
		mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}"
	}
fi
export -f _play

mkdir -p "${TERMV_DIR}"

if [ ! -f "${Channels_List_DB}" ] || [ ! "$(stat -c %y "${Channels_List_DB}" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ];then
	getURL '2term' https://raw.githubusercontent.com/iptv-org/database/refs/heads/master/data/channels.csv | \
	awk -F, -v cats="$TERMV_CATEGORY" -v nsfw_filter="$TERMV_FILTER_NSFW"  -v countrys="$TERMV_COUNTRY" '
		BEGIN {
    		# Only split if cats is not empty to avoid matching everything
    		if (length(cats) > 0) {
        		catscount = split(cats, exclude_arr, " ")
    		} else {
        		catscount = 0
    		}
    		if (length(countrys) > 0) {
        		countryscount = split(countrys, exclude_arr, " ")
    		} else {
        		countryscount = 0
    		}
		}
		{
    		# 1. NSFW Filter: Skip only if filter is ON and column 8 is TRUE
    		if (nsfw_filter == "TRUE" && ($8 == "TRUE" || $7 == "xxx")) {
        		next
    		}
		
    		# 2. Category Filter: Only run if catscount > 0
    		if (catscount > 0) {
        		for (i = 1; i <= catscount; i++) {
            		if ($7 ~ exclude_arr[i]) {
                		next
            		}
        		}
    		}
			
			# 2. Category Filter: Only run if countryscount > 0
			if (countryscount > 0) {
        		for (i = 1; i <= countryscount; i++) {
            		if ($6 ~ exclude_arr[i]) {
                		next
            		}
        		}
    		}
			
			# 3. skip line if no url exist
			if ($NF ~ /^[[:space:]]*$/) {
				next
			}
			
    		# 4. Output selection
    		print $1 "," $7 "," $6 "," $NF
		}' | column -t -s ',' > "$Channels_List_DB"
fi

launcher
