#!/bin/sh
# Install vim and add zellij distro
app_name="zellij"
__choice=""
say "Installing ${app_name}..." 1
repobin --root --file-repo no-web install zellij-org/zellij || failed_to_run "failed to run ${app_name} ."

copy_from_extra_skel ".config/zellij" || continue
