#!/bin/sh
. "/usr/share/my_stuff/lib/chroot/var"	
CHROOT_DIR="${BROWSERS_CHROOT_DIR}"
. "/usr/share/my_stuff/lib/chroot/functions"

set_default_chroot_browser_as_my_www_browser(){
	printf "\n###############################################\n"
	printf "Do you want to set ${APP_NAME} as default browser? 'my-www-browser' (yes or no)"
	printf "\n###############################################"
    stty -icanon -echo time 0 min 1
	answer2="$(head -c1)"
	stty icanon echo
    echo
    if [ "$answer2" = "y" ] || [ "$answer2" = "Y" ]; then
     	my-superuser ln -sf "$launch_default_chroot_browser" "$my_www_browser_path"
    fi
}

create_default_chroot_browser(){
	my-superuser ln -sf "${launch_default_chroot_browser}" "${LAUNCH_SCRIPT_PATH}" || failed_to_run "Failed to set execute permission on launch script"
	my-superuser ln -sf "${launch_default_chroot_browser}.desktop" "/usr/share/applications" || failed_to_run "Failed to set execute permission on launch script"
	set_default_chroot_browser_as_my_www_browser
}

end_of_chroot_creater(){	
	say "Creating launch script to run $APP_NAME from the host..."
	my-superuser ln -sf "${Extra_chroot_browser}/${SCRIPT_NAME}.desktop" "/usr/share/applications" || failed_to_run "Failed to set execute permission on launch script"
	my-superuser ln -sf "${Extra_chroot_browser}/${SCRIPT_NAME}" "${LAUNCH_SCRIPT_PATH}" || failed_to_run "Failed to set execute permission on launch script"
	
	if [ -f "/etc/doas.conf" ];then
		my-superuser tee -a "/etc/doas.conf" > /dev/null <<- EOF
		permit persist :users as root cmd $launch_chroot_browser
		EOF
	else
		my-superuser tee -a "/usr/share/my_stuff/system_files/doas.conf" > /dev/null <<- EOF
		permit persist :users as root cmd $launch_chroot_browser
		EOF
	fi
	
	if [ -d "/etc/sudoers.d" ];then
		my-superuser tee "/etc/sudoers.d/chroot_${APP_NAME}" > /dev/null <<- EOF
		%users ALL=(ALL) NOPASSWD: $launch_chroot_browser
		EOF
		my-superuser chmod 400 "/etc/sudoers.d/chroot_${APP_NAME}"
	fi
	
	if [ ! -f "${LAUNCH_SCRIPT_PATH}/${chroot_default_browser_name}" ];then
		create_default_chroot_browser
	else
		set_default_chroot_browser_as_my_www_browser
	fi
	say 
	say 
	say "You can now launch $APP_NAME from the chroot using the command: $SCRIPT_NAME"	
}
trap cleanup EXIT # from chroot_functions
chroot_creater

say "Installing $APP_NAME in the chroot..."
