#!/bin/sh
ROOT_CHROOT_DIR="/usr/share/my_stuff/system_files/chroots"
LAUNCH_SCRIPT_PATH="/usr/share/my_stuff/system_files/bin"
CHROOT_SCRIPT_PATH="/usr/share/my_stuff/system_files/chroots_scripts"
CHROOT_USER="chrootuser"
#tor
__GUID=4444
__UUID=4444
__ControlPort=9051
__DNSPort=5353
__SocksPort=9050
__TransPort=9040
_non_tor="192.168.1.0/24 192.168.0.0/24"
start_tor_chroot_script_name="start-tor-chroot.sh"
start_torproxy_script_name="torproxy"
_TOR_NAME="tor"
_TOR_USER="tor"

#cups
_CUPS_NAME="cups"
CUPS_GUI="chroot-cups-gui"
ENABLE_CUPS="chroot-cups-enable-web"

#browser
BROWSERS_CHROOT_NAME="chroot-browsers"
chroot_default_browser_name="chroot-browser"

TOR_CHROOT_NAME="chroot-${_TOR_NAME}"
CUPS_CHROOT_NAME="chroot-${_CUPS_NAME}"

RULES="${CHROOT_SCRIPT_PATH}/tor-router.save"
CUPS_CHROOT_DIR="${ROOT_CHROOT_DIR}/${CUPS_CHROOT_NAME}"
BROWSERS_CHROOT_DIR="${ROOT_CHROOT_DIR}/${BROWSERS_CHROOT_NAME}"
TOR_CHROOT_DIR="${ROOT_CHROOT_DIR}/${TOR_CHROOT_NAME}"
launch_default_chroot_browser="${LAUNCH_SCRIPT_PATH}/${chroot_default_browser_name}"
my_www_browser_path="${LAUNCH_SCRIPT_PATH}/my-www-browser"
