#!/bin/sh -e

say 'Adding Repo...' 1
Package_installer_ dnf-plugins-core
add_repo "https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo"
import_key "https://brave-browser-rpm-release.s3.brave.com/brave-core.asc"

say 'Installing package...' 1
Package_installer_ brave-browser
