#!/bin/sh -e

say 'Downloading rpm file...' 1
download_url=$(getURL 'latestgit' 'Alex313031/Thorium' 'rpm' | head -n 1)
getURL 'download2' "$download_url" "/tmp/thorium-latest.rpm"
my-superuser chown root:root "/tmp/thorium-latest.rpm"
cd "/tmp"

say 'Installing package...' 1
Package_installer_ thorium-latest.rpm && my-superuser rm -rdf "/tmp/thorium-latest.rpm"
