#!/bin/sh -e

say 'Adding Repo...' 1
Package_installer_ dnf-plugins-core
add_repo "https://repo.vivaldi.com/stable/vivaldi-fedora.repo"

say 'Installing package...' 1
Package_installer_ vivaldi-stable
