#!/bin/sh

app_name="typora"
Package_update_

download_key "gpg" "https://typora.io/linux/public-key.asc" "/usr/share/keyrings/typora.gpg"
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/typora.gpg] https://typora.io/linux ./" | my-superuser tee /etc/apt/sources.list.d/typora.list

Package_update_

clear

say 'Installing package...' 1

Package_installer_ ${app_name} || continue
copy_from_extra_skel ".config/typora" || continue
