#!/bin/sh -e
if [ ! -e /etc/yum.repos.d/rpmfusion-free.repo ] || [ ! -e /etc/yum.repos.d/rpmfusion-nonfree.repo ]; then # enabled
	return 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	return 1
fi

my-superuser "$PACKAGER" install "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora)".noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm
my-superuser "$PACKAGER" config-manager --enable fedora-cisco-openh264
my-superuser "$PACKAGER" config-manager --set-enabled rpmfusion-nonfree-updates
my-superuser "$PACKAGER" config-manager --set-enabled rpmfusion-free-updates
