#!/bin/sh -e
if grep -q "fastestmirror=True" /etc/dnf/dnf.conf && grep -q "defaultyes=True" /etc/dnf/dnf.conf && grep -q "max_parallel_downloads=10" /etc/dnf/dnf.conf;then # enabled
	return 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	return 1
fi
say "Configuring  DNF..."
my-superuser sed -i '/^max_parallel_downloads=/c\max_parallel_downloads=10' /etc/dnf/dnf.conf || echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
echo "fastestmirror=True" | my-superuser tee -a /etc/dnf/dnf.conf > /dev/null
echo "defaultyes=True" | my-superuser tee -a /etc/dnf/dnf.conf > /dev/null            
my-superuser "$PACKAGER" -y install dnf-plugins-core
