#!/bin/sh
# need superuser : called by my-installer
if [ "$(id -u)" -eq 0 ];then
	_SUPERUSER=""
else
	_SUPERUSER="my-superuser"
fi

if grep -q "fastestmirror=True" /etc/dnf/dnf.conf && grep -q "defaultyes=True" /etc/dnf/dnf.conf && grep -q "max_parallel_downloads=10" /etc/dnf/dnf.conf;then # enabled
	tweek_enabled=true 
elif [ "$1" = "--is-enable" ] || [ "$check_tweek" = "true" ];then # disabled and only check
	tweek_enabled=false
else
	say "Configuring  DNF..."
	${_SUPERUSER} sed -i '/^max_parallel_downloads=/c\max_parallel_downloads=10' /etc/dnf/dnf.conf || echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
	echo "fastestmirror=True" | ${_SUPERUSER} tee -a /etc/dnf/dnf.conf > /dev/null
	echo "defaultyes=True" | ${_SUPERUSER} tee -a /etc/dnf/dnf.conf > /dev/null            
	${_SUPERUSER} "$PACKAGER" -y install dnf-plugins-core
fi
