#!/bin/sh
app_name="zram-generator"

if lsmod | grep -q zram && [ -f "/etc/systemd/zram-generator.conf.d/zram.conf" ];then
	exit 0 
elif [ "$1" = "--is-enable" ];then # disabled and only check
	exit 1
fi

say "Installing ${app_name}..." 1

Package_installer_ "${app_name}" || continue
my-superuser mkdir -p /etc/systemd/zram-generator.conf.d/
if [ ! -f "/etc/systemd/zram-generator.conf.d/zram.conf" ];then
	my-superuser tee /etc/systemd/zram-generator.conf.d/zram.conf <<- EOF > /dev/null
	[zram0]
	zram-size = ram / 2
	compression-algorithm = zstd
	EOF
fi
command -v systemctl >/dev/null 2>&1 && my-superuser systemctl daemon-reexec || continue
service_manager enable systemd-zram-setup@zram0.service || continue
