#!/bin/sh
if [ "$1" = "--is-enable" ];then
	if ls /sys/kernel/iommu_groups/* >/dev/null 2>&1 || ls /sys/class/iommu/* >/dev/null 2>&1 || (cat /proc/cmdline | grep -q "iommu=on") || grep -Ecq '(vmx|svm)' /proc/cpuinfo;then
		exit 0
	else
		exit 1
	fi
fi

my-superuser dnf install -y @virtualization 
