#!/bin/sh
# need superuser : called by my-installer
app_name="dropbox"

say 'Installing package...' 1
Package_installer_ python3-gpg || Package_installer_ python3-gpgme || continue

my-superuser mkdir -p "${__distro_path_downloaded}"/dropbox
cd "${__distro_path_downloaded}"/dropbox
getURL '2term' https://linux.dropboxstatic.com/packages/dropbox.py | my-superuser tee dropbox.py >/dev/null 2>&1 || continue
my-superuser chmod +x dropbox.py || continue
my-superuser ln -sf "${__distro_path_downloaded}"/dropbox/dropbox.py ${__distro_path_root}/system_files/bin/dropbox || continue

my-superuser mkdir -p "${__distro_path_updater}"
my-superuser tee "${__distro_path_updater}"/dropbox_updater <<- 'EOF' > /dev/null
#!/bin/sh
# need superuser : called by my-installer
nohup dropbox update >/dev/null 2>&1
EOF
my-superuser chmod +x "${__distro_path_updater}/dropbox_updater" || continue

my-superuser ln -sf ${_APPS_EXTRA_LIBDIR}/Storage/dropbox_Extra/dropbox.desktop /usr/share/applications/ || continue
my-superuser ln -sf ${_APPS_EXTRA_LIBDIR}/Storage/dropbox_Extra/dropbox.1.gz /usr/share/man/man1/dropbox.1.gz2 || continue
"${__distro_path_updater}"/dropbox_updater || continue
