#!/bin/sh
# never edit anything after # since it req for shortcuts script
while read -r file
do
        case "$1" in
        "w")#setbg
        setbg -R "$file";;
        "c")#copy image
		[ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "m")#move image
		[ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
	"r")#rotate 90
		magick -rotate 90 "$file" "$file" ;;
	"R")#rotate -90
		magick -rotate -90 "$file" "$file" ;;
	"f")#flop
		magick -flop "$file" "$file" ;;
	"y")#copied to clipboard
		printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")#copied path to clipboard
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")#delete image
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"g")#install gimp
		# required
		. "$__distro_path_lib"
		"${__distro_path_root}/bin/not_add_2_path"/check_4_dependencies_if_installed at speaker-test notify-send || exit 1
		("${__distro_path_root}/bin/not_add_2_path"/check_4_dependencies_if_installed gimp || exit 1) && setsid -f gimp "$file" ;;
	"i")#notify-send notify image information
		notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
        esac
done
