#!/bin/sh
#called by my-installer
app_name="envycontrol"

Package_update_

say "Installing ${app_name}..." 1
Package_installer_ "${app_name}" || continue
  				
if [ ! -f "${__distro_path_root}/system_files/skel/.config/autostartscripts/gpu-switcher-session}" ];then
	ln -sf ${__distro_path_root}/bin/X11/yad/gpu_switcher/gpu-switcher-session "${__distro_path_root}/system_files/skel/.config/autostartscripts"
fi
  				
if [ ! -f "${__distro_path_root}/system_files/bin/gui_GPU_Switcher" ];then
	ln -sf ${__distro_path_root}/bin/X11/yad/gpu_switcher/gui_GPU_Switcher "${__distro_path_root}/system_files/bin"
fi
  				
if [ ! -f "${__distro_path_root}/system_files/bin/tray_GPU_Switcher" ];then
	ln -sf ${__distro_path_root}/bin/X11/yad/gpu_switcher/tray_GPU_Switcher "${__distro_path_root}/system_files/bin"
fi
