#!/bin/sh
# need superuser : called by my-installer
app_name="Fingerprint Drivers"

packages_list="fprintd libfprint"

say "Installing $app_name ..." 1

Package_installer_ "$packages_list" || continue

say 'Adding fingerprint_gui to bin ...' 1
my-superuser ln -sf ${__distro_path_root}/bin/X11/not_add_2_path/fingerprint_gui ${__distro_path_root}/system_files/bin
