#!/bin/sh
# need superuser : called by my-installer -e
tweek_as_dependency "Enable_IOMMU_support" || continue

app_name="virt-manager"
extra_apps_="qemu-emulators-full swtpm qemu-desktop libvirt dmidecode dnsmasq iptables-nft "

say "Installing ${app_name}..." 1
Package_installer_ "${app_name} ${extra_apps_}" || continue

Package_remove_ iptables

my-superuser sed -i 's/^#\?firewall_backend\s*=\s*".*"/firewall_backend = "iptables"/' "/etc/libvirt/network.conf"
if service_manager is-active polkit; then
	my-superuser sed -i 's/^#\?auth_unix_ro\s*=\s*".*"/auth_unix_ro = "polkit"/' "/etc/libvirt/libvirtd.conf"
	my-superuser sed -i 's/^#\?auth_unix_rw\s*=\s*".*"/auth_unix_rw = "polkit"/' "/etc/libvirt/libvirtd.conf"
fi

for value in libvirt libvirt_guest; do
	if ! grep -wq "$value" /etc/nsswitch.conf; then
		my-superuser sed -i "/^hosts:/ s/$/ ${value}/" /etc/nsswitch.conf
	fi
done

. "${_APPS_LIBDIR}/hypervisors/virt/post_install_virt_manager.sh"
. "${_APPS_LIBDIR}/hypervisors/virt/post_virtual_install.sh"
