#!/bin/sh -e
RC='\033[0m'
RED='\033[31m'

app_name="virt-manager"
extra_apps_="qemu-emulators-full swtpm qemu-desktop libvirt dmidecode dnsmasq iptables-nft "

say "Installing some packages..." 1
Package_installer_ ${extra_apps_} || continue

say "Installing ${app_name}..." 1
Package_installer_ ${app_name} || continue

my-superuser usermod "$USER" -aG kvm
my-superuser usermod "$USER" -aG libvirt

Package_remove_ iptables

my-superuser sed -i 's/^#\?firewall_backend\s*=\s*".*"/firewall_backend = "iptables"/' "/etc/libvirt/network.conf"
if service_manager is-active polkit; then
	my-superuser sed -i 's/^#\?auth_unix_ro\s*=\s*".*"/auth_unix_ro = "polkit"/' "/etc/libvirt/libvirtd.conf"
	my-superuser sed -i 's/^#\?auth_unix_rw\s*=\s*".*"/auth_unix_rw = "polkit"/' "/etc/libvirt/libvirtd.conf"
fi

for value in libvirt libvirt_guest; do
	if ! grep -wq "$value" /etc/nsswitch.conf; then
		my-superuser sed -i "/^hosts:/ s/$/ ${value}/" /etc/nsswitch.conf
	fi
done

service_manager enable libvirtd.service
my-superuser virsh net-autostart default

if [ ! -e "/dev/kvm" ]; then
	say "${RED}KVM is not available. Make sure you have CPU virtualization support enabled in your BIOS/UEFI settings. Please refer https://wiki.archlinux.org/title/KVM for more information.${RC}"
fi
