#!/bin/sh -e
my-installer --install-needed "GPU" || continue
say 'Installing package...' 1
copr_enable "wehagy/protonplus"
Package_installer_ -y wine dbus git ffmpeg ffmpeg-libs steam lutris protonplus
