#!/bin/sh

app_name="polychromatic"
extra_apps_="openrazer-meta"

if [ -f '/usr/share/my_stuff/system_files/Distrobox_ready' ];then
	Distrobox_Package_update_
	
	clear
	say 'Installing package...' 1
	Distrobox_package_installer_ ${app_name} || continue
	
else
	Package_update_
	
	clear
	
	say 'Installing package...' 1
	
	Package_installer_ ${app_name} || continue
	
	if [ -n "${extra_apps_}" ];then
		say 'Installing extra packages...' 1
		Package_installer_ ${extra_apps_} || continue
		clear
	fi
fi
