#!/bin/sh
#called by : my-installer
app_name="polychromatic"
extra_apps_="openrazer-meta"

if check_system_ready_file "Distrobox_ready";then
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	Package_installer_ "${app_name} ${extra_apps_}" || continue
fi
