#!/bin/sh

app_name="pipewire"
extra_apps_="gstreamer1.0-pipewire pipewire-alsa pipewire-jack pipewire-libcamera pipewire-pulse pipewire-v4l2"

say "Installing ${app_name} ..." 1
Package_installer_ "${app_name} ${extra_apps_}" || continue
