#!/bin/sh

app_name="obs-studio"

if [ -f "${__distro_path_root}/system_files/Distrobox_ready" ];then
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	Package_installer_ "${app_name}" || continue
fi
