#!/bin/sh

setbg -r
. "/usr/share/my_stuff/lib/common/WM"
. "/usr/share/my_stuff/lib/common/panel"

if [ "$_panel_name_" = "polybar" ]; then
   polybar-session 
fi

if [ "$_panel_name_" = "xfce4" ]; then
	xfce4-panel-session
fi 

if [ "$_panel_name_" = "tint2" ]; then
	tint2-session
fi 

