#!/bin/sh
# need superuser : called by my-superuser
# work on this : workonthis
set -e
exit
if [ "$(id -u)" -ne 0 ]; then
    my-superuser $0 "$__distro_path_lib"
    exit
fi

current_path="$(dirname "$0")"

__distro_path_lib="${1:-$__distro_path_lib}"
if [ -z "$__distro_path_lib" ];then
	. "$__distro_path_lib"
	gtktheme_path="${__distro_path_themes}/system-themes"
else
	gtktheme_path="${current_path}/generated_gtk_theme"
fi

list_of_base_GTK_theme="$(find "${current_path}/source_base" -type f || :)"
mkdir -p "${gtktheme_path}"
for t in ${list_of_base_GTK_theme};do
	. "$t"
	mkdir -p "${gtktheme_path}/${base_name}"
done
