#!/bin/sh
# need superuser : called by my-superuser
# work on this : workonthis
set -e
exit

current_path="$(dirname "$(realpath "$0")")"
source_base_path="${current_path}/source_base"
baseGTK_path="${current_path}/baseGTK"

__distro_path_lib="${1:-$__distro_path_lib}"
if [ -n "$__distro_path_lib" ];then
	if [ "$(id -u)" -ne 0 ]; then
    	my-superuser $0 "$__distro_path_lib"
    	exit
	fi
	. "$__distro_path_lib"
	gtktheme_path="${__distro_path_themes}/system-themes"
else
	gtktheme_path="${current_path}/generated_gtk_theme"
fi

list_of_base_GTK_theme="$(find "${source_base_path}" -type f || :)"
mkdir -p "${gtktheme_path}"
for t in ${list_of_base_GTK_theme};do
	. "$t"
	theme_path="${gtktheme_path}/${base_name}"
	if [ -d "$theme_path" ]
		rm -rdf "$theme_path"
	fi
	mkdir -p "$theme_path"
	. "$baseGTK_path/$THEME_STYLE"
done
