#!/bin/sh
set -e

current_path="$(dirname "$0")"

if [ -d "$HOME/Desktop/workonNow/oomox_files/oomox_gui/colors/zzmythemes" ];then
	oomox_files_path="$HOME/Desktop/workonNow/oomox_files/oomox_gui/colors/zzmythemes"
elif [ -d "$HOME/.config/oomox/colors/zzmythemes" ];then
	oomox_files_path="$HOME/.config/oomox/colors/zzmythemes"
else
	echo "no dir found. "
	exit
fi

output_dir="${current_path}/new_source_base"

list_of_base_GTK_theme="$(find "${oomox_files_path}" -type f || :)"
mkdir -p "${output_dir}"

for t in ${list_of_base_GTK_theme};do
	. "$t"
	style_name="${t##*/}"
	style_path="${output_dir}/${style_name}"
	if [ "$THEME_STYLE" = "materia" ];then
		tee  "$style_path" <<-EOF >/dev/null 2>&1
		ACCENT_BG="$ACCENT_BG"
		BG="$BG"
		BTN_BG="$BTN_BG"
		BTN_FG="$BTN_FG"
		BTN_OUTLINE_OFFSET="$BTN_OUTLINE_OFFSET"
		BTN_OUTLINE_WIDTH="$BTN_OUTLINE_WIDTH"
		CARET1_FG="$CARET1_FG"
		CARET2_FG="$CARET2_FG"
		CARET_SIZE="$CARET_SIZE"
		CINNAMON_OPACITY="$CINNAMON_OPACITY"
		FG="$FG"
		GRADIENT="$GRADIENT"
		GTK3_GENERATE_DARK="$GTK3_GENERATE_DARK"
		HDR_BG="$HDR_BG"
		HDR_BTN_BG="$HDR_BTN_BG"
		HDR_BTN_FG="$HDR_BTN_FG"
		HDR_FG="$HDR_FG"
		ICONS_DARK="$ICONS_DARK"
		ICONS_LIGHT="$ICONS_LIGHT"
		ICONS_LIGHT_FOLDER="$ICONS_LIGHT_FOLDER"
		ICONS_MEDIUM="$ICONS_MEDIUM"
		ICONS_SYMBOLIC_ACTION="$ICONS_SYMBOLIC_ACTION"
		ICONS_SYMBOLIC_PANEL="$ICONS_SYMBOLIC_PANEL"
		MATERIA_PANEL_OPACITY="$MATERIA_PANEL_OPACITY"
		MATERIA_SELECTION_OPACITY="$MATERIA_SELECTION_OPACITY"
		MATERIA_STYLE_COMPACT="$MATERIA_STYLE_COMPACT"
		MENU_BG="$MENU_BG"
		MENU_FG="$MENU_FG"
		OUTLINE_WIDTH="$OUTLINE_WIDTH"
		ROUNDNESS="$ROUNDNESS"
		SEL_BG="$SEL_BG"
		SEL_FG="$SEL_FG"
		SPACING="$SPACING"
		SPOTIFY_PROTO_BG="$SPOTIFY_PROTO_BG"
		SPOTIFY_PROTO_FG="$SPOTIFY_PROTO_FG"
		SPOTIFY_PROTO_SEL="$SPOTIFY_PROTO_SEL"
		TERMINAL_ACCENT_COLOR="$TERMINAL_ACCENT_COLOR"
		TERMINAL_BACKGROUND="$TERMINAL_BACKGROUND"
		TERMINAL_COLOR15="$TERMINAL_COLOR15"
		TERMINAL_COLOR7="$TERMINAL_COLOR7"
		TERMINAL_FOREGROUND="$TERMINAL_FOREGROUND"
		THEME_STYLE="$THEME_STYLE"
		TXT_BG="$TXT_BG"
		TXT_FG="$TXT_FG"
		UNITY_DEFAULT_LAUNCHER_STYLE="$UNITY_DEFAULT_LAUNCHER_STYLE"
		WM_BORDER_FOCUS="$WM_BORDER_FOCUS"
		WM_BORDER_UNFOCUS="$WM_BORDER_UNFOCUS"
		EOF
	fi
done
