#!/bin/sh

app_name="vlc"
set_as_default_package=true
prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false

say 'Installing package...' 1

Package_installer_ ${app_name} || continue

[ "$set_as_default_package" = true ] && my-alternatives --set "my-media-player" "${app_name}"
