#!/bin/sh

app_name="lxterminal"

say 'Installing package...' 1

Package_installer_ "${app_name}" || continue

copy_from_extra_skel ".config/lxterminal" || continue
copy_blob_extra_2_system_files_blob "lxterminal" || continue
