#!/bin/bash
# --------------------------------- checks -----------------------------------
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -z "$BASHDOTDIR" ];then
  	export My_shell_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/myshell"
  	export BASHDOTDIR="${My_shell_DIR}/bash"
fi

# --------------------------------- Settings ----------------------------------
vim_mode_enabled=true

# ---------------------------------  Theme  -----------------------------------
BASH_THEME="pure"
SSH_THEME="pure"

# -------------------------------  main file  ---------------------------------
source "$BASHDOTDIR"/bashrc.sh
