#!/bin/bash
if [[ -n $SSH_CONNECTION ]];then
	# -------------------------------  Checks  -----------------------------------
	if [ -z "$BASHDOTDIR" ];then
		export My_shell_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/myshell"
		export BASHDOTDIR="${My_shell_DIR}/bash"
	fi
	
	# -------------------------------  main file  ---------------------------------
	source "$BASHDOTDIR/bashrc"
	
fi
