#!/bin/sh
app_name="envycontrol"

say "create envycontrol installtion file."
my-superuser tee /usr/share/my_stuff/system_files/updater/envycontrol <<- 'EOF' > /dev/null
#!/bin/sh
__distro_path="/usr/share/my_stuff"
PATH="${__distro_path}/bin:$PATH"
envycontrol_updater_path="$(mktemp -d)"
download_url="$(getURL 'latestgit' 'bayasdev/envycontrol' 'deb')"
 				
getURL 'download2' "${download_url}" "/tmp/$USER/python3-envycontrol_version.deb"
cd /tmp/$USER
my-superuser apt-get -y install ./python3-envycontrol_version.deb
			
if [ ! -f "${__distro_path}/system_files/skel/.config/autostartscripts/gpu-switcher-session}" ];then
	ln -sf "${__distro_path}"/bin/X11/yad/gpu_switcher/gpu-switcher-session "${__distro_path}/system_files/skel/.config/autostartscripts"
fi
  				
if [ ! -f "${__distro_path}/system_files/bin/gui_GPU_Switcher" ];then
	ln -sf "${__distro_path}"/bin/X11/yad/gpu_switcher/gui_GPU_Switcher "${__distro_path}/system_files/bin"
fi
  				
if [ ! -f "${__distro_path}/system_files/bin/tray_GPU_Switcher" ];then
	ln -sf "${__distro_path}"/bin/X11/yad/gpu_switcher/tray_GPU_Switcher "${__distro_path}/system_files/bin"
fi
EOF
my-superuser chmod +x /usr/share/my_stuff/system_files/updater/envycontrol
