#!/bin/sh
app_name="envycontrol"

say "Installing ${app_name}..." 1
repobin --sudo --mode deb install bayasdev/envycontrol || failed_to_run "failed to run ${app_name} ."
  				
if [ ! -f "${__distro_path_root}/system_files/skel/.config/autostartscripts/gpu-switcher-session}" ];then
	ln -sf ${__distro_path_root}/bin/X11/yad/gpu_switcher/gpu-switcher-session "${__distro_path_root}/system_files/skel/.config/autostartscripts"
fi
  				
if [ ! -f "${__distro_path_root}/system_files/bin/gui_GPU_Switcher" ];then
	ln -sf ${__distro_path_root}/bin/X11/yad/gpu_switcher/gui_GPU_Switcher "${__distro_path_root}/system_files/bin"
fi
  				
if [ ! -f "${__distro_path_root}/system_files/bin/tray_GPU_Switcher" ];then
	ln -sf ${__distro_path_root}/bin/X11/yad/gpu_switcher/tray_GPU_Switcher "${__distro_path_root}/system_files/bin"
fi

my-superuser prime-select on-demand
my-superuser service_manager mask gpu-manager.service
