#!/bin/sh
app_name="Fingerprint Drivers"
packages_list="fprintd libpam-fprintd"

say "Installing $app_name ..." 1

Package_installer_ $packages_list || continue

say 'Adding fingerprint_gui to bin ...' 1
my-superuser ln -sf /usr/share/my_stuff/bin/not_add_2_path/fingerprint_gui /usr/share/my_stuff/system_files/bin
