; __  __           _       _           
;|  \/  | ___   __| |_   _| | ___  ___ 
;| |\/| |/ _ \ / _` | | | | |/ _ \/ __|   z0mbi3
;| |  | | (_) | (_| | |_| | |  __/\__ \   https://github.com/gh0stzk/dotfiles
;|_|  |_|\___/ \__,_|\__,_|_|\___||___/   z0mbi3.zk@protonmail.com


[module/bi]
type = custom/text
content = "%{T4}%{T-}"
content-foreground = ${color.mb}
content-background = ${color.bg}

[module/bd]
type = custom/text
content = "%{T4}%{T-}"
content-foreground = ${color.mb}
content-background = ${color.bg}

######################################################

[module/date]
type = internal/date

interval = 1.0

time = %I:%M %P
format-foreground = ${color.fg}
;;date-alt = " %A, %d %B %Y"

format = <label>
label = "%{A1:cal-popup --popup:}%time%%{A}"

######################################################

[module/filesystem]
type = internal/fs
mount-0 = /

interval = 60
fixed-values = false

format-mounted = <label-mounted>
format-mounted-prefix = "Disk: "
format-mounted-prefix-foreground = ${color.purple}
format-mounted-prefix-background = ${color.mb}

format-unmounted = <label-unmounted>
format-unmounted-prefix = "Disk: "

label-mounted = "%used%  "
label-mounted-background = ${color.mb}

label-unmounted = %mountpoint%: not mounted
label-unmounted-background = ${color.mb}

######################################################

[module/network]
type = internal/network
interface = ${system.network_interface}

interval = 3.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = "NET: "
format-connected-background = ${color.mb}
format-connected-foreground = ${color.green}

speed-unit = ""
label-connected = "%{A1:rofi-network-manager:}%netspeed%%{A}"
label-connected-background = ${color.mb}
label-connected-foreground = ${color.yellow}

format-disconnected = <label-disconnected>
format-disconnected-prefix = "NET: "
format-disconnected-background = ${color.mb}
format-disconnected-foreground = ${color.red}

label-disconnected = "%{A1:rofi-network-manager:}Offline%{A}"
label-disconnected-background = ${color.mb}
label-disconnected-foreground = ${color.red}

######################################################

[module/ethernet]
type = internal/network
interface = ${system.network_interface}

interval = 3.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = "NET: "
format-connected-background = ${color.mb}
format-connected-foreground = ${color.green}

speed-unit = ""
label-connected = "%{A1:rofi-network-manager:}%netspeed%%{A}"
label-connected-background = ${color.mb}
label-connected-foreground = ${color.yellow}

format-disconnected = <label-disconnected>
format-disconnected-prefix = "NET: "
format-disconnected-background = ${color.mb}
format-disconnected-foreground = ${color.red}

label-disconnected = "%{A1:rofi-network-manager:}Offline%{A}"
label-disconnected-background = ${color.mb}
label-disconnected-foreground = ${color.red}

######################################################

[module/volume]
type = internal/volume
use-ui-max = true
interval = 5

;;<bar-volume>
format-volume = <label-volume>
format-volume-prefix = "VOL: "
format-volume-background = ${color.mb}
format-volume-foreground = ${color.indigo}

label-volume = "%percentage%%"
label-volume-background = ${color.mb}
label-volume-foreground = ${color.fg}

format-muted = <label-muted>
format-muted-prefix = 󰝟
format-muted-background = ${color.mb}
label-muted = " Muted"
label-muted-background = ${color.mb}
label-muted-foreground = ${color.red}

click-right = openbox_scripts --pavucontrol

######################################################

[module/brightness]
type = internal/backlight
card = ${system.graphics_card}

enable-scroll = false

format = <ramp><label>
label = "%percentage%% "

ramp-0 = 󰃚
ramp-1 = 󰃚
ramp-2 = 󰃝
ramp-3 = 󰃝
ramp-4 = 󰃟
ramp-5 = 󰃟
ramp-6 = 󰃠
ramp-7 = 󰃠
ramp-font = 2
ramp-padding = 3pt
ramp-foreground = ${color.yellow}

######################################################

[module/bna]
type = custom/text

content = " NA"
content-foreground = ${color.yellow}

######################################################

[module/battery]
type = internal/battery
full-at = 99
battery = ${system.battery}
adapter = ${system.adapter}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-prefix-foreground = ${color.red}
label-charging = %percentage%%

format-discharging = <ramp-capacity><label-discharging>
label-discharging = %percentage%%

format-full = <label-full>
format-full-prefix = 
format-full-prefix-font = 5
format-full-prefix-padding = 3 pt
format-full-prefix-foreground = ${color.green}
label-full = "%percentage%%"

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${color.yellow}
ramp-capacity-font = 5
ramp-capacity-padding = 3 pt

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${color.green}
animation-charging-font = 5
animation-charging-padding = 3 pt
animation-charging-framerate = 700

######################################################

[module/AC_only]
type = custom/text

content-prefix = ${system.AC_only_prefix}
content = ${system.AC_only_content}
content-foreground = ${color.green}
content-padding = 0

click-left = my_power_manager --gui

######################################################

[module/weather]
type = custom/script
exec = get_weather -i
interval = 900
format = <label>
label = "%output%"

######################################################

[module/workspaces]
type = internal/xworkspaces

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false

ws-icon-0 = xprop_NET_DESKTOP_NAMES 1;󰬺
ws-icon-1 = xprop_NET_DESKTOP_NAMES 2;󰬻
ws-icon-2 = xprop_NET_DESKTOP_NAMES 3;󰬼
ws-icon-3 = xprop_NET_DESKTOP_NAMES 4;󰬽
ws-icon-4 = xprop_NET_DESKTOP_NAMES 5;󰬾
ws-icon-5 = xprop_NET_DESKTOP_NAMES 6;󰬿
ws-icon-default = "♟ "


format = <label-state>
format-font = 3

label-active_focused = %icon%
label-active_focused-background = ${color.mb}
label-active_focused-padding = 1
label-active_focused-foreground = ${color.blue}

label-occupied = %icon%
label-occupied-padding = 1
label-occupied-background = ${color.mb}
label-occupied-foreground= ${color.green}

label-urgent = %icon%
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${color.fg}
label-empty-padding = 1
label-empty-background = ${color.mb}

[module/tiling_mod]
type = internal/xworkspaces

format = <label-mode>
format-background = ${color.bg}
format-foreground = ${color.purple}
format-padding = 1
format-font = 1

label-monocle = "Monocle"
label-tiled = "Tiled"

label-floating = " | Float"
label-pseudotiled = " | Pseudo"
label-fullscreen = " | Full"

label-locked = " | Locked"
label-sticky = " | Sticky"
label-private = " | Private"

######################################################

[module/no_tiling_mod]
type = custom/text
content = " "

######################################################

[module/browser]
type = custom/text
content = "󰇧"
content-padding = 1
content-background = ${color.bg}
content-foreground = ${color.orange}

click-left = my-www-browser

[module/filem]
type = custom/text
content = "󰷏"
content-padding =1
content-background = ${color.bg}
content-foreground = ${color.yellow}

click-left = my-file-manager

[module/terminal]
type = custom/text
content = "󰆍"
content-padding = 1
content-background = ${color.bg}
content-foreground = ${color.blue}

click-left = my-terminal-emulator

[module/editor]
type = custom/text
content = "󱞂"
content-padding = 1
content-background = ${color.bg}
content-foreground = ${color.red}

click-left = my-text-editor

[module/whats]
type = custom/text
content = "󰖣"
content-padding = 1
content-background = ${color.bg}
content-foreground = ${color.green}

click-left = my-www-browser https://web.whatsapp.com/

[module/fetch]
type = custom/text
content = "󰯇"
content-padding = 1
content-background = ${color.bg}
content-foreground = ${color.pink}

click-left = sysinfo_script_ --system

######################################################

[module/title]
type = internal/xwindow

format = <label>
format-prefix = "󱂬 "
format-prefix-foreground = ${color.purple}
format-prefix-font = 2

label = %title%
label-maxlen = 45

label-empty = "${system.distro_name}"
label-empty-foreground = ${color.grey}

######################################################

[module/updates]
type = custom/script
exec = updates.sh
interval = 120
label = "%output%"
label-background = ${color.mb}
click-left = popup_terminal --commands "update-notification -i"
click-right = popup_terminal --commands "update-notification -l"
format-prefix = "󰑖 "
format-prefix-foreground = ${color.green}
format-prefix-background = ${color.mb}

######################################################

[module/launcher]
type = custom/text

content = "${system.distro_icon}"
content-font = 3
content-foreground = ${color.fg}

click-left = rofi-launcher
click-right = RiceSelector

######################################################

[module/sep]
type = custom/text
content = " "
content-foreground = ${color.bg-alt}

######################################################

[module/sep2]
type = custom/text
content = " 󰇙 "
content-foreground = ${color.indigo}

######################################################

[module/cpu_bar]
type = internal/cpu

interval = 0.5
format = <label>
format-prefix = "CPU: "
format-prefix-background = ${color.mb}
format-prefix-foreground = ${color.red}

label = "%percentage%%  "
label-background = ${color.mb}

######################################################

[module/memory_bar]
type = internal/memory

interval = 3

format = <label>
format-prefix = "RAM: "
format-prefix-background = ${color.mb}
format-prefix-foreground = ${color.yellow}

label = "%used% "
label-background = ${color.mb}

######################################################

[module/mpd_control]
type            = internal/mpd
host            = 127.0.0.1
port            = 6600
interval        = 2
format-online   = <icon-prev><toggle><icon-next>
format-offline  = <label-offline>
label-offline = "󰝛 No Music"
icon-play               = " %{T2}󰐌"
icon-pause              = " %{T2}󰏥"
icon-stop               = " %{T2}󰙦"
icon-prev               = "%{T2}󰼨"
icon-next               = " %{T2}󰼧"

format-offline-foreground = ${color.grey}

icon-play-foreground    = ${color.green}
icon-pause-foreground   = ${color.green}
icon-stop-foreground    = ${color.green}
icon-prev-foreground    = ${color.blue}
icon-next-foreground    = ${color.blue}
toggle-on-foreground    = ${color.green}
toggle-off-foreground   = ${color.red}

######################################################

[module/mpd]
type                    = internal/mpd
host                    = 127.0.0.1
port                    = 6600
interval        		= 2
format-online           = "%{F#87a987}[%{F-} %{A1:popup_terminal --commands ncmpcpp:}<label-song>%{A} %{F#87a987}]%{F-}"
format-offline          = ""
label-song              = "%title%"
label-song-maxlen		= 40
icon-repeat             = "󰝚"

icon-repeat-background  = ${color.bg}
toggle-on-foreground    = ${color.green}
toggle-off-foreground   = ${color.red}

######################################################

[module/mplayer]
type = custom/text
content = ""
content-foreground = ${color.green}

click-left = popup_terminal --commands mpv
click-right = popup_terminal --commands ncmpcpp

[module/usercard]
type = custom/text
content =  ""
content-foreground = ${color.cyan}

click-left = usercard

[module/power]
type = custom/text
content = "󰐥"
content-foreground = ${color.red}

click-left = my_session_manager --rofi

#####################################################

[module/tray_m]
type = internal/tray

format = <tray>
format-background = ${color.bg}
tray-background = ${color.bg}
tray-foreground = ${color.fg}
tray-spacing = 8px
tray-padding = 0px
tray-size = 55%

#####################################################

[module/notray_m]
type = custom/text
content = " "

#####################################################

[module/bluetooth]
type = custom/script
exec = bluetooth.sh
interval = 3

format = <label>
format-font = 2
label = "%output%"
click-left = rofi-bluetooth

#####################################################

[module/no_bluetooth]
type = custom/text
content = "${system.NO_BT_content}"
content-font = 2
