# ============================
# ========== Colors ==========
# ============================

foreground            #dfd9cd
background            #100f0d
cursor                #dfd9cd

selection_foreground  #100f0d
selection_background  #dfd9cd

active_border_color   #dfd9cd
inactive_border_color #9c978f
bell_border_color     #9c978f

color0  #100f0d
color1  #E99551
color2  #C8A763
color3  #24768B
color4  #537A84
color5  #299299
color6  #539EA8
color7  #dfd9cd
color8  #9c978f
color9  #E99551
color10 #C8A763
color11 #24768B
color12 #537A84
color13 #299299
color14 #539EA8
color15 #dfd9cd

active_tab_foreground   #C8A763
active_tab_background   #100f0d
active_tab_font_style   normal

inactive_tab_foreground #dfd9cd
inactive_tab_background #100f0d

# vim:ft=conf
