#!/bin/sh
# need superuser : called by my-installer
app_name="docker"
__newGroup="docker"

if [ ! -f "${__distro_path_root}/system_files/Container_Group_podman" ] || [ ! -L "${__distro_path_root}/system_files/bin/CONTAINER_RT" ];then	
	say "Installing ${app_name}..." 1
	
	Package_installer_ "${app_name} ${extra_apps_}" || continue
	
	my-superuser usermod -aG docker ${USER} || :
	service_manager enable docker.service || :
	service_manager enable containerd.service || :
	
	my-superuser gpasswd -a ${USER} docker || :
	my-superuser service docker restart
	
	if ! grep -q '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"5"}}' /etc/docker/daemon.json;then
		# Limit log size to avoid running out of disk
		echo '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"5"}}' | my-superuser tee -a /etc/docker/daemon.json > /dev/null
	fi
	
	generate_applicationsdotdesktop_link "Docker"
	
	echo "${__newGroup}" | my-superuser tee "${__distro_path_root}/system_files/Container_Group_docker" > /dev/null 2>&1
fi	
