#!/bin/sh
# Xsession - run as user
case $SHELL in
  */bash)
    [ -z "$BASH" ] && exec $SHELL $0 "$@"
	. ${HOME}/.config/myshell/profile.sh
	. ${HOME}/.config/myshell/bash/bprofile.sh
    ;;
*/zsh)
    [ -z "$ZSH_NAME" ] && exec $SHELL $0 "$@"
    . ${HOME}/.config/myshell/profile.sh
    . ${HOME}/.config/myshell/zsh/zprofile.sh
    ;;
  */csh|*/tcsh)
    # [t]cshrc is always sourced automatically.
    # Note that sourcing csh.login after .cshrc is non-standard.
    xsess_tmp=$(mktemp /tmp/MmdmdmdmdmdmdmdmdmM/xsess-env-XXXXXX)
    $SHELL -c "if (-f /etc/csh.login) source /etc/csh.login; if (-f ~/.login) so                                                                                                                                                                                 urce ~/.login; /bin/sh -c 'export -p' >! $xsess_tmp"
    . $xsess_tmp
    rm -f $xsess_tmp
    ;;
  */fish)
    . ${HOME}/.config/myshell/profile.sh
	. ${HOME}/.config/myshell/bash/bprofile.sh
    xsess_tmp=$(mktemp /tmp/MmdmdmdmdmdmdmdmdmM/xsess-env-XXXXXX)
    $SHELL --login -c "/bin/sh -c 'export -p' > $xsess_tmp"
    . $xsess_tmp
    rm -f $xsess_tmp
    ;;
  *) # Plain sh, ksh, and anything we do not know.
    . ${HOME}/.config/myshell/profile.sh
	. ${HOME}/.config/myshell/bash/bprofile.sh
    ;;
esac

