#!/bin/sh
# work on this : add https://github.com/denisidoro/navi
set -e
op__="${1-}"
__lang=".en"

. "$__distro_path_lib"
tldr_dir="$__distro_for_all_path/tldr"
cheat_sh_dir="$__distro_for_all_path/cheat_sh"
betterman_dir="$__distro_for_all_path/betterman"
navi_cheats_dir="$__distro_for_all_path/navi_cheats"
fzf_menu_file_path="${betterman_dir}/fzf_menu_file"

git_clone(){
	git clone --depth=1 "${1:-}" "${2:-}"
}

build_betterman_dir(){
	if [ -f "$betterman_dir/done_building" ];then
		return
	fi
	
	mkdir -p \
		"$betterman_dir/cheat_sh" \
		"$betterman_dir/navi_cheats" \
		"$betterman_dir/tldr_${__lang}"
	
	for section in common linux; do
		if [ ! -L "$betterman_dir/tldr_${__lang}/$section" ];then
			ln -sf "$tldr_dir/pages${__lang}/$section" "$betterman_dir/tldr_${__lang}/$section"
		fi
	done
	
	for subdir in see_also sheets; do
		if [ ! -L "$betterman_dir/cheat_sh/$subdir" ];then
			ln -sf "$cheat_sh_dir/$subdir" "$betterman_dir/cheat_sh/$subdir"
		fi
	done
	
	for d in "$navi_cheats_dir"/*; do
		dir_basename="$(basename "$d")"
		if [ ! -L "$betterman_dir/navi_cheats/$dir_basename" ] && [ -d "$d" ];then
			cp -r "$d" "$betterman_dir/navi_cheats/$dir_basename"
		fi
	done
	rm -rdf "$betterman_dir/navi_cheats/os"
	touch "$betterman_dir/done_building"
}

download_betterman_repos(){
	if [ ! -d "${tldr_dir}" ];then
		if [ ! -d "${tldr_dir}/.git" ];then
			rm -rdf "${tldr_dir}"
		fi
		git_clone https://github.com/tldr-pages/tldr "${tldr_dir}"
	fi

	if [ ! -d "${cheat_sh_dir}" ];then
		if [ ! -d "${cheat_sh_dir}/.git" ];then
			rm -rdf "${cheat_sh_dir}"
		fi
		git_clone https://github.com/chubin/cheat.sheets.git "${cheat_sh_dir}"
	fi
	
	if [ ! -d "${navi_cheats_dir}" ];then
		if [ ! -d "${navi_cheats_dir}/.git" ];then
			rm -rdf "${navi_cheats_dir}"
		fi
		git_clone https://github.com/denisidoro/cheats.git "${navi_cheats_dir}"
		create_fzf_cache_file_
	fi
}

update_betterman() {
	last_update="$(stat -c %y "$betterman_dir" 2>/dev/null | cut -d' ' -f1 | cut -d'-' -f1-2)"
	current_month="$(date +'%Y-%m')"

	if [ "$last_update" != "$current_month" ]; then
		for dir in "$tldr_dir" "$cheat_sh_dir" "$navi_cheats_dir"; do
			if [ -d "$dir/.git" ]; then
				(
					cd "$dir"
					git pull --quiet
					[ -n "$(git status --porcelain)" ] && git checkout .
				)
			fi
			if [ "$dir" = "$navi_cheats_dir" ];then
				create_fzf_cache_file_
			fi
		done
		rm -rf "$betterman_dir/done_building"
	fi
}

install_betterman(){
	download_betterman_repos
	build_betterman_dir
	update_betterman
	build_betterman_dir
}

help() {
	script_name="$(basename "$0")"
	cat <<-EOF
	Usage: $script_name [option] <command>
	
		Options:
  		-c, --cheat     Show cheat.sh output for command
  		-t, --tldr      Show betterman/tldr content
  		-u, --update    Update all cheat repositories
  		-h, --help      Show this help message
	EOF
	exit 0
}

run_my_tldr_(){
	cmd="${1:-}"
	extra_arg="${2:-}"
	
	if [ -z "$cmd" ];then
		help
	fi
	
	install_betterman
	
	if [ -z "${extra_arg}" ];then
		result="$(find -L "${betterman_dir}" \( -name "${cmd}.md" -o -name "${cmd}.cheat" -o -name "${cmd}" \) 2>/dev/null || :)"
	
		if [ -z "${result}" ];then
			echo "no betterman entry for ${cmd}" 
			exit 1
		fi
		
		batcat --style=plain --paging=never "${result}"
	else
		get_cheat_sh_online "${@}"
	fi
}

get_cheat_sh_online(){
	# work on this : make it offline https://github.com/chubin/cheat.sh
	command_2_find="${1:-}"
	shift
	cheat_sh_query="${@}"
	
	if [ -z "${cheat_sh_query}" ];then
		getURL '2term' "cheat.sh/${command_2_find}"
	else
		cheat_sh_query=$(printf '%s' "${cheat_sh_query}" | sed 's@ *$@@; s@^ *@@; s@ @/@; s@ @+@g')
		getURL '2term' "cheat.sh/${command_2_find}/${cheat_sh_query}"
	fi
}

create_fzf_cache_file_(){
	:
}

fzf_mode_(){
	column -t -s '#' -o ' # ' "${fzf_menu_file_path}" |\
		fzf --delimiter '#' --with-nth '1,2,3' --preview 'printf "%s [%s]\n%s" "{2}" "{1}" "{3}"' --preview-window 'top:3:wrap' --header 'Press Enter to copy the command' --bind 'enter:become(eval {4})'
}

if [ -n "$op__" ];then
	shift
fi

case "$op__" in
	-c|--cheat) get_cheat_sh_online "${@}" ;;
	-t|--tldr) run_my_tldr_ "${@}" ;;
	-u|--update) install_betterman ;;
	-h |--help) help ;;
	-f |--fzf | '') fzf_mode_ ;;
	*) run_my_tldr_ "$op__" "${@}" ;;
esac
