#!/bin/sh
# need superuser : use my-superuser
# if this line exist script will be part of hub script.

# Purpose: Quick check of logged service failures and sys errors

set -e

YELLOW="\\033[1;33m"
NC="\\033[0m" # no colour

banner() {
  printf "\n"
  printf "${YELLOW}#### ${1} ####${NC}"
  printf "\n"
}

main() {
	banner "Failed systemd services"
	my-superuser systemctl --failed
	banner "High priority errors in systemd journal"
	my-superuser journalctl -p 3 -xb
}

# (O< -- Let's go!
# (/)_
main "$@"
