#!/bin/sh
# download audio from URL and set ID3v2 metadata
set -eu

ask_question(){
	echo "$1"
	read answer
	echo $answer
}

check_command() {
  state=true
  for package in "${@}"; do
    if ! command -v "${package}" >/dev/null 2>&1;then 
      echo "MISSING: ${package} not installed."
      state=false
    fi
  done
  "${state}" && return 0 || return 1
}

YTDL=yt-dlp

! check_command "${YTDL}" mid3v2 && exit 3

OPTIONS=t:a:u:f:
LONGOPTIONS=title:,artist:,url:,format
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "${PARSED}"

while [ $# -ge 1 ]; do
  case "$1" in
    -t|--title)
      TITLE="$2"
      shift 2
      ;;
    -a|--artist)
      ARTIST="$2"
      shift 2
      ;;
    -u|--url)
      URL="$2"
      shift 2
      ;;
    -f|--format)
      FORMAT="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error: unknown command line option \"$2\"."
      exit 3
      ;;
  esac
done

if [ -z "$TITLE" ];then
    TITLE=$(ask_question "What is the title?")
fi

if [ -z "$ARTIST" ];then
    ARTIST=$(ask_question "Who is the artist?")
fi

if [ -z "$URL" ];then
    URL=$(ask_question "What is the URL?")
fi

if [ -z "$FORMAT" ];then
    FORMAT="mp3"
fi

URL="$(echo "$URL" | sed 's/"//g')"

# Download the file, extract audio, and set the ID3v2 tags.
"${YTDL}" --extract-audio --prefer-ffmpeg --audio-format ${FORMAT} \
  "${URL}" -o "${TITLE} - ${ARTIST}.%(ext)s"
mid3v2 "${TITLE} - ${ARTIST}.${FORMAT}" -a "${ARTIST}" -t "${TITLE}"
