#!/bin/sh
# work on this : improve
# youtube-dl wrapper to download web series / playlists / etc.
set -e
START=""

ask_question(){
	echo "$1"
	read answer
	echo $answer
}

check_command() {
  state=true
  for package in "${@}"; do
    if ! command -v "${package}" >/dev/null 2>&1;then 
      echo "MISSING: ${package} not installed."
      state=false
    fi
  done
  "${state}" && return 0 || return 1
}

videodir=
mediadir=
YTDL=yt-dlp

! check_command "${YTDL}" && exit 3

OPTIONS=d:n:r:s:u:
LONGOPTIONS=destination:,name:,resolution:,start:,url:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "${PARSED}"

while [ $# -ge 1 ]; do
  case "$1" in
    -d|--destination)
      VIDEODIR="$2"
      shift 2
      ;;
    -n|--name)
      NAME="$2"
      shift 2
      ;;
    -u|--url)
      URL="$2"
      shift 2
      ;;
    -r|--resolution)
      RESOLUTION=$(echo "$2" | tr -d 'pi')
      shift 2
      ;;
    -s|--start)
      START="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error: unknown command line option \"$2\"."
      exit 3
      ;;
  esac
done

if [ -z "$NAME" ];then
  NAME=$(ask_question "What is the name of the series?")
fi

if [ -z "$URL" ];then
  URL=$(ask_question "What is the URL?")
fi

if [ -z "$RESOLUTION" ];then
  RESOLUTION=720
fi

case "${RESOLUTION}" in
  720p|720i|720)
    HEIGHT=800
    WIDTH=1300
    ;;
  1080p|1080i|1080)
    HEIGHT=1200
    WIDTH=2000
    ;;
  *)
    HEIGHT=800
    WIDTH=1300
    ;;
esac

if [ -z "${VIDEODIR}" ];then
  if [ -n "${mediadir}" ] && [ -d "${mediadir}" ];then
    VIDEODIR="${mediadir}/Web Series"
  elif [ -n "${videodir}" ] && [ -d "${videodir}" ];then
    VIDEODIR="${videodir}"
  else
    VIDEODIR="$(pwd)"
  fi
fi


mkdir -p "${VIDEODIR}/${NAME}"
cd "${VIDEODIR}/${NAME}"

if [ -z "$START" ];then
  "${YTDL}" "${URL}" \
    --write-sub \
    --embed-subs \
    --add-metadata \
    --playlist-start "${START}" \
    --prefer-free-formats \
    --download-archive .archive.txt \
    -f "bestvideo[ext=mp4][width<${WIDTH}][height<=${HEIGHT}]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<${WIDTH}][height<=${HEIGHT}]+bestaudio[ext=webm]/bestvideo[width<${WIDTH}][height<=${HEIGHT}]+bestaudio/best[width<${WIDTH}][height<=${HEIGHT}]/best" \
    --ignore-errors
else
  "${YTDL}" "${URL}" \
    --write-sub \
    --embed-subs \
    --add-metadata \
    --prefer-free-formats \
    --download-archive .archive.txt \
    -f "bestvideo[ext=mp4][width<${WIDTH}][height<=${HEIGHT}]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<${WIDTH}][height<=${HEIGHT}]+bestaudio[ext=webm]/bestvideo[width<${WIDTH}][height<=${HEIGHT}]+bestaudio/best[width<${WIDTH}][height<=${HEIGHT}]/best" \
    --ignore-errors
fi
