#!/bin/sh
# if this line exist script will be part of hub script.
# work on this : improve
# Simple script to generate a script file in my scripts directory
. "$__distro_path_lib"
scripts_folder_="$HOME/script"
ans="${1-}"
if [ -z "$ans" ];then
	printf "File Name: "
	
	# Set a name for the script
	while [ -z "$ans" ];
		do
  		read -r ans
		
  		if [ -z "$ans" ];then
    		printf "File Name: "
  		fi
	done
fi
    
case "$ans" in
    *.bash) file2copyare="bash.bash";;
    *.fish) file2copyare="fish.fish";;
	*.ps1)  file2copyare="PowerShell.ps1";;
	*.zsh)  file2copyare="zsh.zsh";;
    *) 		file2copyare="sh.sh";;
esac

file="$scripts_folder_/$ans"

if [ ! -d "$scripts_folder_" ];then
	mkdir -p "$scripts_folder_"
fi

if [ -e "$scripts_folder_/$ans" ];then
	$CLI_EDITER "$file"
else
	cp -r "${__distro_path_root}/lib/Templates/ShellScripting/${file2copyare}" "$file"
	$CLI_EDITER "$file"
fi
