#!/bin/sh
# work on this : improve
set -eu
. "$__distro_path_lib"
"${__distro_path_root}/bin/not_add_2_path"/check_4_dependencies_if_installed nmcli sed || exit 1

nmcli conn | sed -n "s/.*\s\+\([0-9a-z\-]\+\)\s\+openvpn.*/\1/p" | while read -r CONN; do
    nmcli conn delete "$CONN"
done
