#!/bin/bash
set -euo pipefail
unalias -a
. "$__distro_path_lib"
"${__distro_path_root}/bin/not_add_2_path"/check_4_dependencies_if_installed ffmpeg find xargs || exit 1

show_error() {
  local red=$'\033[0;91m'
  local nc=$'\033[0m'
  if [[ "${1:--e}" =~ ^(-e|-n)$ ]];then
    echo "${1:--e}" "${red}${*:2}${nc}" 1>&2
  else
    echo -e "${red}${*}${nc}" 1>&2
  fi
}

show_header() {
  local cyan=$'\033[0;96m'
  local nc=$'\033[0m'
  if [[ "${1:--e}" =~ ^(-e|-n)$ ]];then
    echo "${1:--e}" "${cyan}${*:2}${nc}"
  else
    echo -e "${cyan}${*}${nc}"
  fi
}

#
# Functions
#

function do_strip_flac {
  local in="${1}"
  local tmp

  tmp=$(mktemp)
  trap 'rm -vf "${tmp}"' INT RETURN ERR TERM

  ffmpeg -v warning -i file:"${in}" -c copy -f ogg - |
    ffmpeg -v warning -i - \
      -map_metadata -1 -map 0:a -c:a copy -vn \
      -fflags +bitexact -flags:a +bitexact \
      -f flac file:"${tmp}" -y

  mv "${tmp}" "${in}"
}
export -f do_strip_flac

function do_strip_mp3 {
  local in="${1}"
  local tmp

  tmp=$(mktemp)
  trap 'rm -vf "${tmp}"' INT RETURN ERR TERM

  ffmpeg -v warning -i file:"${in}" -c copy -f avi - |
    ffmpeg -v warning -i - \
      -map_metadata -1 -map 0:a -c:a copy \
      -fflags +bitexact -flags:v +bitexact -flags:a +bitexact \
      -f mp3 file:"${tmp}" -y

  mv "${tmp}" "${in}"
}
export -f do_strip_mp3

#
# Main
#

show_header "Stripping ${*@Q}..."

if [ $# -eq 0 ];then
  show_error "ERROR: No path(s) provided. Exiting."
  exit 3
fi

find "${@}" -type f -iname "*.flac" -print0 |
  xargs -0 -I{} -P "$(nproc)" bash -c 'do_strip_flac "{}"'

find "${@}" -type f -iname "*.mp3" -print0 |
  xargs -0 -I{} -P "$(nproc)" bash -c 'do_strip_mp3 "{}"'

sync
