#!/bin/bash
# need superuser : use my-superuser
unalias -a
# View Apache logs
apachelog() {
	if [ -f /etc/httpd/conf/httpd.conf ];then
		cd /var/log/httpd && ls -xAh && multitail --no-repeat -c -s 2 /var/log/httpd/*_log
	else
		cd /var/log/apache2 && ls -xAh && multitail --no-repeat -c -s 2 /var/log/apache2/*.log
	fi
}

# Edit the Apache configuration
apacheconfig() {
	if [ -f /etc/httpd/conf/httpd.conf ];then
		my-superuser $CLI_EDITER /etc/httpd/conf/httpd.conf
	elif [ -f /etc/apache2/apache2.conf ];then
		my-superuser $CLI_EDITER /etc/apache2/apache2.conf
	else
		echo "Error: Apache config file could not be found."
		echo "Searching for possible locations:"
		my-superuser updatedb && locate httpd.conf && locate apache2.conf
	fi
}

# Edit the PHP configuration file
phpconfig() {
	if [ -f /etc/php.ini ];then
		my-superuser $CLI_EDITER /etc/php.ini
	elif [ -f /etc/php/php.ini ];then
		my-superuser $CLI_EDITER /etc/php/php.ini
	elif [ -f /etc/php5/php.ini ];then
		my-superuser $CLI_EDITER /etc/php5/php.ini
	elif [ -f /usr/bin/php5/bin/php.ini ];then
		my-superuser $CLI_EDITER /usr/bin/php5/bin/php.ini
	elif [ -f /etc/php5/apache2/php.ini ];then
		my-superuser $CLI_EDITER /etc/php5/apache2/php.ini
	else
		echo "Error: php.ini file could not be found."
		echo "Searching for possible locations:"
		my-superuser updatedb && locate php.ini
	fi
}

# Edit the MySQL configuration file
mysqlconfig() {
	if [ -f /etc/my.cnf ];then
		my-superuser $CLI_EDITER /etc/my.cnf
	elif [ -f /etc/mysql/my.cnf ];then
		my-superuser $CLI_EDITER /etc/mysql/my.cnf
	elif [ -f /usr/local/etc/my.cnf ];then
		my-superuser $CLI_EDITER /usr/local/etc/my.cnf
	elif [ -f /usr/bin/mysql/my.cnf ];then
		my-superuser $CLI_EDITER /usr/bin/mysql/my.cnf
	elif [ -f ~/my.cnf ];then
		$CLI_EDITER ~/my.cnf
	elif [ -f ~/.my.cnf ];then
		$CLI_EDITER ~/.my.cnf
	else
		echo "Error: my.cnf file could not be found."
		echo "Searching for possible locations:"
		my-superuser updatedb && locate my.cnf
	fi
}

case "$1" in
  apachelog)
    apachelog
    ;;
  apacheconfig)
    apacheconfig
    ;;
  phpconfig)
    phpconfig
    ;;
  mysqlconfig)
    mysqlconfig
    ;;
  *)
    echo "Usage: $0 {apachelog|apacheconfig|phpconfig|mysqlconfig}"
    exit 1
    ;;
esac
