#!/bin/sh -e
app_name="codium"

say "add Repo..." 1
download_key "gpg" "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg" "/usr/share/keyrings/vscodium-archive-keyring.gpg"
echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' | my-superuser tee /etc/apt/sources.list.d/vscodium.list

say "Update Repo..." 1
Package_update_

say "Installing ${app_name}..." 1
Package_installer_ ${app_name}
