#!/bin/sh -e
app_name="github-desktop"

say "add Repo..." 1
download_key "gpg" 'https://apt.packages.shiftkey.dev/gpg.key' '/usr/share/keyrings/shiftkey-packages.gpg'
add_repo "shiftkey-packages" 'deb [arch=amd64 signed-by=/usr/share/keyrings/shiftkey-packages.gpg] https://apt.packages.shiftkey.dev/ubuntu/ any main'

say "Update Repo..." 1
Package_update_
             
say "Installing ${app_name}..." 1                
Package_installer_ "${app_name}"
