#!/bin/sh
# Install vim and add lazygit distro
no_neovim="${1:-}"
app_name="lazygit"

__choice=""
if [ "${no_neovim}" = "no_neovim" ];then
	say "Installing Neovim..." 1
	install_as_dependency Neovim
fi

say "Installing ${app_name}..." 1
repobin --sudo install jesseduffield/lazygit || failed_to_run "failed to run ${app_name} ."
copy_from_extra_skel ".config/lazygit" || continue
