#!/bin/sh
# Install vim and add lazydocker distro
no_neovim="${1:-}"
app_name="lazydocker"

__choice=""
if [ "${no_neovim}" = "no_neovim" ];then
	say "Installing Neovim..." 1
	install_as_dependency Neovim
fi

say "Installing ${app_name}..." 1
repobin --sudo install jesseduffield/lazydocker || failed_to_run "failed to run ${app_name} ."
copy_from_extra_skel ".config/lazydocker" || continue
