#!/bin/sh -e
app_2_install="librewolf-bin"
app_name="librewolf"
set_as_default_package=true
prompt "  Do you want to set $app_name as default package?"  || set_as_default_package=false

say "Installing ${app_name}..." 1
Package_installer_ ${app_2_install} || continue

[ "$set_as_default_package" = true ] && my-alternatives --set "my-www-browser" "${app_name}"
