#!/bin/sh
# need superuser : called by my-superuser

set -e

__distro_path_lib="${1:-$__distro_path_lib}"
force_update="${2:-false}"

if [ "$force_update" = "--force-update" ];then
	force_update=true
fi

mv_generated_icons=false
current_path="$(dirname "$(realpath "$0")")"
source_base_path="${current_path}/source_base"
generated_dir="${current_path}/generated_icons"
universal_icons_dir=""

if [ -n "$__distro_path_lib" ];then
	if [ "$(id -u)" -ne 0 ]; then
    	my-superuser $0 "$__distro_path_lib" "$force_update"
    	exit
	fi
	. "$__distro_path_lib"
	universal_icons_dir="${__distro_path_themes}/system-icons"
	if [ -d "${__distro_path_themes}" ] && [ -d "${generated_dir}" ];then
		iconstheme_path="${generated_dir}"
		mv_generated_icons=true
	else
		iconstheme_path="${__distro_path_themes}/system-icons"
	fi
else
	iconstheme_path="${current_path}/generated_icons"
fi

if [ ! -d "${source_base_path}" ];then
	echo "source_base for gtk icons does not exit at ${source_base_path}." >&2
	exit
fi

list_of_base_files="$(find "${current_path}/source_base" -type f)"
mkdir -p "${iconstheme_path}"

echo "building All GTK Icons."

for theme_file in ${list_of_base_files};do
	output_theme_name="$(basename "$theme_file")"
	icons_output_dir="${iconstheme_path}/${output_theme_name}"
	if [ -d "$icons_output_dir" ] && [ "$force_update" = false ];then
		continue
	fi
	icons_style_name="$(grep "^ICONS_STYLE=" "$theme_file" | awk -F= '{print $2}')"			  
	"${current_path}/baseIcons/theme_builder.sh" "${current_path}/baseIcons" "${icons_style_name}" "${output_theme_name}" "${icons_output_dir}" "$theme_file"
done

if [ "$mv_generated_icons" = true ];then
	echo "Moving ${generated_dir}/* to ${universal_icons_dir}"
	mv "${generated_dir}"/* "${universal_icons_dir}"
	rm -rdf "${generated_dir}"
fi

echo "Done building All GTK Icons."
