#!/bin/sh
#called by : my-installer
app_name="heroic"
if check_system_ready_file "Distrobox_ready";then
	app_name="heroic-games-launcher-bin"
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
  	pacstall_install heroic-games-launcher-deb || continue
fi
