#!/bin/sh

app_name="heroic"
if [ -f '/usr/share/my_stuff/system_files/Distrobox_ready' ];then
	app_name="heroic-games-launcher-bin"
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
  	pacstall_install heroic-games-launcher-deb || continue
fi
