#!/bin/sh

app_name="minigalaxy"
if [ -f '/usr/share/my_stuff/system_files/Distrobox_ready' ];then
	Distrobox_package_installer_ ${app_name} || continue
else
	say 'Installing package...' 1
	cd "$(mktemp -d)"
	download_url="$(getURL '2term' 'https://api.github.com/repos/sharkwouter/minigalaxy/releases/latest' \
		| grep '"browser_download_url"' \
		| grep '.deb' \
		| cut -f2,3 -d':' \
		| tr -d '"')"
	getURL 'download' "$download_url"
	install_deb ./minigalaxy_*.deb
fi
