#!/bin/sh
app_name="virtualbox"
my-installer --tweek "Enable_virtualization" || continue

Package_update_

say 'Installing package...' 1
Package_installer_ virtualbox virtualbox-host-kmp-default || continue

my-superuser modprobe vboxdrv
my-superuser modprobe vboxnetflt
my-superuser modprobe vboxnetadp

my-superuser usermod -aG vboxusers $USER 

. "${_APPS_LIBDIR}/hypervisors/virt/post_virtual_install.sh"
