#!/bin/sh
#called by my-installer
"${__distro_path_root}"/bin/not_add_2_path/my-installer-installer --install-needed "GPU" || continue
say 'Installing package...' 1
Package_installer_ -y wine dbus git lutris protonplus

remove_system_ready_file GPU_Drivers_ready
generate_system_ready_file Gaming_ready
