#!/usr/bin/expect --
# askpass implementation for doas

# don't mind the man behind the curtain
log_user 0

# no command, then nothing to do
if { $argc == 0 } { exit 0 }

# treat first argument as password input
set pwd [lindex $argv 0];
# treat all arguments as command input
set cmd [lrange $argv 1 end];

# spawn doas operation
spawn my-superuser {*}$cmd

# send password and execute command
expect "doas*password:" {
	send -- "$pwd\r"
	expect \r
	log_user 1
	expect eof
}
