#!/bin/sh

download_key "gpg" "https://updates.signal.org/desktop/apt/keys.asc" "/usr/share/keyrings/signal-desktop-keyring.gpg"
add_repo "signal-xenial" 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main'

Package_update_
clear

say 'Installing signal-desktop ...' 1
Package_installer_ signal-desktop || continue
