#!/bin/sh
# Install vim and add localsend distro

app_name="localsend"
say "Installing ${app_name}..." 1
repobin --root --ext deb install localsend/localsend || failed_to_run "failed to run ${app_name} ."
